### ISSUE TITLE
Architecture-specific options are evaluated for host arch, not jail arch

### ISSUE THREAD

**Issue by clausecker** [freebsd/poudriere#1012]
When interactively configuring a port with `poudriere testport -c`, the options seem to be configured for the architecture of the host, not of the jail.  So e.g. when building on an amd64 host with an i386 jail and the port has

    OPTIONS_DEFINE_i386= FOO

then Poudriere does not show the option `FOO` as available.

**Comment by bdrewery** [comment]
It's due to #214. We can at least fix the architecture problem for now though.

**Comment by bdrewery** [comment]
Oh `testport`! I was testing `options`.
