### ISSUE TITLE
[question] Can MAX_MEMORY setting work per-port?

### ISSUE THREAD

**Issue by yurivict** [freebsd/poudriere#1016]
Currently MAX_MEMORY is a global setting. However, there is at least one port that requires more memory to build: science/py-tensorflow.

Is it possible to allow to set MAX_MEMORY per-port: MAX_MEMORY_${PKGBASE}?

Currently MAX_FILES allows to specify per-port values MAX_FILES_${PKGBASE}. MAX_MEMORY should be similar.

**Comment by bdrewery** [comment]
No problem. I'll add that.

Also makes me think we should move to `rctl` for everything here. The `ulimit` method is pre-process in each jail rather than per-jail.
