### ISSUE TITLE
manpage of poudriere-options(8) does not document "-o" option

### ISSUE THREAD

**Issue by michael-o** [freebsd/poudriere#1020]
## Prerequisites
- [X] Have you checked for an existing issue describing your problem?
- [X] Are you running the latest version?
- [X] Is your ports tree recent?
- [X] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
`./src/share/poudriere/options.sh` contains `-o` and also evaluates it, but https://github.com/freebsd/poudriere/wiki/poudriere-options.8-devel#options does not describe it. It is either a hidden or officially unsupported feature. Please document propertly.

**Comment by bdrewery** [comment]
It was added in 6eea9e5ef4a53da98f6aac32ec00a8b11d97a2a0 but I forgot to update the wiki. That's done now. Thanks!
