### ISSUE TITLE
How do I stop poudriere from building things it doesn't need to build?

### ISSUE THREAD

**Issue by heliosyne** [freebsd/poudriere#1028]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
Despite having poudriere configured to fetch pkgs (and seeing it do so), poudriere is still trying to build everything, including things like rust and llvm, which take hours to build and often fail. I have only three ports with non-default options: dovecot, postfix, and postfixadmin. None of these are dependencies of anything else, so it should only need to build those three pkgs and get everything else from the public repo. Instead, poudriere downloads a bunch of packages, then deletes them, and queues up 632 builds.

## Expected behavior
I expect poudriere to compare the configured options I have for ports to those recorded in pkgs (something I know it can do), realize that the version I need is already in the public repo, and skip building that port. Poudriere should queue up just a handful of builds, not 632.

## Environment
 - FreeBSD 12.3
 - Poudriere 3.3.99.20220831
 - Ports branch is head, commit 908640ce3450dc5e55fee0fefea407b1a0aec693
 
I'm am unsure what additional information you need, but please do ask.

If I sound frustrated it's because I am extremely so. I've been at this for days. I haven't found any useful mailing list, forum, or blog posts about it, and the docs say it shouldn't be doing this. I have port updates I need to get out, but I can't do that because poudriere will spend all night building llvm and rust, when it doesn't need to do so, only to fail on either/both after hours of work, leaving me a 100,000-line log full of compiler warnings to sift through.

**Comment by bdrewery** [comment]
Currently it is possible for packages to be fetched and then deleted by the incremental build algorithm. That will be fixed in #822.
