### ISSUE TITLE
Poudriere doesn't fail to build the port that is in MOVED when it has flavor

### ISSUE THREAD

**Issue by yurivict** [freebsd/poudriere#1030]
If ```math/slepc``` is in MOVED - poudriere fails to build it.
But if ```math/py-slepc4py``` is in MOVED - poudriere doesn't fail to build it.
The reason, I think, is because the latter has flavor.

**Comment by bdrewery** [comment]
#541 probably fixes this. Do you have `MOVED` entries to show me?

**Comment by yurivict** [comment]
Commits 8dfcd1f2a8c9f11755447eddd98b8a8ab3ebc8a3 and fdeb11a438e2d3851b2689aa9ec82b4a99b19e88 removed them.

**Comment by bdrewery** [comment]
Going to say #541 fixed this for now. Open a new bug if a new issue comes up.
