### ISSUE TITLE
Poudriere's error handler for zfs tries to destroy the wrong zpool

### ISSUE THREAD

**Issue by davidchisnall** [freebsd/poudriere#1072]
The error handler force unmounts `${zroot}` not `${tmpzroot}`.  By default, the pool created with Poudriere has the same name as the pool created by the installer, so this has the effect of force unmounting the root zpool.  This unmounts all filesystems except the root, which completely breaks the system.

I have changed this:

```
        [ -z "${zroot}" ] || zpool destroy -f ${zroot}
```

to this:

```
    # If the ZPOOL has an alternative name, delete it using that.  If not then delete it with the 
    if [ -n "${tmpzroot}" ]; then
        zpool destroy -f ${tmpzroot}
    else
        [ -z "${zroot}" ] || zpool destroy -f ${zroot}
    fi

```

in `delete_image` in `image.sh`, but I am not sure whether we actually need to destroy `${zroot}` in any situation.

**Comment by jlduran** [comment]
I wonder if it is related to #1036?

**Comment by davidchisnall** [comment]
I think that’s what introduced the alternative name, it didn’t update the error handling cleanup.

**Comment by jlduran** [comment]
I believe you have might be using poudriere-devel from ports. There is no `tmpzroot` after #1036.

**Comment by davidchisnall** [comment]
Yup, looks like it's fixed here.  Maybe someone could update the port.  The poudriere port is on a 2021 release and -devel is a year-old snapshot.  The release can't build working ZFS images at all, the -devel version can but kills the host system if anything goes wrong.

**Comment by jlduran** [comment]
See: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274726
