### ISSUE TITLE
poudriere image fails with error from mkimg

### ISSUE THREAD

**Issue by einsibjarni** [freebsd/poudriere#1098]
## Prerequisites
- [ x] Have you checked for an existing issue describing your problem?
- [ x] Are you running the latest version?
- [ x] Is your ports tree recent?
- [ x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug

After upgrading the host to 14.0-RELEASE (and now on 14.0-RELEASE-p2) `poudriere image ... -t zfs+gpt ... ` fails with:

```
mkimg: partition 2: Invalid argument
```

## How to reproduce

Run `poudriere image -v -j 132amd64 -p 132amd64_default -z default -n template -h freebsd-template -s 3g -t zfs+gpt -f /usr/local/etc/poudriere.d/buildlists/132amd64`

## Expected behavior

A working image is created

## Screenshots
<If applicable add screenshots to help explain your problem.>

## Environment
 - Host OS [e.g. 12.2 amd64]:
14.0-RELEASE-p2
 - Jail OS [e.g. 12.0 powerpc]: 
 13.2-RELEASE-p7
 - Browser: [e.g. chrome, safari]: 
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: 
3.4.99.20231113
 - Ports branch and revision [e.g. 2020Q3 r550754]:

## Additional context
The problem is in https://github.com/freebsd/poudriere/blob/9143ab494773f7a1ba69efc31177d4bbfe51bf7f/src/share/poudriere/image_zfs.sh#L172

If I change the line to
```
gptboot="-p freebsd-boot:=${mnt}/boot/gptzfsboot"
```
The error dissapears, but the image is not valid and will not boot.
Reading `mkimg` usage instructions and git commit messages, I've tried multiple different versions of the command "-p freebsd-boot:=${mnt}/boot/gptzfsboot::512k" etc.

Looking at `mkimg` output on 13.2-RELEASE-p5, I can't see that the current version of the code could ever have worked...

```
partition specification:
	<t>[/<l>]::<size>[:[+]<offset>]	-  empty partition of given size and
					   optional relative or absolute offset
	<t>[/<l>]:=<file>[:[+]offset]	-  partition content and size are
					   determined by the named file and
					   optional relative or absolute offset
	<t>[/<l>]:-<cmd>		-  partition content and size are taken
					   from the output of the command to run
	-				-  unused partition entry
	    where:
		<t>	-  scheme neutral partition type
		<l>	-  optional scheme-dependent partition label
```

**Comment by einsibjarni** [comment]
If I change the line to `gptboot="-p freebsd-boot:=${mnt}/boot/gptzfsboot"` *AND* set zpool -o compatibility=openzfs-2.1-freebsd, I can boot the image in BIOS mode. It won't boot in UEFI.

**Comment by jlduran** [comment]
The problem with that change is that it would create a `freebsd-boot` partition the size of `/boot/gptzfsboot`(~173K), and we want it to be 512K (to keep it inline with `bsdinstall`).
Regarding the EFI boot, I was able to boot without problems, with an image that has the same zpool version as the builder. Base releases use `makefs -t zfs` to overcome this issue (among other things).

**Comment by jlduran** [comment]
Apparently #962 (taken from #958) never fixed the issue, just avoided a failed assertion.
Would you mind trying with:
```
gptboot="-p freebsd-boot::512k"
```

**Comment by jlduran** [comment]
Waiting on feedback from @einsibjarni before submitting.
Possible patch, if OK (https://github.com/jlduran/poudriere/commit/4f33a15924df67ef9bdb8b84fc442940196067c1).
(Only tested with `sh /usr/share/examples/bhyve/vmrun.sh -u -m 4G -t tap0 -d /usr/local/etc/poudriere.d/buildlists/132amd64 132amd64`, with and without `-E` for EFI booting).

**Comment by einsibjarni** [comment]
Tested https://github.com/jlduran/poudriere/commit/4f33a15924df67ef9bdb8b84fc442940196067c1 and it fixed the problem. 
Booted without problems with EFI
