### ISSUE TITLE
Make shell configurable for interactive mode

### ISSUE THREAD

**Issue by michael-o** [freebsd/poudriere#1142]
## Prerequisites
- [X] Have you checked for an existing issue describing your idea?

## What is your proposal?
Make shell configurable in `poudriere.conf` for https://github.com/freebsd/poudriere/blob/86d95d6bbe54359f839440546b1a95f2318fb1fe/src/share/poudriere/common.sh#L2526

## What is the existing behavior, if any?
It is always `csh`

## What is the motivation / use case for the change?
I'd prefer to use bourne shell `sh`

**Comment by michael-o** [comment]
Magic, fast!

**Comment by bdrewery** [comment]
I'll update the -devel port later today.

**Comment by bdrewery** [comment]
This was not enough. Even now in 14+ (maybe earlier I did not check) the default root shell was changed to /bin/sh.
