### ISSUE TITLE
Error: download_from_repo_post_delete: We lost fetched unversioned

### ISSUE THREAD

**Issue by fraenki** [freebsd/poudriere#1165]
## Prerequisites
- [X] Have you checked for an existing issue describing your problem?
- [X] Are you running the latest version?
- [X] Is your ports tree recent?
- [X] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
poudriere-devel-3.4.99.20240709 fails with the following error:

```
# poudriere bulk -j f141amd64 -p f141build1 -z default -b latest -f default-pkglist
...
[00:06:19] Deleting py311-sqlite3-3.11.9_7.pkg: missing dependency: sqlite3-3.46.0,1
...
[00:00:47] Package fetch: Generating logs for fetched packages
[00:00:47] Error: /usr/local/share/poudriere/bulk.sh:download_from_repo_post_delete:20:download_from_repo_post_delete: We lost fetched unversioned py311-sqli
te3-3.11.9_7.pkg
Error: (2487) /usr/local/share/poudriere/bulk.sh:download_from_repo_post_delete:257: set -e error: status = 70
```

## How to reproduce
1. Install poudriere-devel
2. Run the previously mentioned build command

## Expected behavior
Build should ignore errors with pre-fetched packages and build the required package.

## Environment
 - Host OS [e.g. 12.2 amd64]: 14.1 amd64
 - Jail OS [e.g. 12.0 powerpc]: 14.1 amd64
 - Browser: [e.g. chrome, safari]: ---
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: poudriere-devel-3.4.99.20240709
 - Ports branch and revision [e.g. 2020Q3 r550754]: latest

**Comment by fraenki** [comment]
I've realized that this is the intended behaviour:

https://github.com/freebsd/poudriere/blob/4702d1e498d5865b477ca10d19709165caa50862/src/share/poudriere/common.sh#L4481-L4484

So I'm hereby reporting this failure. :)

**Comment by grahamperrin** [comment]
Thanks, see also: 

- [280270 – ports-mgmt/poudriere-devel: We lost fetched unversioned doxygen](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280270)

– you can add a cross-reference from there, to here.

**Comment by bdrewery** [comment]
Sorry, the error being a hard assertion is correct but only when PKG_NO_VERSION_FOR_DEPS is set to "yes". It is "no" by default.
It is a beta feature I have not fully announced yet. The error
should not be an error otherwise. An update to the port will be
out shortly.

**Comment by bileslav** [comment]
Hi @bdrewery,

I use `poudriere-devel` and `PKG_NO_VERSION_FOR_DEPS=yes`. As I see, the error is expected/intended in this case. However, I don't really understand it. Should such cases be considered an error in the port Makefile?

I'm getting the error when building an indirect dependency on `libepoll-shim`. I got around it by using `PACKAGE_FETCH_BLACKLIST=libepoll-shim`:

```
*fetching packages*
[00:00:28] Checking packages for incremental rebuild needs
[00:00:29] Deleting libepoll-shim-0.0.20240608.pkg: FLAVOR changed to 'default' from ''
[00:00:29] Deleting stale symlinks... done
[00:00:30] Deleting empty directories... done
[00:00:30] Package fetch: Generating logs for fetched packages
[00:00:30] Error: /usr/local/share/poudriere/[bulk.sh](https://bulk.sh/):download_from_repo_post_delete:36:download_from_repo_post_delete: We lost fetched unversioned libepoll-shim-0.0.20240608.pkg
Error: (62801) /usr/local/share/poudriere/[bulk.sh](https://bulk.sh/):download_from_repo_post_delete:265: set -e error: status = 70
[00:00:30] Cleaning up
[00:00:30] Unmounting file systems
```
