### ISSUE TITLE
Make devfs rules configurable

### ISSUE THREAD

**Issue by arrowd** [freebsd/poudriere#1173]
Currently Poudriere makes no use of `/etc/devfs.rules`, but instead add rules on the fly in `common.sh:do_jail_mounts`. I want to pass through the `/dev/zfs` device into the jail and there is even a ruleset ready to be used in `/etc/defaults/devfs.rules`. unfortunately, there is no way to tell Poudriere to use these rules.

Related issue: https://github.com/freebsd/poudriere/issues/682

**Comment by bdrewery** [comment]
#1175 addresses this.
