### ISSUE TITLE
a few improvements to common.sh

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#139]
- Unroll bset stats_\* loop. There are only three items in it,
  so IMHO much clearer to just use 3 bset lines
- Whitespace nit
- Simplify conditions, e.g if not not empty($nbq) -> if empty($nbq)
- Replace two fetch in immediate succession to fetch -a (retry on soft errors)
- Refactore mtree's exclude list handling. Now there is commond list
  and additional items for each state. This allows to see what difference
  between prepkg/prebuild/preinst checks more easily and reduces the code.
  I also used ./compat/linux/proc/ in all checks and removed ./var/db/pkg/*
  from preinst, it's covered by ./var/db/*

**Comment by bdrewery** [comment]
A lot of this is done already and otherwise is just style.
