### ISSUE TITLE
list of packages 'to build' on web stats

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#142]
it would be nice to see a list of ports that are queuing to build. Now I can see only "To build: XXX" via web interface/`poudriere status 10-CURRENT-latest`

**Comment by grahamperrin** [comment]
Is this implemented? (Do I misunderstand?)

![image](https://user-images.githubusercontent.com/192271/126678601-b6007298-c2d4-46e0-9dd6-decb38866d4b.png)

Nit: I'd like the queue to shorten after each queued item is handled.

**Comment by bdrewery** [comment]
The queued table is _initially_ queued. To see the "build queue", or "remaining", requires setting `HTML_TRACK_REMAINING=yes` in poudriere.conf. It's disabled as it is not implemented well and takes up more resources and I wasn't comfortable enabling by default.

**Comment by bdrewery** [comment]
So yeah implemented.
