### ISSUE TITLE
please add -o option to poudriere bulk

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#180]
When using the bulk subcomment, please permit to specify a port's origin with an -o option (just as though it were placed on the command line bare).  This is to allow for symmetry with testport.

This change (allow poudriere bulk -j MYJAIL -p MYPORTSTREE -o category/port) would allow a successful "testport" to minimally be re-run as "bulk" without also removing the -o option.

**Comment by bdrewery** [comment]
Imported ticket. Will fix in #338.
