### ISSUE TITLE
Update version for jails after update via freebsd-update

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#213]
After upgrading (within the same -RELEASE) a jail installed via ftp or http method, version shown with poudriere jail -l is not updated. The following patch fixes this.

--- /usr/local/share/poudriere/jail.sh.orig     2014-07-31 12:57:56.696463595 +0200
+++ /usr/local/share/poudriere/jail.sh  2014-07-29 15:18:17.475784437 +0200
@@ -125,6 +125,10 @@
                jstart 1
                if [ -z "${TORELEASE}" ]; then
                        injail env PAGER=/bin/cat /usr/sbin/freebsd-update fetch install
+                       eval `grep "^[RB][A-Z]*=" ${JAILMNT}/usr/src/sys/conf/newvers.sh `
+                       RELEASE=${REVISION}-${BRANCH}
+                       jset ${JAILNAME} version ${RELEASE}
+                       update_version ${RELEASE}
                else
                        # Install new kernel
                        injail env PAGER=/bin/cat /usr/sbin/freebsd-update -r ${TORELEASE} upgrade install ||

Maybe it is not wanted to show the specific patch version, but it was a bit annoying when my jail was listed as 10.0-RC2 when it was 10.0-RELEASE-p7. Some packages do record the version on which they were compiled, so giving them the wrong info seems "bad".

**Comment by so14k** [comment]
Confirmed. Before:

```
# poudriere jail -l
JAILNAME      VERSION         ARCH  METHOD TIMESTAMP           PATH
100-test      10.0-RELEASE-p8 amd64 http   2014-09-10 22:22:49 /usr/local/poudriere/jails/100-test
```

[ .. update .. ]

```
# poudriere jail -l
JAILNAME      VERSION          ARCH  METHOD TIMESTAMP           PATH
100-test      10.0-RELEASE-p16 amd64 http   2015-01-25 16:09:10 /usr/local/poudriere/jails/100-test
```
