### ISSUE TITLE
qemu user mode doesn't work with USE_TMPFS=localbase

### ISSUE THREAD

**Issue by AMDmi3** [freebsd/poudriere#227]
When cross-compiling packages with qemu user mode, any build will fail with errors such as ```jexec: execvp(): env: No such file or directory``` and ```jexec: execvp(): make: No such file or directory```. This probably happens because qemu binary is located in jail's /usr/local which is umounted and then remounted as tmpfs in case of USE_TMPFS=localbase -> qemu binary is no longer accessible. Best solution would probably be to place qemu binary in jail's /usr/bin or /bin - this will fix both /usr/local remount problem and won't interfere with package builds which modify localbase.

**Comment by bdrewery** [comment]
This is likely fixed by 54183f5f which made it into 3.1.2

**Comment by bdrewery** [comment]
Closing, working for me.
