### ISSUE TITLE
updating armv6 jail fails

### ISSUE THREAD

**Issue by rene0** [freebsd/poudriere#255]
Building an initial 10.1-armv6 jail on a 10.1-amd64 host (without the -x option) works fine, but updating it with 'poudriere -j JAIL -u' fails after updating the SVN source with:
make[1]: "/usr/local/poudriere/jails/rpi/usr/src/Makefile.inc1" line 151: Unknown target armv6:armv6.

% cat  /usr/local/etc/poudriere.d/jails/rpi/arch
armv6

The initial build was with poudriere 3.1-rc3 (iirc), the failed update is with both poudriere 3.1-rc3 and poudriere 3.1.1

**Comment by rene0** [comment]
I think this can be closed?

**Comment by miwi-fbsd** [comment]
Can we please get this documented somewhere? I just run in the same problem :)
