### ISSUE TITLE
If there is an issue with the signing key, Poudriere spits out a nonsensical error message

### ISSUE THREAD

**Issue by RobotsOnDrugs** [freebsd/poudriere#257]
Poudriere 3.1.1, FreeBSD 10.1

I recently moved an instance of Poudriere from one machine to another, and everything was good until I actually went to build some packages. At the end, there was this one very unhelpful and, IMO, nonsensical error message:
rm: /usr/local/poudriere/data/.m/101x64-default-py27/ref/tmp/repo.key: Operation not permitted

That directory does get created during the run, and there is nothing special about that jail or dataset, so for it to return 'Operation not permitted' when trying to delete that file is very puzzling. I finally figured out that I had the wrong key file set up as the signing key, and with the correct one in place, Poudriere runs without issue. Even something generic like 'Could not sign repo' here would have been helpful. Another thing to note is that Poudriere did not seem to notice that something was wrong and simply output
[00:00:42] ====>> Cleaning up
[00:00:42] ====>> Umounting file systems
after the error message.

**Comment by bdrewery** [comment]
Everything I've tried I cannot reproduce this.
