### ISSUE TITLE
poudriere distclean requires options

### ISSUE THREAD

**Issue by ari** [freebsd/poudriere#263]
Executing just

    poudriere distclean

results in no action, but printing of usage. However none of the options are mandatory. Passing any option (even -v) allows it to continue.

**Comment by so14k** [comment]
This works for me on poudriere-devel. What version do you have installed?

**Comment by bdrewery** [comment]
This was fixed in 3.1.0 from f56cc55c7ef458167c62f868636e38b706722c74
