### ISSUE TITLE
'real' symlinks in package repo breaks caching

### ISSUE THREAD

**Issue by ari** [freebsd/poudriere#265]
We distribute packages built via poudriere to remote data centres by using rsync after the poudriere bulk run is complete. Since a recent poudriere upgrade there is now a new folder structure in the repository.

lrwxr-xr-x  1 root  wheel  16 Jan 11 21:33 .latest -> .real_1420972418
drwxr-xr-x  4 root  wheel   8 Jan 11 21:33 .real_1420972418
lrwxr-xr-x  1 root  wheel  11 Dec 27 04:16 All -> .latest/All
lrwxr-xr-x  1 root  wheel  14 Dec 27 04:16 Latest -> .latest/Latest
lrwxr-xr-x  1 root  wheel  19 Dec 27 04:16 digests.txz -> .latest/digests.txz
lrwxr-xr-x  1 root  wheel  16 Dec 27 04:16 meta.txz -> .latest/meta.txz
lrwxr-xr-x  1 root  wheel  23 Dec 27 04:16 packagesite.txz -> .latest/packagesite.txz

Unfortunately that means that if a single package is updated, the entire repository is synchronised over rsync again. I can't determine a simple way to avoid this, other than scripts which unravel the whole repository structure.

Can we disable this new feature?

**Comment by so14k** [comment]
I have experienced this as well.

**Comment by ari** [comment]
I understand the reason for the new feature was to provide atomic deployment. However another way to achieve that would be to just 'mv' the final folder into place at the end. The problem with renaming the folder is a very significant one for us since it breaks our the ability to duplicate (rsync) the repository to other locations.

**Comment by so14k** [comment]
Understood. I will have a look.

**Comment by bdrewery** [comment]
You can disable the feature by setting `ATOMIC_PACKAGE_REPOSITORY=no` in poudriere.conf, or always sync the actual directory by dereferencing .latest.

I distribute my package repo to S3 just fine via a bulk.sh hook. https://github.com/freebsd/poudriere/wiki/hooks. From the hook you can rsync `$(realpath ${PACKAGES})` which will reference the *real* directory and not the top-level one.

This will remain the default.

**Comment by bdrewery** [comment]
You could also $(realpath /usr/local/poudriere/data/packages/.../whatever/.latest) the same way and get the real directory. Just rsync that, not the top-level.
