### ISSUE TITLE
Cache jail installation files for all non-src based (or binary based) -m <method>'s

### ISSUE THREAD

**Issue by koobs** [freebsd/poudriere#271]
Would help save bandwidth & time, especially when trying to reproduce/debug jail based errors / environments where you want a clean environment every time.

Potentially made optional (opt-in) for jail -c calls with a new arg (-C ?)

**Comment by so14k** [comment]
Good idea.

**Comment by bdrewery** [comment]
This can possibly be mitigated by using a caching proxy and `FTP_PROXY` / `HTTP_PROXY`.

**Comment by bdrewery** [comment]
Duplicate of #137
