### ISSUE TITLE
Single package build may fail and succeed at the same time

### ISSUE THREAD

**Issue by AMDmi3** [freebsd/poudriere#273]
I'm trying experimental port build run with projects/clang360-import branch (where anything is possible), and I've encountered a single package (namely pkg) succeed and fail (clean_pool phase) at the same time.

[Build log](https://people.freebsd.org/~amdmi3/pkg-clean_pool.log)

**Comment by bdrewery** [comment]
Yes it's confusing. The pkg build passed fine, but a poudriere action unrelated to building the package failed for some reason.

**Comment by bdrewery** [comment]
Is this reproducible? It would help if you ran `poudriere -x bulk ...` and then provided the pkg build log.
