### ISSUE TITLE
Possibly incorrect nginx config example

### ISSUE THREAD

**Issue by AMDmi3** [freebsd/poudriere#274]
I've just created a new jail in my poudriere and started a build, however the jail haven't appeared on poudriere main page serverd with nginx. I've opened http://<server>/data/.data.json and it didn't contain new build until I refreshed it. It makes me suspect that example nginx config is incorrect:

```add_header Cache-Control "public, must-revalidate, proxy-revalidate";```

I'm not a pro in http caching/nginx config, but maybe it needs ```no-cache``` instead?

**Comment by bdrewery** [comment]
The actual request for data.json is done with `Cache-Control: max-age=0` to force a recheck/no cache. So it should be working fine.

The example config is highly optimized; none of the caching bits are actually needed for a working setup.

**Comment by AMDmi3** [comment]
Still it doesn't work.
