### ISSUE TITLE
feature request: make test

### ISSUE THREAD

**Issue by assistcontrol** [freebsd/poudriere#280]
It would be incredibly helpful to have a `testport` switch that adds `TEST_DEPENDS` to `RUN_DEPENDS` and runs `make test` after build.

**Comment by bdrewery** [comment]
There needs to be Mk/ framework support first.

**Comment by assistcontrol** [comment]
Running `make test` directly from `${WRKSRC}` makes part of it easier.

Even just adding `TEST_DEPENDS` to `RUN_DEPENDS` makes `testport -i` easier to run `make test` yourself in.

I do understand what you mean though. `RUN_DEPENDS` are added from `make run-depends-list` IIRC.

**Comment by assistcontrol** [comment]
Adding a reference to FreeBSD bug #198494 (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198494).

**Comment by bdrewery** [comment]
There's a decent implementation at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=164896 that needs to be rebased and tweaked a little.

My concern is that I don't want to put much special logic in poudriere for ports. Another tool may come along and decide it should do things differently. This happened with Tinderbox->Poudriere. It's better if the framework defines how things should work and the rules behind them. Then no tool can be wrong.

**Comment by bdrewery** [comment]
#355
