### ISSUE TITLE
getaddrinfo(3) failure when building bulk, interactive works

### ISSUE THREAD

**Issue by saper** [freebsd/poudriere#287]
While there are or were some getaddrinfo(3) handling issues in node/npm  https://github.com/npm/npm/issues/7508, https://github.com/joyent/node/pull/9212) there is something strange happening:

I build a local port (`textproc/node-sass`, not yet in the tree) with:

     poudriere bulk -i -j nodejs_10_1_amd64 -p exp textproc/node-sass

and the build fails in npm with getaddrinfo(3) problem:

```
npm ERR! code EAI_FAIL
npm ERR! errno EAI_FAIL
npm ERR! syscall getaddrinfo
```

Full log: https://gist.github.com/anonymous/b1a9680802336c1ab059

However, after the failure, when I drop into the `-i` shell I can cd to `/usr/ports/www/node-sass`
and compile that port using `make stage` without problems.

DNS resolution also works, I have 2 IPv6 and 5 IPv6 addresses configured on the interface
and visible in the poudriere jail.

Local port tree changes (https://github.com/saper/ports-exp):
- `textproc/libsass` and `textproc/sassc` ports updated
- local patch for `www/npm` on i386 to work around [FreeBSD bug 198350: [www/node] segfault when installing npm on 8.4, 9.3 on i386](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198350) which is caused by the kernel [bug 178881: getifaddrs(3) does not report IPv6 addresses properly in 32-bit compatibility mode](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=178881)

Portshaker configuration:

```
mirror_base_dir="/var/cache/portshaker"
poudriere_ports_mountpoint="/usr/local/poudriere/ports"
ports_trees="exp"
exp_poudriere_tree="exp"
exp_merge_from="ports myrepo"
```

Portshaker `myrepo` configuration:

```
#!/bin/sh
# $Id$

. /usr/local/share/portshaker/portshaker.subr

# Update ports using portsnap (faster)
method="rsync"

# *OR* update ports using csup (hidden portshaker ninja gurus)
#method="csup"
#csup_supfile="/usr/local/etc/portshaker.d/ports-supfile"
rsync_source_path="/home/saper/sw/FreeBSD/"

run_portshaker_command $*
```

**Comment by brd** [comment]
This is because poudriere does not allow network access in the stage part of the build (only in the fetch phase IIRC). You might look at the FreeBSD node port to see how they get around this. But basically it is to prevent software from pulling in things that are unexpected and not properly setup in the ports Makefile. I imagine you can just disable that network test.

**Comment by saper** [comment]
Makes sense. 
[npm](https://github.com/npm/npm) is fetching dependencies automatically during `install` step.

`node` does not have this problem and the only package depending on node and npm in the tree is `www/uglifyjs`, which... does not have any dependencies, so nothing needs to be fetched.

Maybe I can force npm to do the download in the fetch phase.

**Comment by brd** [comment]
You might need to create additional ports for those dependencies.

**Comment by saper** [comment]
No way, there so many of them!

Plus I think there is no way we can sanely support node_modules dependency model with ports easily (every module can have it's `node_modules` directory where its "local" dependencies are).

So they nicely recurse, avoiding the "DLL hell" problem:

https://gist.github.com/1c887b483de687b024ca

Let's see if I can run npm in the `post-fetch` target

**Comment by saper** [comment]
Well, I can't :) because it need an unpacked `package.json` file (from `$WRKSRC`) - and it's not yet there. In `post-extract` I have no network.

**Comment by brd** [comment]
Ouch.

**Comment by saper** [comment]
Some progress:  9564a103caaa99e2c1c93d4db5b52febaf33a9e7

**Comment by brd** [comment]
Cool! In between which phases?

**Comment by bdrewery** [comment]
The bug for getifaddrs(3) is described at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=178881. I am working on a proper patch to fix the problem in head.

There's a temporary fix for npm at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=198350

**Comment by saper** [comment]
Thanks @bdrewery ! I think I reported 198350 :) Looks like the simpler fix for 9.x/10.x posted on bug 178881 does not work for me

**Comment by saper** [comment]
After a lot of fighting I finally got this port to build offline using poudriere https://github.com/saper/ports-exp/commit/86b8a08728c4e76f15b7078c2d9ec06e2bded99a

Thank you for your patience :)

**Comment by bdrewery** [comment]
@saper The "simpler" fix you mention. Which was it? Was it what I have in https://reviews.freebsd.org/D2131?

**Comment by saper** [comment]
I mean https://bugs.freebsd.org/bugzilla/attachment.cgi?id=134236 (ported as https://bugs.freebsd.org/bugzilla/attachment.cgi?id=154041 to 10.1) which were originally attached to the bug. This is before the code got refactored; but still it does not work for my 10.1 system.

**Comment by bdrewery** [comment]
@saper Your host is 10.1-RELEASE?

**Comment by saper** [comment]
10.1-STABLE, `r279751`

**Comment by cpu82** [comment]
@bdrewery Same problem here. Also tested on jails 93/amd64, 93/i386 
```
<snip>
pm ERR! FreeBSD 10.1-RELEASE-p15
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--ignore-scripts" "/wrkdirs/usr/ports/deskutils/ladon/work/ladon-1.0.6"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.2
npm ERR! code EAI_FAIL
npm ERR! errno EAI_FAIL
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo EAI_FAIL
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /wrkdirs/usr/ports/deskutils/ladon/work/stage/usr/local/lib/npm-debug.log
*** Error code 1
```
Any thoughts how to handle this?

**Comment by bdrewery** [comment]
It's a bug in the kernel, still present. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=178881

**Comment by cpu82** [comment]
Thanks @bdrewery. 

So we can't overcome this problem ATM. Do we have any temporary fix or dirty hack?

**Comment by bdrewery** [comment]
Sure, read this issue, there are links.

**Comment by cpu82** [comment]
@bdrewery have you updated the rtsock.c patch for 10.2-RELEASE? It fails to builkernel using this one:
https://reviews.freebsd.org/file/data/iucxoni7jnciidyijdna/PHID-FILE-7p44cov6huy43mukiye6/sys_net_rtsock.c
