### ISSUE TITLE
poudriere doesn't check ports names for periods

### ISSUE THREAD

**Issue by JamesKoenig** [freebsd/poudriere#289]
While poudriere checks the jailname string you pass it (with poudriere jail -c) for periods, it doesn't check port names (and likely set names), when running poudriere ports -c, for periods. 

This is a bug because build jails are made with the following pattern: (jailname)-(portname)[-(setname)].  However, jails (man 8 jail) don't allow for periods in their names, though poudriere tries to make one if the <portname> contains periods.

**Comment by bdrewery** [comment]
Related to #247
