### ISSUE TITLE
testport with origin devel produce errors instead of bad origin message

### ISSUE THREAD

**Issue by andrejzverev** [freebsd/poudriere#299]
Example:
```
poudriere testport -j 10amd64 -p phoenix -o devel
```

**Comment by andrejzverev** [comment]
i looked into code and must admit there is no easy fix.
Something like this can be done, but i don't like it and sure you are also.

if exists directory PORTSDIR/ORIGIN and exists directory POTRSDIR/ORIGIN/../Mk then bad origin.

/usr/ports/devel/../Mk - bad origin since Mk exist
/usr/ports/devel/port../Mk - good origin since no Mk in devel/

**Comment by andrejzverev** [comment]
@bdrewery http://az.semmy.ru/testport.sh.txt

**Comment by bdrewery** [comment]
Done in d72e70fe977fca91791e647d954b2c0fa779dbf9
