### ISSUE TITLE
Difficulties Building SendMail with correct options under Poudriere 3.1.1

### ISSUE THREAD

**Issue by mrludo** [freebsd/poudriere#304]
I have been trying to determine the "correct" way to convince the FreeBSD SendMail port to build with the options I require via Poudriere.

I am  using a manually maintained "frozen" copy of the ports tree dated 6th Feb 2015 .
The sendmail port version in this tree is 8.15.1

My poudriere is hosted on a 64bit FreeBSD 10.1-STABLE host.

I am building the port primarily for 64bit FreeBSD 9.3 using a tree named frozen150206 and a jail named fm64-9 ..

I tried every variation I could think of using the poudriere option command to set the required options and I could see the results of my option setting in the appropriate options files produced were exactly what I wanted. e.g.

poudriere option -c mail/sendmail
poudriere option -c -j fm64-9 mail/sendmail
poudriere option -c -p frozen150206 mail/sendmail
poudriere option -c -j fm64-9 -p frozen150206 mail/sendmail

When sendmail was built it was built without the option I was trying to add (specifically LDAP).

No matter what I tried it would build sendmail+tls+sasl2-8.15.1.txz  

In the end I was able to make it build with the options I wanted by adding the following to the make.conf file for the jail (fm64-9-make.conf) :

.if ${.CURDIR:M*/mail/sendmail}
OPTIONS_DEFAULT?=       SHMEM SEM LA NIS IPV6 TLS SASL SASLAUTHD LDAP PICKY_HELO_CHECK MILTER MILTER_SHARED MILTER_POOL
.endif

This resulted in sendmail+tls+sasl2+ldap-8.15.1.txz  .

sendmail in ports used to have several slave ports with various combined options set but this has changed to there now being only mail/sendmail .  I considered using portshaker to recreate the appropriate slave port but this seems like overkill.

Can anyone advise the neatest most correct way of dealing with variations to sendmail options under poudriere ?

Thanks in advance,

--Dave

**Comment by brd** [comment]
Can you post a link to the build log?

**Comment by mrludo** [comment]
Are you after the successful one ?  This would be without any options set via poudriere and just with the addition to fm64-9-make.conf ?

If necessary I can do a rebuild of it without the addition to make.conf as well .

**Comment by mrludo** [comment]
Log of build without options set http://pastebin.com/Fj3JHKR9
Log of build with addition to fm64-9-make.conf http://pastebin.com/7ez1AQYG

**Comment by mrludo** [comment]
I think I may have worked out why I am having trouble with this.
The ports tree I am using is manually maintained.
Rereading the Note in section 9.5.6. of the FreeBSD proters handbook...

"The dash in the METHOD column means that Poudriere will not update or change this ports tree, ever. It is completely up to the user to maintain this tree, including all local modifications that may be used for testing new ports and submitting patches."

I think this means that when I use the command:  poudriere options -p frozen150206 -c mail/sendmail
the options that are changed are not saved into /usr/local/etc/poudriere.d/frozen150206-options/mail-sendmail/options as I thought they would be.

i worked this out as a result of banging my head against trying to add LDAP and proxying support into apache22 .
I set the options I wanted in my poudriere default ports tree and manually copied /usr/local/etc/poudriere.d/options/www_apache22/options to /usr/local/etc/poudriere.d/frozen150206-options/www_apache22/options .

My build then gave me the LDAP support that I was after.

**Comment by bdrewery** [comment]
No it just means you must manually update the tree with 'svn up' or whatever. The options subcommand will still work.

**Comment by mrludo** [comment]
I had mis-understood where the options were recorded. When you do something like:

poudriere options -p frozen150206 mail/sendmail

the adjusted options are not saved into poudriere.d/frozen150206-options/mail_sendmail as I thought they would be.

When I subsequently used the following build command:

poudriere bulk -j fm64-9 -p frozen150206 -f myportslist
[00:00:01] ====>> Creating the reference jail... done
[00:00:51] ====>> Mounting system devices for fm64-9-frozen150206
[00:00:51] ====>> Mounting ports/packages/distfiles
[00:00:51] ====>> Stashing existing package repository
[00:00:52] ====>> Mounting packages from: /u1/jails/poudriere/data/packages/fm64-9-frozen150206
[00:00:52] ====>> Mounting /var/db/ports from: /usr/local/etc/poudriere.d/frozen150206-options
[00:00:52] ====>> Appending to make.conf: /usr/local/etc/poudriere.d/fm64-9-make.conf

This indicates that /var/db/ports is being mounted from /usr/local/etc/poudriere.d/frozen150206-options .

Because my changed options were not saved into /usr/local/etc/poudriere.d/frozen150206-options, the build I do does not see the options I want  unless I manually copy the updated options file into where it needs to be noticed by the bulk build.

**Comment by kostikbel** [comment]
Options do not work for me:

tom% ls /usr/local/etc/poudriere.d                                            ~
RCS                             ports
hooks                           tom_poudriere-head-make.conf
jails                           tom_poudriere-head-options

tom% sudo poudriere options -j tom_poudriere -p head -c -n devel/bison

tom% ls /usr/local/etc/poudriere.d                                            ~
RCS                             tom_poudriere-head-make.conf
hooks                           tom_poudriere-head-options
jails                           tom_poudriere-options
ports

**Comment by bdrewery** [comment]
Unclear what the problem is here beyond a question. Some of the options behavior is likely #583.
