### ISSUE TITLE
Poudriere fails with orphaned docs files when DOCS, PORTDOCS and HTMLDOCS are unset

### ISSUE THREAD

**Issue by yurivict** [freebsd/poudriere#306]
Port textproc/ibus fails:
````
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/gtk-doc/html/ibus/IBusAttrList.html
Error: Orphaned: share/gtk-doc/html/ibus/IBusAttribute.html
Error: Orphaned: share/gtk-doc/html/ibus/IBusBus.html
...
````

Makefile in textproc/ibus declared DOCS as the port option. pkg-plist declares all docs with %%PORTDOCS%%%%DOCSDIR%% prefix. Port itself naturally installs them into the stage dir. Poudriere probably should pass these, not label them as orphans, because DOCS options are unset, and they are legitimately not installed into /usr/local

**Comment by bdrewery** [comment]
All of that logic is in ports Mk.

It's a bug in the port.

<pre>
~/svn/ports/textproc/ibus # make -V DOCSDIR
/usr/local/share/doc/ibus
~/svn/ports/textproc/ibus # grep gtk-doc pkg-plist
[nothing]
~/svn/ports/textproc/ibus # grep IBusAttrList.html pkg-plist
%%PORTDOCS%%%%DOCSDIR%%/IBusAttrList.html

Error: Orphaned: share/gtk-doc/html/ibus/IBusAttrList.html
</pre>

Note that _DOCSDIR_ is **/usr/local/share/doc/ibus** but the orphaned file is in **/usr/local/share/gtk-doc/html/ibus**

**Comment by yurivict** [comment]
Ok, thanks, I will notify the maintainer.
