### ISSUE TITLE
bulk build with specific ports list fail with `Missing dependency 'gettext-runtime-0.19.4'`

### ISSUE THREAD

**Issue by AMDmi3** [freebsd/poudriere#308]
- If that's relevant, previous build was a huge build of all ports which terminated abnormally (by some build eating all mem)
- Next, I try smaller build (all ports which have USE_LDCONFIG). Many ports fail with the following error:

```
[10-amd64-default-job-02] Installing gmake-4.1_1...
pkg-static: Missing dependency 'gettext-runtime-0.19.4'

Failed to install the following 1 package(s): /packages/All/gmake-4.1_1.txz
*** Error code 70
```

Examples of such behavior are:
http://poudriere.amdmi3.ru/build.html?mastername=10-amd64-default&build=2015-05-09_16h39m06s
http://poudriere.amdmi3.ru/build.html?mastername=10-amd64-default&build=2015-05-09_17h17m20s
http://poudriere.amdmi3.ru/build.html?mastername=10-amd64-default&build=2015-05-09_18h12m57s
- Notably, build with the different set of ports (only devel/libcheck, textproc/libxml2 and print/freetype2 which failed early in these builds) build fine:

http://poudriere.amdmi3.ru/build.html?mastername=10-amd64-default&build=2015-05-09_17h02m04s
- Same If include gettext-runtime to the list:

http://poudriere.amdmi3.ru/build.html?mastername=10-amd64-default&build=2015-05-09_17h33m38s

My guess is that it's somehow broken after the first huge build and it'll be fixed after removing packages and cache, but inconsistency of these failures suggests that there may be error in poudriere. http://poudriere.amdmi3.ru/build.html?mastername=10-amd64-default&build=2015-05-09_16h39m06s indicates that gettext-runtime is built after its consumers, however old package is not used.

That's poudriere-3.1.4 on 11-current r280307, all build are run as:
`poudriere bulk -j 10-amd64 -f BULK_LIST -N -w -t -C -k`

**Comment by bdrewery** [comment]
Hard to say, but I think this may have been a ports bug. I haven't seen it in a long time.
