### ISSUE TITLE
Weirdness with upgrade on non-changed options.

### ISSUE THREAD

**Issue by kostikbel** [freebsd/poudriere#311]
I have a machine which was installed using the old portinstall way.  I have built the repo with the same list of packages and (eventually) the same options as the machine.  Initially, some options were set wrong, see #304.  E.g., bison was first built with EXAMPLES turned on, then I corrected options and poudriere correctly rebuilt devel/bison without options.

When I am doing pkg upgrade, I see
tom% tar tzf /usr/home/poudriere/data/packages/tom_poudriere-head/All/bison-2.7.1,1.txz | grep exam

tom% sudo pkg upgrade -n                                                      ~
Updating tom_repo repository catalogue...
tom_repo repository is up-to-date.
All repositories are up-to-date.
Checking for upgrades (361 candidates): 100%
Processing candidates (361 candidates): 100%
Checking integrity... done (0 conflicting)
The following 48 package(s) will be affected (of 0 checked):

Installed packages to be REINSTALLED:
        bison-2.7.1,1 (option added: EXAMPLES)

**Comment by bdrewery** [comment]
It's hard to say at this point, but I would have wanted to try `pkg update -f` as well to ensure it was using the latest copy of the repository and not an older cached one from when the package still had EXAMPLES in it.

**Comment by kostikbel** [comment]
The state has long time gone.

BTW, from your response, does it imply that even for local repository, accessed with the file:/// url schema, pkg caches the repo somewhere ?  In other words, does the machine carry two copies of the packages ?

**Comment by bdrewery** [comment]
Yes for file:// it will still keep a cache of the repository in /var/db/pkg/, it just optimizes fetching by not duplicating the packages to /var/cache/pkg/ on fetch/upgrade.
