### ISSUE TITLE
Jail created with -m src=/path might not have a consistent /usr/src after update.

### ISSUE THREAD

**Issue by kpaasial** [freebsd/poudriere#318]
It looks like after an update to a jail that was created with -m src=/path the jail's /usr/src could be in an inconsistent state if the updated sources had files deleted compared to what was in the jail /usr/src before the update. I suggest that install_from_src in jail.sh deletes the jail /usr/src completely before copying a new set of sources to avoid this problem.

**Comment by bdrewery** [comment]
8808b527c462834 should resolve this.

**Comment by kpaasial** [comment]
That is correct and the fix seems to be already in poudriere-devel. Issue solved for me.
