### ISSUE TITLE
poudriere bulk -c man outdated

### ISSUE THREAD

**Issue by f-andrey** [freebsd/poudriere#320]
man page contain outdated information

poudriere bulk
```
 -c          -- Clean all the previously built binary packages
```
man poudriere
```man
-c           Clean all previously built packages and logs.
```

Is there a way to cleanly remove log's or only rm -Rf logs dir?

**Comment by bdrewery** [comment]
The bug is more that bulk doesn't remove the logs.

Regards,
Bryan Drewery

**Comment by ant1** [comment]
This breaks bulk -ca
Also,  i can't compare current run with previous run anymore....
