### ISSUE TITLE
Poudriere stuck in "balancing_pool" status

### ISSUE THREAD

**Issue by SylvainGarrigues** [freebsd/poudriere#324]
My poudriere.conf is the default one but with NO_NFS=yes

I'm using FreeBSD 11-CURRENT and the poudriere-devel port.

When I use the bulk command, the first package to be build is built successfully but then the script is stuck in balancing_pool status.

Last line of the build reads:
=======================<phase: package        >============================
===>  Building package for pkg-1.5.4
===========================================================================
====>> Cleaning up wrkdir
===>  Cleaning for pkg-1.5.4
[1;33m====>>[0;0m [1;33mWarning: Leftover processes:
[0;0m

**Comment by ant1** [comment]
Does this problem occur with native build or are you cross compiling?

**Comment by bdrewery** [comment]
The problem is `ps` is returning no results and a non-zero exit code. I'm seeing this in QEMU builds. Are you using QEMU? What kernel revision and what jail revision and archs?

**Comment by SylvainGarrigues** [comment]
Hi,
I'm using a FreeBSD 11.0-CURRENT r284451 kernel on an x64 machine to cross-compile ARMv6 ports on a poudriere jail which also use FreeBSD 11.0-CURRENT. The jail was built with the native-xtools (-x).
QEMU is used through binmisctools kernel declaration to run arm executables.
_____________________________

**Comment by seanbruno** [comment]
I've narrowed this wierd failure to a combination of two things:

r283304 --> changes ps behavior

Unknown change that causes qemu-user-static to have no output for /bin/ps

**Comment by bdrewery** [comment]
FYI I also checked a native jail on the same revision and had ps working. Seems limited to qemu.

Regards,
Bryan Drewery

**Comment by SylvainGarrigues** [comment]
Thank you guys for your time trying to reproduce the bug. So if I understand correctly you suggest that:

- either I checkout a revision of the FreeBSD tree prior to r283304
- or I wait for qemu-user-static to work with the new post-r283304 behavior

Is that correct?

**Comment by seanbruno** [comment]
For now Stacey/Juergen have fixed the ps issues and you should be able to update your qemu-user-static port and be fine.

**Comment by bdrewery** [comment]
Fixed at https://github.com/seanbruno/qemu-bsd-user/commit/f51f4da6f75a19afd5685004d9e2ad382748be43
