### ISSUE TITLE
Permissions problem in package tree

### ISSUE THREAD

**Issue by mrludo** [freebsd/poudriere#345]
We are currenlty using poudriere-3.1.1 on FreeBSD 10.2-BETA2.

My boss had to add a package into our standard build of a frozen ports tree.

He followed my notes on how to do this but when he tried to install the resultant newly built package he hit a problem with...

pkg: http://fmaster64-10.some.where/fm64-9-frozen150206/packagesite.txz: Forbidden

This was tracked down to /u1/jails/poudriere/data/packages/fm64-9-frozen150206/.real_1441442467 having permissions of drwx------ .

My notes had ommitted that I usually actually become root when using poudriere. He had simply assumed root priviledges without actually becoming root.

He has asked me if poudriere should be be resetting the umask when creating these directories rather than having to become root when working with it ?

**Comment by njthomas** [comment]
I had the same issue. Turns out I was building poudriere via sudo which was overriding root's umask. The fix was to set the following in sudoers:
```
Defaults umask=0022
Defaults umask_override
```
