### ISSUE TITLE
use testport to test a port with an overlay

### ISSUE THREAD

**Issue by uzsolt** [freebsd/poudriere#352]
I think it would be useful if `poudriere testport` can use to test a (under working) port.
I think one solution is similar to: `poudriere testport` will mount the selected port tree, after mount a specified directory (outside from port tree) to the tested port.
For example: I've default port in /poudriere/ports/default. It appears new version from a program (name `foo`). I'll copy `/poudriere/ports/default/foo-category/foo` to `${TESTPORTDIR}/foo-category/foo` and edit `Makefile`, etc.
Run `poudriere testport -j myarch -o foo-category/foo`. The `/poudriere/ports/default` will (nullfs) mount to `${JAIL}/usr/ports` and (this is the essential of issue) mounts (nullfs too) `${TESTPORTDIR}/foo-category/foo` to `${JAIL}/usr/ports`.

**Comment by bdrewery** [comment]
This sounds like port shaker to me. We supposedly have support for that.

**Comment by uzsolt** [comment]
I think it's only similar not exactly same. On `portshaker`'s way should have two port trees (I'm using `poudriere` on a small VPS so every 100M count). 
My idea would be simplier and doesn't waste disk capacity.

**Comment by bdrewery** [comment]
The idea begs using unionfs though. So many ports are slaves to other ports or require mounting a Mk/Uses directory as well. Unionfs is broken :(

**Comment by uzsolt** [comment]
No, unionfs isn't good solution to this - I tried it some time ago ;)
The reason: if your port doesn't need a patch anymore in `files` directory you'll delete it from `${TESTPORTDIR}/foo-category/foo/files/`. But the main port tree contains the deleted file so in `unionfs` will appear.

Do you think the `nullfs-mount` will not work?

**Comment by bdrewery** [comment]
I think nullfs would work for basic ports.

**Comment by uzsolt** [comment]
Do you think it's useful idea? If yes I would try to implement.

**Comment by arrowd** [comment]
I've tried to this on the host side and failed:

1. The ports tree is in `/usr/ports`
2. The port i'm testing in `~/ports/sysutils/myport`.
3. I've done `poudriere ports -c -F -f none -M /usr/ports`.
4. Then `mount_nullfs -o union ~/ports/sysutils/ /usr/ports/sysutils`.
5. `ls /usr/ports/sysutils/bsdisks` works.
6. Running `poudriere testport sysutils/myport gives`

> [00:00:01] ====>> Starting jail default-default
> [00:00:02] ====>> Warning: (sysutils/myport): make: chdir /usr/ports/sysutils/myport: No such file or directory

If i use `cp -r` instead of `mount_nullfs`, everything works fine.

**Comment by uzsolt** [comment]
I think should replace "mount_nullfs" 4. and 6. So first should mount everything in poudriere and poudriere should mount_nullfs the ports.

Check a simple example:
1. mount_nullfs /A /B
2. mount_nullfs /B /C/B
You will see the original content of /B in /C/B (not the content of /A).

**Comment by mat813** [comment]
This looks like you need to use portshaker, or you could simply put a full checkout of the ports tree in ~ports, it'd simplify things. A lot.

**Comment by uzsolt** [comment]
I found an ugly workaround:

0. You've `/usr/ports` and an empty `/usr/local/poudriere/ports/devel` (`poudriere ports -c -m null -p devel && mkdir /usr/local/poudriere/ports/devel`
1. Create a temporary directory (`/usr/local/poudriere/ports/wrk`).
2. `mount_unionfs /usr/ports /usr/local/poudriere/ports/wrk`
3. `mount_unionfs ~/ports /usr/local/poudriere/ports/wrk`
4. `mount_nullfs /usr/local/poudriere/ports/wrk /usr/local/poudriere/ports/devel`
5. `poudriere testport -p devel ...`

Maybe it's a bit annoying that the `ls` command shows everything twice (in `.../devel`).

**Comment by bdrewery** [comment]
Fixed by #790
