### ISSUE TITLE
"poudriere ports -d" does not delete the actual files

### ISSUE THREAD

**Issue by victor-sudakov** [freebsd/poudriere#353]
The "poudriere ports -d" does not delete the actual ports tree from /var/poudriere/ports/default/ as if "-k" was also given (but it was not). Am I supposed to remove the tree manually now?

poudriere-devel-3.1.99.20150915 on FreeBSD 9.3-RELEASE-p24, NO_ZFS=yes.

**Comment by bdrewery** [comment]
That's odd because a related bug, #250, is that `ports -d` wipes system ports trees when it didn't create them. One of these bugs has to be wrong. I'll look into it more.

**Comment by victor-sudakov** [comment]
Can it be related to the fact that I am not using zfs?
