### ISSUE TITLE
GitHub wiki version of poudriere.8 contains broken links to its section headings

### ISSUE THREAD

**Issue by mjb2010** [freebsd/poudriere#359]
In the HTML-ized man page at https://github.com/freebsd/poudriere/wiki/poudriere.8 there are links in the prose pointing to various sections like FILES, ENVIRONMENT, or CUSTOMISATION...but none of them work. These links need to be pointing to the anchor IDs, or the anchor hrefs (which isn't really kosher, but works).

**Comment by bdrewery** [comment]
This is just generated with `mandoc -Txhtml`. I don't expect this to be fixed.
