### ISSUE TITLE
Advice to use WITH_PKG=yes may not be ideal in the pkg_repos wiki page

### ISSUE THREAD

**Issue by mjb2010** [freebsd/poudriere#360]
https://github.com/freebsd/poudriere/wiki/pkg_repos demonstrates putting WITH_PKG=yes into make.conf files. Should it not be WITH_PKGNG=yes?

And is it safe to assume this advice necessary only for the make.conf files of target system versions prior to FreeBSD 10.0 or whenever it was that PKGNG became standard?

**Comment by bdrewery** [comment]
Thanks, fixed.
