### ISSUE TITLE
poudriere -c -x .. command to build native cross tools appears to be broken

### ISSUE THREAD

**Issue by mmitchel** [freebsd/poudriere#361]
output from the following command appears that -x in conjunction with jail creation fails. the command used is:
# poudriere jails -j STABLE-i386 -a i386 -v stable/10 -m svn -c -x > jmake.txt &

the error log output includes this before the failure, and the same failure is seen when using -v head on 11.0-CURRENT source baseline also.

===> sbin/md5 (obj,depend,all,install)
--- obj ---
--- _proginstall ---
sh /usr/src/tools/install.sh -s -o root -g wheel -m 555   md5 /usr/obj/i386.i386/nxb-bin/sbin/md5
--- _installlinks ---
/sbin/rmd160 -> /sbin/md5
/sbin/sha1 -> /sbin/md5
/sbin/sha256 -> /sbin/md5
/sbin/sha512 -> /sbin/md5
===> sbin/sysctl (obj,depend,all,install)
--- obj ---
--- sysctl.o ---
cc -O2 -pipe  -std=gnu99  -Qunused-arguments -c /usr/src/sbin/sysctl/sysctl.c -o sysctl.o
/usr/src/sbin/sysctl/sysctl.c:89:3: error: use of undeclared identifier 'CTLTYPE_S8'
        [CTLTYPE_S8] = 1,
         ^
/usr/src/sbin/sysctl/sysctl.c:90:3: error: use of undeclared identifier 'CTLTYPE_S16'
        [CTLTYPE_S16] = 1,
         ^
/usr/src/sbin/sysctl/sysctl.c:91:3: error: use of undeclared identifier 'CTLTYPE_S32'
        [CTLTYPE_S32] = 1,

```
     ^
```

**Comment by bdrewery** [comment]
The problem is actually 'make native-xtools' is broken by design in the base system. It's not a Poudriere problem persay. I've been working on a solution though.
