### ISSUE TITLE
symlink "All" directory into the ".real_*" directory?

### ISSUE THREAD

**Issue by SBBH** [freebsd/poudriere#363]
Because of the directory structure every time packages are updated all files have to be re-uploaded even if not changed which can be very inconvenient especially if you're unable to build packages on the same server as the package repository.

Is there any way that the "All" directory that holds the packages could be linked into the .real_* directory so that programs like rsync will only have to upload the packages that have changed and not everything?

**Comment by bdrewery** [comment]
The way to handle this is to upload the packages/.lastest/ directory (with / at end to resolve the symlink). Then you're only uploading new packages since it will rsync INSIDE the real directory. 

If you're using the hooks then `${PACKAGES}/` will already do this for you.

**Comment by SBBH** [comment]
Brilliant, I should have thought of that. Thank you!
