### ISSUE TITLE
command line build options for specific port

### ISSUE THREAD

**Issue by SBBH** [freebsd/poudriere#372]
For example when installing from the ports directory I can do something like:

```test:/usr/ports/databases/mysql56-server # make WITH_CHARSET=utf8 WITH_COLLATION=utf8_general_ci install```

From what I understand this is not possible in poudriere without it applying to all ports being built. Can this feature be added or am I missing something?

**Comment by AMDmi3** [comment]
I think you can use usual make.conf hacks, e.g.

```
.if ${.CURDIR:T} == "mysql56-server"
WITH_COLLATION=utf8_general_ci
.endif
```

**Comment by SBBH** [comment]
Oh, good to know. Thank you!

**Comment by bdrewery** [comment]
Also `testport -c`
