### ISSUE TITLE
Change forced testport TRYBROKEN=yes to -T (matching bulk -T)

### ISSUE THREAD

**Issue by koobs** [freebsd/poudriere#373]
I was attempting to test a conditional BROKEN in www/py-autobahn and couldnt determine why it kept not failing BROKEN.

Investigation revealed: testport.sh contains
```
testport.sh:export TRYBROKEN=yes
```
I propose the following:

* Don't try broken by default, by removing the unconditional export of `TRYBROKEN=yes`
* Add a `-T` argument to the `testport` command to match the existing `bulk -T`

**Comment by bdrewery** [comment]
Well the idea is that you asked to test it, why should it stop in the BROKEN? I realize it is confusing though. When using TRYBROKEN and BROKEN is set the ports framework does show a message already.

<pre>
.if defined(TRYBROKEN) && defined(BROKEN)
buildanyway-message:
    @${ECHO_MSG} "Trying build of ${PKGNAME} even though it is marked BROKEN."
.endif
</pre>

**Comment by koobs** [comment]
@bdrewery Because BROKEN is a ports construct that ought to be tested in the same manner as any other framework construct, and is not special. It also brings it into line with bulk. This is about expected vs actual results. This issue is only about providing a consistent default, removal of hardcoding, not about removing the feature

**Comment by AMDmi3** [comment]
bulk and testport are fundamentally different actions, and there's no reason to "bring them into line". Testport is run on individual ports and should run regardless of many port constructs such as BROKEN, NO_PACKAGE and MANUAL_PACKAGE_BUILD (and actually IGNORE which it does honor for now), because port building test was explicitly requested and it should be performed. Building BROKEN ports is crucial to determine if they are no longer broken, and the message is more than enough to test BROKEN itself.

So, while here, maybe we can add NO_IGNORE to testport? Same way as BROKEN, it'd be really useful to check and fix e.g. ONLY_FOR_ARCHS.

**Comment by koobs** [comment]
The premise of this issue is **not** to remove the ability to bypass BROKEN, but to provide the ability to _test_ said framework functions. _bringing into line_ was **not** about making them the same, or asserting that bulk and testport weren't used for different things. It is about bring the -T functionality to testport, thus _alignment_.

**Comment by mat813** [comment]
To test the framework, you can run bulk foo/bar and it'll tell you if it is broken.

**Comment by bdrewery** [comment]
`testport` is more useful if it works by default for everything.  Given the framework already shows a message I'm not inclined to change this.

**Comment by koobs** [comment]
@bdrewery I indeed agree that "work by default" is the expectation, which is why the issue was reported. 

The current default setting of TRYBROKEN (no) for testport is actually _less_ work by by default then yes.

In fact, there is an argument to be made that switching bulk (TRYBROKEN) default to no, so that it can be explicitly set/modified for big-package-run purposes if desired/needed/necessary, and testport defaulted to yes, so that _tests of ports_, which is the entire purpose of testport, can indeed _work by default_, which is almost exclusively always the case.

To put a finer point on it, when does a user ever _not_ want TRYBROKEN=yes (without having to know it or change it) as the default, when they test a port?

**Comment by bdrewery** [comment]
The argument is understood now. The default will change and require `-T` to ignore the `BROKEN`.
