### ISSUE TITLE
after 54f3f32 "chflags: ... No such file or directory"

### ISSUE THREAD

**Issue by f-andrey** [freebsd/poudriere#378]
Hello, after commit 54f3f32 poudriere not work (test 9.3, 10.2 and current jail)
````
[00:00:07] ====>> Recording filesystem state for prepkg... done
[00:00:10] ====>> Building 1 packages using 1 builders
[00:00:10] ====>> Starting/Cloning builders
chflags: /poudriere/data/.m/93amd64-default-opensmtpd/01: No such file or directory
[00:00:11] ====>> Cleaning up
[00:00:11] ====>> Umounting file systems
````
If revert this change, work fine

**Comment by bdrewery** [comment]
That seems wrong, the old code was also running chflags and not ignoring errors. Did you revert a different commit too?

**Comment by bdrewery** [comment]
I recreated the issue with ZFS here and will fix it. It was working fine with my `USE_TMPFS=all` testing.

**Comment by bdrewery** [comment]
Oh I see the problem now, I need `/*` on the `rm`.

**Comment by bdrewery** [comment]
Thanks!
