### ISSUE TITLE
can't fetch x11-fonts/webfonts

### ISSUE THREAD

**Issue by rhavenn** [freebsd/poudriere#384]
For about the last few weeks I can't fetch x11-fonts/webfonts when using poudriere from multiple build locations. I use poudriere at work and at home. In both locations I can manually fetch the files no problem.

Error log attached. Manually running fetch via:
> fetch http://downloads.sourceforge.net/project/corefonts/the%20fonts/final/arial32.exe

works fine for all files in question. I was pretty sure poudriere used fetch under-the-hood, yes?

[webfonts_build.txt](https://github.com/freebsd/poudriere/files/221544/webfonts_build.txt)

[Uploading webfonts_build.txt…]()

**Comment by bdrewery** [comment]
If this is still an issue please report it to the port maintainer.  The fetching for Poudriere uses the same fetching as ports, just done from a jail.  If there were a problem with poudriere or the jail it would likely show everywhere and not just in port.
