### ISSUE TITLE
BUILD_DEPENDS are not available during patch stage

### ISSUE THREAD

**Issue by K6BSD** [freebsd/poudriere#389]
Dependencies listed in BUILD_DEPENDS are not available during the patch stage.

The porters handbook states:
> “build” here means everything from extraction to compilation. The dependency is checked from within the extract target.

bsd.port.mk states:
> tuples of other ports this package depends to build (between the "extract" and "build" stages, inclusive).

And a quick non-scientific test shows that the port system does behave this way, but poudriere will fail in the patch stage for this.

**Comment by mat813** [comment]
Well, BUILD_DEPENDS are available starting at the configure stage onwards, you want to use PATCH_DEPENDS.

**Comment by bdrewery** [comment]
Looking at the sequence code in bsd.port.mk, `build-depends` isn't called until you run `make configure`:

<pre>
_CONFIGURE_SEQ= 150:build-depends 151:lib-depends 200:configure-message \
                300:pre-configure 450:pre-configure-script 460:run-autotools \
                490:run-autotools-fixup 500:do-configure 700:post-configure \
                850:post-configure-script \
...
</pre>

This is where `BUILD_DEPENDS` gets hooked in and how poudriere does it as well.
