### ISSUE TITLE
Dtrace builds

### ISSUE THREAD

**Issue by dinapappor** [freebsd/poudriere#391]
I am having a difficult time building packages with dtrace which is needed for observability.

I have tried copying /boot/ into the reference jail, both manually and adding it to common.sh operations. 

It's still a no go, how does one go about compiling packages with dtrace supports?

**Comment by dinapappor** [comment]
```
checking for 1-stage DTrace precompilation... dtrace: failed to compile script emulator/beam/erlang_dtrace.d: "/usr/lib/dtrace/ip.d", line 225: operator -> cannot be applied to a forward declaration: no struct ip definition is available
configure: error: Could not precompile erlang_dtrace.d: dtrace -h failed
configure: error: /bin/sh '/wrkdirs/usr/ports/lang/erlang/work/otp_src_18.3/erts/configure' failed for erts
===>  Script "configure" failed unexpectedly.
Please report the problem to olgeni@FreeBSD.org [maintainer] and attach the
"/wrkdirs/usr/ports/lang/erlang/work/otp_src_18.3/config.log" including the
output of the failure of your make command. Also, it might be a good idea to
provide an overview of all packages installed on your system (e.g. a
/usr/local/sbin/pkg-static info -g -Ea).
*** Error code 1

Stop.
make: stopped in /usr/ports/lang/erlang
====>> Cleaning up wrkdir
===>  Cleaning for erlang-18.3.3_1,3
build of lang/erlang ended at Thu May 19 17:01:00 UTC 2016
```

This is what happends during configure phase.

**Comment by dinapappor** [comment]
Actually, copying the /boot/ directory to the poudrier worker jails actually worked. \o/ Is it possible to have an "ENABLE_DTRACE=YES" option that would actually do this?

**Comment by bdrewery** [comment]
What from /boot is needed? We can just make the jail create/update ensure the files are brought in.

**Comment by dinapappor** [comment]
@bdrewery I think it's these files:

```
/boot/kernel/dtrace.ko              /boot/kernel/dtrace.ko.symbols      /boot/kernel/dtrace_test.ko         /boot/kernel/dtrace_test.ko.symbols /boot/kernel/dtraceall.ko           /boot/kernel/dtraceall.ko.symbols
```

I will make some experiments and try to narrow it down to exactly what files are needed and get back to you.

**Comment by dinapappor** [comment]
Hi, I looked this up and this is what I did to be able to build dtrace enabled packages repeatedly:

In common.sh after line 1776 I added: 

```
mkdir -p "${tomnt}/boot/kernel"
cp -R /boot/kernel/kernel "${tomnt}/boot/kernel/"
cp /boot/kernel/dtrace.ko "${tomnt}/boot/kernel/"
```
This is enough for me to build dtrace enabled packages. It however requires that dtraceall is loaded into the kernel.

**Comment by bdrewery** [comment]
Thanks. We'll have to buildkernel from the source as well but that is quick and we can limit it to just kernel and dtrace it looks like.

**Comment by infracaninophile** [comment]
Ran into this myself today.  DTrace related builds (ie. postgresql95-server) work fine on my home system, where the jail is from a locally compiled tree:
```
stable11amd64 11.0-BETA1       amd64 src=/usr/src 2016-08-24 13:04:46 /usr/local/poudriere/jails/stable11amd64
```
At work, it failed with jails installed by FreeBSD update:
```
FreeBSD:10:amd64 10.1-RELEASE-p37 amd64 ftp    2016-08-24 12:04:47 /usr/local/poudriere/jails/FreeBSD:10:amd64
10_3             10.3-RELEASE-p7  amd64 ftp    2016-08-24 15:28:59 /usr/local/poudriere/jails/10_3
```
... unless I forced the jail to have exactly the same version as the host system right down to the patchlevel.  

Question: is there any hope of DTrace builds working in a jail that is a different version than the host system?

**Comment by bdrewery** [comment]
+ @markjdb

**Comment by bdrewery** [comment]
See #410.  This should be resolved in ports already or simply by adding `-xnolibs` to `dtrace` calls for older releases via ports PR.
