### ISSUE TITLE
Poudriere fails to mount /nxb-bin in the bulk command

### ISSUE THREAD

**Issue by zxombie** [freebsd/poudriere#392]
In df25388 poudriere started mounting /nxb-bin, however it seems to only exist when cross building so will fail when trying to mount it in do_jail_mounts in common.sh.

**Comment by bdrewery** [comment]
It only mounts it if nxb-bin/ exists in the jail, which should only be the case if it was setup with `jail -x`.

**Comment by zxombie** [comment]
I didn't use `jail -x`, however if I remove `/nxb-bin` from `nullpaths` in https://github.com/freebsd/poudriere/blob/master/src/share/poudriere/common.sh#L1168 it will work. I suspect it should check fir the existance before trying to perform the null mount.

**Comment by bdrewery** [comment]
Do you have a `/nxb-bin` globally? I think the logic may incorrectly be looking there.

**Comment by zxombie** [comment]
Yes, that seems to exist.

**Comment by bdrewery** [comment]
Oops! So it's lacking the `${mnt}` in the directory check. Will fix.

**Comment by fullermd** [comment]
This seems to have a bad side effect...

[00:00:00] ====>> Creating the reference jail... done
[00:00:00] ====>> Mounting system devices for tar-default
mkdir: /nxb-bin: Read-only file system
[00:00:00] ====>> Cleaning up
[00:00:00] ====>> Umounting file systems

**Comment by bdrewery** [comment]
Yup, was fixed in 3.1.14 today.
