### ISSUE TITLE
[feature request] document SVN rev. in finished packages

### ISSUE THREAD

**Issue by ohauer** [freebsd/poudriere#398]
It would be nice if PD places a file with the SVN rev. and the branch, this would help users building partiality to be as close as possible with upstream

**Comment by AMDmi3** [comment]
Won't this break reproducible builds? Also isn't this useless with portsnap?

**Comment by ohauer** [comment]
I cannot see why this information could break anything ...
By comparing the documented SVN rev. and branch someone is able to checkout and build the identical portstree, the timestamp in distinfo is in my opinion useless for the case I will decribe below since it doesn't reflect changes in Mk, the ports Makefile or any dependency but the SVN rev. is unique it reflects the whole ports tree.

Back to the request, and why I think documenting the SVN rev. is useful.
I was helping a user who tries to install as much as possible from FreeBSD packages, we crawled all beefy[n] systems to find the SVN rev. that was used to build the FreeBSD packages in poudriere so we could sync to the same SVN  rev. before some ports where rebuild with different OPTIONS, having that information in a simple plain text file would save some crawling work.

**Comment by ohauer** [comment]
Perhaps the following makes it more clear, the SVN rev. should be placed in a single file (PD BUILD info)
.latest	-> .real_1466506323
.real_1465788196
.real_1465840768
.real_1465989074
.real_1466060575
.real_1466086322
.real_1466157796
.real_1466247052
.real_1466317361
.real_1466480936
.real_1466506323
All -> .latest/All
Latest -> .latest/Latest
**Latest.rev -> .latest/Latest.rev     <== new requested info**
digests.txz -> .latest/digests.txz
meta.txz -> .latest/meta.txz
packagesite.txz	-> .latest/packagesite.txz

**cat Latest.rev**
Master		101i386-quarterly
Build		417177
Status		stopped:done:
Jail		101i386	
Set
Ports_Tree	quarterly
SVN		svn://svn0.us-west.freebsd.org/ports/branches/2016Q2@417177

**Comment by bdrewery** [comment]
I am all for doing this as an optional feature.  It could be stored as a PKG_NOTE.

**Comment by ohauer** [comment]
:) naming the file PKG_NOTE is even better, perhaps also replace the SVN server name with svn.freebsd.org so not all users using the file as information ending on the same server and rendering gdns useless.
Most important, the file should be fetch able from pkg.freebsd.org/$(ABI|ALTABI)/

**Comment by bdrewery** [comment]
When I say PKG_NOTE I am talking about the ports feature that adds a note into the package which `pkg` can view.

**Comment by utrenkner** [comment]
@bdrewery This could also be interesting. But it was not the original intention: I am the user @ohauer wanted to help... My aim is to bring my local ports tree to the exact same revision that the packages are that I get from the official FreeBSD repos. It is not an information per package but per run of package-building.

**Comment by AMDmi3** [comment]
@utrenkner I think you can get this info from poudrieres which build official packages. For instance, 10.x amd64: http://beefy6.nyi.freebsd.org/jail.html?mastername=101amd64-default. Build name equals to ports revision, the last complete build is probably what's you looking for.

**Comment by bdrewery** [comment]
Here is an example of how it works in git `master` currently for 3.4...

```
# pkg info postfix
...
Annotations    :
        FreeBSD_version: 1202000
        build_timestamp: 2021-08-14T00:45:37+0000
        built_by       : poudriere-git-3.3.0-869-g56218a5e6
        cpe            : cpe:2.3:a:postfix:postfix:3.6.2:::::freebsd12:x64
        port_checkout_unclean: no
        port_git_hash  : ee4991c47f3c
        ports_top_checkout_unclean: no
        ports_top_git_hash: 40d27faa8903
        repo_type      : binary
        repository     : custom
```
