### ISSUE TITLE
Feature request: show reverse dependency tree, or "why is this port being built"?

### ISSUE THREAD

**Issue by voltagex** [freebsd/poudriere#421]
Currently to try to get an idea of why something is being built, I have to do `grep "depends on" /usr/local/poudriere/data/logs/bulk/freebsd-HEAD/latest/logs/* | less` and then probably Google, because pkg info -r only works on installed packages.

Would it be possible to show a dependency tree in the Poudriere HTML pages?

**Comment by AndiDog** [comment]
`<build jail>/.p/port_deps` gives this information while the build is still running, or in interactive mode. I'd also like this to be available, maybe just place a copy of that file in the log directory?

**Comment by khera** [comment]
It would be nice if there were an option, perhaps with dry run, to output a tree like diagram similar to what https://gist.github.com/bdrewery/3375001 does.

**Comment by bdrewery** [comment]
#386 adds some basic dependency information to the HTML interface, but not a tree.

There is also now a _/usr/local/poudriere/data/logs/bulk/freebsd-HEAD/latest/.poudriere.deps%_ file that can be passed to `dot` to generate a graph.  The file is linked from the HTML interface in f64c2d39f041cd36db53cbf6e61a6c7465e8995a which will be in 3.2.
