### ISSUE TITLE
[feature request] add a hook before repo signing to permit injecting non-poudriere packages

### ISSUE THREAD

**Issue by dch** [freebsd/poudriere#438]
Use case: a `package.txz` has been manually built with `pkg-create(8)` and I'd like to include it into an existing private poudriere-based package repo, so that it can be delivered using the existing pkg repo.

I can work on a patch if you point me in the right location or functionality in the source code to extend this.

**Comment by bdrewery** [comment]
Definitely. I had just missed this but it's literally a 1 line change. I'll get it into the next release.

**Comment by bdrewery** [comment]
Documented at https://github.com/freebsd/poudriere/wiki/hooks as well
