### ISSUE TITLE
zsh: ncurses detection

### ISSUE THREAD

**Issue by Yuubari** [freebsd/poudriere#450]
The `shells/zsh` port is designed so it detects whether `devel/ncurses` is installed in the build environment, and links against it if it is. When building using poudriere with `devel/ncurses` at the top of the ports listing the resulting `shells/zsh` package is still linked against base system ncurses.

Poudriere-built package:

```% ldd /usr/local/bin/zsh
/usr/local/bin/zsh:
        libncursesw.so.8 => /lib/libncursesw.so.8 (0x8008cf000)
        libm.so.5 => /lib/libm.so.5 (0x800b2b000)
        libc.so.7 => /lib/libc.so.7 (0x800d56000)
```

Binary built using `make build` in `/usr/ports/shells/zsh` with the binary `devel/ncurses` package installed:

```# ldd /var/ports/basejail/usr/ports/shells/zsh/work/zsh-5.3.1/Src/zsh
/var/ports/basejail/usr/ports/shells/zsh/work/zsh-5.3.1/Src/zsh:
        libtinfow.so.6 => /usr/local/lib/libtinfow.so.6 (0x8008cf000)
        libm.so.5 => /lib/libm.so.5 (0x800b08000)
        libc.so.7 => /lib/libc.so.7 (0x800d33000)
```

Is there a way to force poudriere to install ncurses from ports in the build environment prior to starting the builder jobs?

**Comment by brd** [comment]
Yes, this is something that should be an option for the port as an optional build dependency.  Please open a bug in the FreeBSD bugzilla.
