### ISSUE TITLE
Add sortable column for 'build time' in web interface

### ISSUE THREAD

**Issue by rootwyrm** [freebsd/poudriere#452]
Enhancement request for Web UI component; add a sortable column for 'Built ports' for time spent building using 'build time' from logs. This would be very useful for quickly identifying long-runners that may have problems but build successfully.

gist of how I'm doing it now:
https://gist.github.com/rootwyrm/44b85a4d2593a9cf16344dcd5ddc6af6
(then run output file through sort)

**Comment by bdrewery** [comment]
Yeah, we could store the build time into the json and push it through to the interface.
