### ISSUE TITLE
run_hook jail start: missing parameter or missing guard?

### ISSUE THREAD

**Issue by capjo** [freebsd/poudriere#461]
Hi,

the description of 'jail start' hook says: Called when the master jail starts.

What I have seen in my tests is that the hook is called for every jail that is started also the (job-??) jails.

Either we should prevent the hook from running inside the job jails or have an additional parameter that tells us if we are master or job-?? jail.

Or we add another environment variable with this information?

Add the moment it is not possible to use 'jexec' inside a specific jail. I would go for adding 'jls Name'. It would allow for more use cases.

The questions where should the name be added to?

Thanks.

**Comment by bdrewery** [comment]
What version? I only see the `jail start` hook running from `jail_start`, which is only ran once ever. Builders (job) use `builder start` hooks.

**Comment by capjo** [comment]
Sorry you are right.

It was the 'jail mount hook' that was called for the master and builder jails. Would an id make sense for the 'jail mount hook'? Like 0 for master and 1..n for the builder jails?

It would be also possible to extract the builder id using the mnt path that end with two digits in case of a builder jail.

I want to run sshd inside the master jail to do some manual testing some server software. Sshd is used to do the port forwarding in order to connect the client and sshfs can be used to map work directory to modify files. I modify the sshd_config and copy the authorized_keys after mounting the jails.

For now it seems to work :-).

Thanks for your quick reply.

# master
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/ref/etc/ssh/sshd_config]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/ref/root/.ssh/authorized_keys]
# builder
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/04/etc/ssh/sshd_config]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/04/root/.ssh/authorized_keys]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/01/etc/ssh/sshd_config]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/02/etc/ssh/sshd_config]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/01/root/.ssh/authorized_keys]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/02/root/.ssh/authorized_keys]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/03/etc/ssh/sshd_config]
[hook jail mount: /pdr/data/.m/103amd64-rmg-rmg/03/root/.ssh/authorized_keys]

**Comment by bdrewery** [comment]
The builder jails are copied from the master, so you should be able to only modify the master and have your files appear in the builders as well. There is a `MY_JOBID` variable that is set to the builder id, such as _01_.  It will be *blank* for the master though.  So you could check with:
```
if [ "$1" = "mount" -a -z "$MY_JOBID" ]; then
    # Do stuff only in the master
    mnt="$2"
    cp .... ${mnt}/etc/ssh/
fi
```

However, I've just stuck to the `jail start` and `jail stop` hook for doing this kind of thing. It is simpler since it only fires for the master jail.

I am going to close this since there's no bug, but we can keep discussing it all.
