### ISSUE TITLE
Poudriere now needs c99/gnu99 to compile

### ISSUE THREAD

**Issue by chmeeedalf** [freebsd/poudriere#468]

**Comment by chmeeedalf** [comment]
(Hit enter a little too quickly):
Building ports-mgmt/poudriere-devel on powerpc64 I see the following error.  Speaking with jilles@ it seems gcc4.2.1 base is getting tripped up on the 'restrict' keyword in here.  Building with std=gnu99 should fix this.

cc -DHAVE_CONFIG_H -I. -I./src    -DSHELL -DNO_HISTORY -include  ./external/sh_compat/compat.h -I./src  -I./external/sh -I./src/poudriere-sh  -I./src/poudriere-sh -O2 -pipe  -fno-strict-aliasing -MT external/sh/sh-expand.o -MD -MP -MF external/sh/.deps/sh-expand.Tpo -c -o external/sh/sh-expand.o `test -f 'external/sh/expand.c' || echo './'`external/sh/expand.c
external/sh/expand.c:273: error: expected ';', ',' or ')' before 'argbackq'
external/sh/expand.c:416: error: expected ';', ',' or ')' before 'argbackq'
external/sh/expand.c:542: error: expected ';', ',' or ')' before 'argbackq'
external/sh/expand.c:616: error: expected ';', ',' or ')' before 'argbackq'
external/sh/expand.c:653: error: expected ';', ',' or ')' before 'argbackq'
*** [external/sh/sh-expand.o] Error code 1

**Comment by bdrewery** [comment]
http://people.freebsd.org/~bdrewery/patch-Makefile.am -> ports-mgmt/poudriere-devel/files/patch-Makefile.am

Does the patch work? I wrote it up for linimon a few days ago and haven't heard back yet.

**Comment by bdrewery** [comment]
And for ports-mgmt/poudriere: https://people.freebsd.org/~bdrewery/patches/poudriere-sh-31-c99.diff

**Comment by bdrewery** [comment]
Let me know if it works and I'll push it out to the port.

**Comment by bdrewery** [comment]
Fixed in ports now.
