### ISSUE TITLE
jail -x needs to be supported for non-src builds

### ISSUE THREAD

**Issue by bdrewery** [freebsd/poudriere#477]
`jail -c -j 120C-SNAP-aarch64 -x -m url=http://ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/aarch64/12.0-CURRENT/ -v 12.0-CURRENT -a arm64.aarch64`

This did not actually build and install the XDEV / native-xtools pieces.

**Comment by rootwyrm** [comment]
Yep... XDEV=1 only triggers within `build_and_install_world()` at line 364 in jail.sh. What would the preference be as far as addressing that? Should only need 364-416. But given various factors, would it make sense to be able to rebuild xtools outside of jail creation (e.g. as part of update)?

**Comment by bdrewery** [comment]
Update usually calls `build_and_install_world` too. We need the XDEV code to run anytime `-c` or `-u` that `-x` (`XDEV==1`) is set, before the `@clean` snapshot is created.

**Comment by bdrewery** [comment]
I would not bother doing it for `-m null` though and instead have an error that it is not supported.  It's best to not mess with an existing chroot and to consider it read-only as much as possible.

**Comment by rootwyrm** [comment]
As implemented, users performing updates will need to include `-X`, but it should cover clean and update scenarios.
