### ISSUE TITLE
make check-plist ok but poudriere testport report check-plist error

### ISSUE THREAD

**Issue by amutu** [freebsd/poudriere#484]
This Port run 'make check-plist' manually OK, but poudriere testport report error:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219682

Detail:
poudriere testport -j 103amd64 databases/ora2pg
......
====> Running Q/A tests (stage-qa)
Notice: You have some Perl modules as dependencies but you do not have devel/p5-Module-CoreList installed, the perlcore QA check gets better results when using it, especially with older Perl versions.
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%SITE_ARCH%%/auto/Ora2Pg/.packlist
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/databases/ora2pg
====>> Error: check-plist failures detected
build of databases/ora2pg ended at Thu Jun  8 17:10:37 CST 2017
build time: 00:00:29
!!! build failure encountered !!!
[00:01:18] ====>> Error: Build failed in phase: check-plist
[00:01:18] ====>> Cleaning up
[00:01:21] ====>> Unmounting file systems
root@:/usr/ports/databases/ora2pg # ls
Makefile        distinfo        pkg-descr       pkg-plist       work
root@:/usr/ports/databases/ora2pg # make check-plist
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
===> No pkg-plist issues found (check-plist)

**Comment by bdrewery** [comment]
@mat813

**Comment by bdrewery** [comment]
Which version of poudriere is this?
Does the problem go away with this in poudriere.conf? `BUILD_AS_NON_ROOT=no`

**Comment by amutu** [comment]
poudriere version
3.1.17

with this setting, the problem still there.

**Comment by mat813** [comment]
Removing %%SITE_ARCH%%/auto/Ora2Pg/.packlist from the plist should fix the issue.

**Comment by bdrewery** [comment]
@mat any idea why it would work outside of Poudriere? Seems odd.

**Comment by mat813** [comment]
Mmmm, not really. The problem is that the .packlist files are added automatically during post-install by perl5.mk, so if you add it to the pkg-plist file, it will end up being there twice, which is reported by the check-plist code.

I can't find a databases/ora2pg in my ports tree, so I cannot really test exactly what is wrong.

**Comment by amutu** [comment]
this pr have the port shar：https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219682

I rember I  try to remove the line from plist file but install or portlint will report error.

**Comment by mat813** [comment]
Well, like I usually say, portlint is a static lint tool that gets it wrong most of the time.
You have to remove the .packlist from the pkg-plist file.

**Comment by bapt** [comment]
@amutu have you added DEVELOPER=yes in yout make.conf? have you run make check-plist?

**Comment by amutu** [comment]
@bapt Yes I have DEVELOPER=yes set.
I try again and find that removing the .packlist line  from pkg-plist fix the problem.Now check-plist and poudriere all passed.
I find another problem for this port about ETCDIR/DOCDIR path and fixed now.Maybe this bug cause poudriere testport failed make me think removing the .packlist line do not fix the problem last time .

Thanks everyone!
