### ISSUE TITLE
Feature request: In interactive mode, chdir to the current port's directory

### ISSUE THREAD

**Issue by mat813** [freebsd/poudriere#491]
Almost every time I need to do something in an interactive testport jail, it starts with a cd /usr/ports/foo/bar.  It would be great it it was not needed :-)

**Comment by bdrewery** [comment]
Yeah it would be nice, we'd need to modify the profile I think.

**Comment by mat813** [comment]
Yes, I think adding a cd /usr/ports/foo/bar at the end of .profile would do it.

**Comment by mat813** [comment]
I'd say it is about 50/50, I need to go to the wrkdir, or the ports directory (to run make test or something).

Being able to run make makepatch using the work directory in the jail from outside the jail would be great.
