### ISSUE TITLE
Default "spinning job" timeout of 100k seconds too low for arm64 & llvm

### ISSUE THREAD

**Issue by bsdphk** [freebsd/poudriere#507]
Building llvm on arm64 routinely takes more than a day.

With a little load on the machine, 100k seconds is not enough.

See for instance: http://thunderx1.nyi.freebsd.org/data/110arm64-default/444616/logs/errors/llvm-devel-5.0.d20170524.log

**Comment by bdrewery** [comment]
I've raised it to 36 hours now. Let's see if that helps.
