### ISSUE TITLE
wiki: use_system_ports_tree instructions broken

### ISSUE THREAD

**Issue by mandree** [freebsd/poudriere#518]
for poudriere 3.1.19, the https://github.com/freebsd/poudriere/wiki/use_system_ports_tree instructions do not work.

```poudriere ports -c -m null -M /ports/custom -p custom``` does not work and only prints usage information. With ```poudriere ports -c -F -M /ports/custom -p custom``` or in particular ```poudriere ports -c -F -M /usr/ports -p default``` things work for me. Please fix the Wiki.

**Comment by mandree** [comment]
@bdrewery - this seems to be yours.

**Comment by bdrewery** [comment]
Thanks, I jumped the gun on updating the documentation for release. I'll add both old and new methods in.

**Comment by bdrewery** [comment]
Is it now fixed, thanks.
