### ISSUE TITLE
Make -C default for 'options'

### ISSUE THREAD

**Issue by ari** [freebsd/poudriere#527]
When I write

    poudriere options databases/mariadb102-server

and nothing happens, typically that's a bit surprising. What should be the default behaviour should be the -C option to clean the options for that one port and allow me to change them. Sometimes I mistype -c and regret it for the next 20 minutes.

**Comment by bdrewery** [comment]
Changing defaults after 5 years would probably be more surprising overall.

**Comment by ari** [comment]
Hi, please reconsider your choice here. Yes, its a change, but surely the number of people relying on 'options' to perform no action is probably rather small. Maybe I'm missing something obvious, but why would you want to type that interactive command and have it do nothing? What's the use case for the current behaviour?

**Comment by bdrewery** [comment]
So actually `-C` is already the default.
```
    -c          -- Use 'make config' target
    -C          -- Use 'make config-conditional' target (default)
```

```
COMMAND=config-conditional
...
while getopts "a:cCj:f:p:nrsz:" FLAG; do
        case "${FLAG}" in
                a)
                        ARCH=${OPTARG}
                        # If TARGET=TARGET_ARCH trim it away and just use
                        # TARGET_ARCH
                        [ "${ARCH%.*}" = "${ARCH#*.}" ] && ARCH="${ARCH#*.}"
                        ;;
                c)
                        COMMAND=config
                        ;;
                C)
                        COMMAND=config-conditional
                        ;;
...
```

**Comment by ari** [comment]
OK, I'll close this ticket. I'm getting myself confused between -c and -C for options and for bulk. They are different and one is painful, so remembering which is which is really important.

-c is almost always what you want when using `options` but almost never what you want when using `bulk`

I can think of one use case for `options -C` when used with -f to review all new options not previously set.

I'd still argue that `options -c` should be the default here, but I'll close this task if you think the change is too disruptive.
