### ISSUE TITLE
package only fetched if using -i option

### ISSUE THREAD

**Issue by nbari** [freebsd/poudriere#533]
For testing a package I use something like this:

     poudriere testport -v -j 11amd64 -p custom www/go-www 

But for some reason, I get errors like:

    !!! build failure encountered !!!               
    [00:00:06] ====>> Error: Build failed in phase: fetch

Therefore I notice that by enter in interactive mode and doing a `make` the package was fetched:

    poudriere testport -v -j 11amd64 -p custom www/go-www 

and then: 

    cd /usr/ports/www/go-www; make

That fetched the packages and I just copy them to `/usr/ports/distfiles/`

Then again:

    poudriere testport -v -j 11amd64 -p custom www/go-www 

More details here: https://stackoverflow.com/q/46455135/1135424

I am using version 3.1.19 on FreeBSD amd64 11.1

Some of the logs are here: http://build.affe.network/jail.html?mastername=11amd64-custom for example http://build.affe.network/data/11amd64-custom/2017-09-27_19h29m02s/logs/errors/go-www-1.1.1.log

**Comment by bdrewery** [comment]
Looks solved in the stackoverflow link.

```
=======================<phase: fetch          >============================
===>  License BSD3CLAUSE accepted by the user
===>   go-www-1.1.1 depends on file: /usr/local/sbin/pkg - found
=> nbari-www-1.1.1_GH0.tar.gz doesn't seem to exist in /portdistfiles/.
=> Attempting to fetch https://codeload.github.com/nbari/www/tar.gz/1.1.1?dummy=/nbari-www-1.1.1_GH0.tar.gz
fetch: 4211: No such file or directory
nbari-www-1.1.1_GH0.tar.gz                               0  B    0  Bps
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/nbari-www-1.1.1_GH0.tar.gz
fetch: 4211: No such file or directory
fetch: http://distcache.FreeBSD.org/ports-distfiles/nbari-www-1.1.1_GH0.tar.gz: Not Found
=> Couldn't fetch it - please try to retrieve this
=> port manually into /portdistfiles/ and try again.
*** Error code 1
```

As noted in the stackoverflow link, the problem here was duplicate entries in _distinfo_.
The _Mk/Scripts/functions.sh_ `distinfo_data` function expects that a file will only be listed twice.
Some sort of QA/validation check may make sense in Ports, but not for Poudriere.
