### ISSUE TITLE
Restore support for colon in jail names

### ISSUE THREAD

**Issue by rootwyrm** [freebsd/poudriere#546]
Observed in poudriere-devel-3.2.99.20171111 on 11.1-REL. Subject says most of it. Having $JAILNAME correspond directly to ${ABI} is a massive time saver to say the least. And colon definitely was not banned before.

**Comment by bdrewery** [comment]
It's not a bug, it was an intended change.  Colons cause problems for `PATH`.

**Comment by bdrewery** [comment]
I'll see if I can make it replace `:` with another value for mounting.

**Comment by rootwyrm** [comment]
If you can point me to the error (I can honestly say I've had zero problems, so was unaware), I'm happy to help with fixing this one.

**Comment by bdrewery** [comment]
The problem is with buildworld using the source tree pathname in _PATH_.  It's not worth fixing there.

**Comment by bdrewery** [comment]
I actually blocked buildworld in FreeBSD base from using : in paths so I'll just revert this Poudriere change.  If you avoid buildworld then it won't be a problem.
