### ISSUE TITLE
'poudriere ports' can end up removing a ports checkout

### ISSUE THREAD

**Issue by rakuco** [freebsd/poudriere#547]
I'm using poudriere-devel (3.2.99.20171111), with a ports git checkout at /usr/local/poudriere/ports/default:

```sh
# poudriere ports -l
PORTSTREE METHOD TIMESTAMP           PATH
default   git    2016-01-16 18:51:31 /usr/local/poudriere/ports/default
```

In a momentary brain fart, I tried creating another ports tree in the same location:

```sh
# poudriere ports -c -m git -p qt59 -M /usr/local/poudriere/ports/default -B qt-5.9 -f none
[00:00:00] Cloning the ports tree...fatal: destination path '/usr/local/poudriere/ports/default' already exists and is not an empty directory.
[00:00:00] Error:  fail
[00:00:00] Error while creating ports tree, cleaning up.
```

After this command ran, `/usr/local/poudriere/ports/default` was removed from my file system, and I had to clone it again from scratch.

Poudriere should probably warn about the screw-up but not try changing the existing checkout directory.

**Comment by rakuco** [comment]
Oh, Poudriere still considers the directory exists:

```sh
# poudriere ports -c -m git 
[00:00:00] Error: The ports tree, default, already exists
# poudriere ports -l 
PORTSTREE METHOD TIMESTAMP           PATH
default   git    2016-01-16 18:51:31 /usr/local/poudriere/ports/default
```

**Comment by brd** [comment]
Just to confirm, the directory did get nuked even though it thinks it is there via `poudriere ports -l` ?

**Comment by rakuco** [comment]
Correct.

**Comment by bdrewery** [comment]
It's because you used `-f none` which considers a successful `mkdir -p` to be that poudriere created the destination.  I just need to make it check if the directory exists and is non-empty in `createfs`.
