### ISSUE TITLE
Unfriendly error message printed when user just intend to check usage

### ISSUE THREAD

**Issue by yunchih** [freebsd/poudriere#548]
Run `poudriere` first time without root will produce:

```
[yunchih@FreeBSD ~]$ poudriere image -h
mkdir: /usr/local/poudriere: Permission denied
/usr/local/share/poudriere/common.sh: parallel_shutdown: not found
```

Obviously, `poudriere` needs privilege to create that directory, but the above `parallel_shutdown: not found` error might be confusing for new users.  Why not source the necessary files in exit_handler:

``` git diff
diff --git a/src/share/poudriere/common.sh b/src/share/poudriere/common.sh
index f2df1da..006f45f 100755
--- a/src/share/poudriere/common.sh
+++ b/src/share/poudriere/common.sh
@@ -1091,6 +1091,8 @@ exit_handler() {
        # Ignore SIGINT while cleaning up
        trap '' SIGINT
 
+    . ${SCRIPTPREFIX}/include/parallel.sh
+
        if was_a_bulk_run; then
                log_stop
                # build_queue may have done cd MASTERMNT/.p/pool,
```
Interestingly, the `ports.sh` script can run all the way to printing "usage" before executing exit handler, while the `image.sh` script jump directly to exit handler before it can source `include/*.sh`.
`poudriere image -h`: http://ix.io/Cfl
`poudriere ports -h`: http://ix.io/Cfm

In addition, maybe it is better to run `. ${SCRIPTPREFIX}/common.sh` after `getopt`, so user can avoid running `common.sh` if they just want to check usage?

**Comment by bdrewery** [comment]
The `mkdir` isn't even needed anymore, it's a leftover from other refactoring. Will remove it.

**Comment by bdrewery** [comment]
> In addition, maybe it is better to run . ${SCRIPTPREFIX}/common.sh after getopt, so user can avoid running common.sh if they just want to check usage?

The getopts line may depend on defaults set by _common.sh_ so it must come after.

The difference with _ports_ vs _image_ is that _image_ runs with `set -e` and exits immediately on the `mkdir error`.
