### ISSUE TITLE
Add ".latest_$(hostname)" symlink to repo output

### ISSUE THREAD

**Issue by rootwyrm** [freebsd/poudriere#550]
This would prevent collision of `.latest` when combining output of multiple hosts into a single 'master' repository via rsync or similar. pkg repo would need to be taught to handle this in some fashion, preferably without needing knowledge of ports tree (timestamp of `.latest_$(hostname)/All/$pkgname` maybe?)

**Comment by bdrewery** [comment]
You can do this with a pkgbuild hook for now (https://github.com/freebsd/poudriere/wiki/hooks).  _PACKAGES_ will reference the .latest dir in the hook script.

**Comment by bdrewery** [comment]
This should be done as a hook. Poudriere won't do this. The thing you are doing is a workaround for the lack of distributed builds. I'm working on distributed builds in #473 but won't support what you're doing.
