### ISSUE TITLE
poudriere options (not recursive).

### ISSUE THREAD

**Issue by lebarondemerde** [freebsd/poudriere#551]
Hello!

It seems most people just deviate from defaults for a handful of ports, and most times just in the origins ones. Indeed most of the ports just have options for NLS/DOCS/EXAMPLES what people rarely change because the desired behavior is already set in the make.conf (or not set at all).

With the current recursive behavior of "poudriere options" we end with a ton ports set with DEFAULT options which can bring some unnecessary annoyance when the options change upstream. Not to say after some time we can't remember if we actually changed something for this or that port.

Please, consider the inclusion of a option to run "make config" just for the original target, and not for every single dependency.

Alternatively or in addiction, at least an option to "clean" all configured ports set with DEFAULT options.

Possible relation with #527

Thanks!

**Comment by bdrewery** [comment]
This is what the `-n` flag is for:

```
    -n          -- Do not configure/show/remove options of dependencies
```
