### ISSUE TITLE
Unable to update jail since version 3.2.1

### ISSUE THREAD

**Issue by RalfvdEnden** [freebsd/poudriere#555]
When I tried updating my jail to 11.1-RELEASE-p5 this morning I got the following error:

> [00:00:00] Upgrading using ftp
> /etc/resolv.conf -> /usr/local/poudriere/jails/freebsd_11-1x64/etc/resolv.conf
> env: /usr/sbin/freebsd-update.fixed: No such file or directory
> 11.1-RELEASE-p5
> [00:00:00] Recording filesystem state for clean... done
> 

After downgrading poudriere from my package cache to 3.2.0 it worked again.

**Comment by O2Graphics** [comment]
Same problem with poudriere-devel 3.2.99.20171127.

**Comment by bdrewery** [comment]
3.2.2 released with fix.
