### ISSUE TITLE
Incorrect jailed loopback address check.

### ISSUE THREAD

**Issue by koue** [freebsd/poudriere#559]
poudriere-3.1.22
I'm running poudriere inside jail. The jail has assigned loopback addresses 127.0.0.4 and ::4. Jailed loopback address check fails because in  /usr/local/share/poudriere/common.sh '127.0.0.1' and '::1' are defined.
Poudriere prints warning message "No loopback address defined, consider setting LOIP6/LOIP4 or assigning a loopback address to the jail."
Because of this 'lang/python27' build fails with message:
```
...
checking for getaddrinfo... yes
checking getaddrinfo bug... yes
Fatal: You must get working getaddrinfo() function.
       or you can specify "--disable-ipv6".
===>  Script "configure" failed unexpectedly.
Please report the problem to python@FreeBSD.org [maintainer] and attach the
"/wrkdirs/usr/ports/lang/python27/work/Python-2.7.14/config.log" including
...
```
In /usr/local/share/poudriere/common.sh if define LOIP4 to '127.0.0.4' and LOIP6 to '::4' and comment the IP addresses check then 'lang/python27' build is OK.

I checked poudriere 3.2.2 source and the same problem appears there also.

**Comment by koue** [comment]
misconfigured /usr/local/etc/poudriere.conf

LOIP4="127.0.0.4/32" instead of LOIP4="127.0.0.4"

**Comment by xaque208** [comment]
Did you need to get LOIP6 set also?  Was that `::4/128` then?
