### ISSUE TITLE
GH_PROJECT= ${PORTNAME:tl} crashed all jails

### ISSUE THREAD

**Issue by joneum** [freebsd/poudriere#562]
pkg info | grep poudriere
poudriere-devel-3.2.99.20171204_1 Port build and test system

uname -a
FreeBSD joneumbox.org 12.0-CURRENT FreeBSD 12.0-CURRENT #3 r325009: Thu Oct 26 16:18:05 CEST 2017

after a change from @mat here: https://reviews.freebsd.org/D13235 to GH_PROJECT=	${PORTNAME:tl}, all jails stop with "stopped:crashed"
[00:00:01] Error: Nonexistent origin listed for build: devel/pear-SebatianBergmann_PHPCPD
[00:00:01] Error: Fatal errors encountered gathering initial ports metadata

I have no explanation for that

Jochen

**Comment by bdrewery** [comment]
```
~/svn/ports # ls devel/pear-SebatianBergmann_PHPCPD
ls: devel/pear-SebatianBergmann_PHPCPD: No such file or directory
```

It is spelled _devel/pear-SebastianBergmann_PHPCPD_

```
~/svn/ports # ls devel/pear-SebastianBergmann_PHPCPD
./         ../        Makefile   distinfo   pkg-descr
```
