### ISSUE TITLE
Doesn't complain when invalid flavor has been requested

### ISSUE THREAD

**Issue by yurivict** [freebsd/poudriere#563]
It just ignores command line entries requesting flavors that aren't declared in ports.

**Comment by bdrewery** [comment]
testport is fine but not bulk.

**Comment by bdrewery** [comment]
The problem here is that the `make -V PKGNAME` lookup returns the default PKGNAME and poudriere assumes that it is the default FLAVOR and drops the lookup. An _IGNORE_ entry is returned due to the bad FLAVOR being used that is never processed due to the assumption.
