### ISSUE TITLE
Allow building a specific ports category

### ISSUE THREAD

**Issue by feld** [freebsd/poudriere#564]
Currently there is no way to build a category. You can build all ports or a list (optionally from a file). A method to build an entire category would be a huge win for me at work allowing me to build our internal ports category no matter which tree I'm on.

**Comment by bdrewery** [comment]
Sounds interesting but I won't implement such a feature as it is very niche and easily done by a wrapper.
```
#!/bin/sh
list=$(mktemp)
cd /poudriere/ports/default/local
echo * | tr ' ' '\n' > ${list}
poudriere bulk -j amd64 -f ${list}
```
You get the idea...
