### ISSUE TITLE
FreeBSD_HOST needs /pub/ directory

### ISSUE THREAD

**Issue by croquagei** [freebsd/poudriere#565]
I'm wanting to use my Universities mirror located at ftp://ftp.swin.edu.au

I've set my universities mirror ftp://ftp.swin.edu.au as FREEBSD_HOST in poudriere.conf 

The issue is fetching always looks at ftp://ftp.swin.edu.au/pub/FreeBSD

My Universities mirror (and many others) now forgo the pub/ directory.  Is there a way to further manipulate the host url?

**Comment by bdrewery** [comment]
Use something like `-m url=ftp://ftp.swin.edu.au/freebsd/releases/amd64/amd64/11.1-RELEASE/`
