### ISSUE TITLE
Typo in man page

### ISSUE THREAD

**Issue by RobBelics** [freebsd/poudriere#566]
man (8) Under EXAMPLES and Bulk Build of Binary Packages, should be "regar**d**less":

 

>  Of	course you can use another version of FreeBSD, **regarless** on what ver-
>      sion you are running.  amd64 users	can choose i386	arch like in this
>      example:

**Comment by brd** [comment]
Thank you for the report!

**Comment by bdrewery** [comment]
This file is obsolete and I've removed it. How did you stumble upon it? Is there a link somewhere?

**Comment by RobBelics** [comment]
https://www.freebsd.org/cgi/man.cgi?query=poudriere&sektion=8&manpath=FreeBSD+11.1-RELEASE+and+Ports

**Comment by bdrewery** [comment]
Aha thanks, that was fixed earlier in commit 28f71197edbe7713a8c6d06263a5d44c88e2948e. Not sure how that file is cached.

The proper one is at https://github.com/freebsd/poudriere/wiki/poudriere.8
