### ISSUE TITLE
Poudriere on 10.4-RELEASE-p3 fails to build pkg for armv6 - log included

### ISSUE THREAD

**Issue by bobbybudnick** [freebsd/poudriere#578]
(copied from the FreeBSD forums)

I setup an older but now updated FreeBSD system to build armv6 packages also for 10.4-Release-p3. Once the bulk build starts pkg is the first to be built but configuring fails immediately. I have attached the log. Thanks for any help. 

edit: If you need extra information just ask.
[pkg-1.10.3_1.log.txt](https://github.com/freebsd/poudriere/files/1609226/pkg-1.10.3_1.log.txt)

**Comment by bdrewery** [comment]
Your QEMU seems outdated. `utimensat` support was added to QEMU in 2016. https://svnweb.freebsd.org/ports?view=revision&revision=r417742

**Comment by bobbybudnick** [comment]
Thanks. I did just need to update the ports tree.
