### ISSUE TITLE
Options command forces custom options directory to be associated with a ports tree

### ISSUE THREAD

**Issue by davehayes** [freebsd/poudriere#583]
From the man page:

```
 Before building a package, poudriere can mount a directory containing option files if available. poudriere will check for any of these directories in this order:
    /usr/local/etc/poudriere.d/<jailname>-<tree>-<setname>-options
    /usr/local/etc/poudriere.d/<jailname>-<setname>-options
    /usr/local/etc/poudriere.d/<jailname>-<tree>-options
    /usr/local/etc/poudriere.d/<setname>-options
    /usr/local/etc/poudriere.d/<tree>-options
    /usr/local/etc/poudriere.d/<jailname>-options
    /usr/local/etc/poudriere.d/options

 If a directory with this name exists, it is null-mounted into the
 /var/db/ports/ directory of the jail, thus allowing to build package with
 custom OPTIONS.

 The options subcommand can be used to easily configure options in the correct directory.
```
Apparently, for the options subcommand, "the correct directory" is not
flexible, like implied above. Unless I use the 'default' ports tree, I can not
(easily) configure options in any of the following directories:

```
    /usr/local/etc/poudriere.d/<jailname>-<setname>-options
    /usr/local/etc/poudriere.d/<setname>-options
    /usr/local/etc/poudriere.d/<jailname>-options
    /usr/local/etc/poudriere.d/options
```
This is because the -p switch forces 'options' to use one of

```
    /usr/local/etc/poudriere.d/<jailname>-<tree>-<setname>-options
    /usr/local/etc/poudriere.d/<jailname>-<tree>-options
    /usr/local/etc/poudriere.d/<tree>-options
```
Of course, the behavior I'd expect to see is the same behavior as make.conf or
poudriere.conf; an 'overlay' of options directories with the most specific
options dir being used. This is because of the customizable behavior of
make.conf, src.conf, and poudriere.conf.

Here's how I discovered this. When I upgraded to 3.2.4, I got this dialog:

```
  > poudriere options -f myportlist -j myoldjail -p MYPORTSNAPSHOT
 [00:00:00] Warning: You already have options configured without '-p MYPORTSNAPSHOT' that will no longer be used.
 [00:00:00] Warning: Drop the '-p MYPORTSNAPSHOT' option to avoid this problem.
 [00:00:00] Are you sure you want to continue? [y/N] ^C
```

This was really surprising. Looking at the code I see this:

 ```sh
OLD_PORT_DBDIR=${POUDRIERED}/${JAILNAME}${JAILNAME:+-}${SETNAME}${SETNAME:+-}options
 PORT_DBDIR=${POUDRIERED}/${JAILNAME}${JAILNAME:+-}${PTNAME_TMP}${PTNAME_TMP:+-}${SETNAME}${SETNAME:+-}options

 if [ -d "${OLD_PORT_DBDIR}" ] && [ ! -d "${PORT_DBDIR}" ]; then
        msg_warn "You already have options configured without '-p ${PTNAME_TMP}' that will no longer be used."
        msg_warn "Drop the '-p ${PTNAME_TMP}' option to avoid this problem."
        if [ -t 0 ]; then
                confirm_if_tty "Are you sure you want to continue?" || exit 0
        else
                msg_warn "Will create ${PORT_DBDIR} which overrides existing ${OLD_PORT_DBDIR}"
        fi
 fi

 mkdir -p ${PORT_DBDIR}
```
What I do not see is the provision for the ordered checking of directories
that was implied in the manpage. What actually happened was this:

 ```
 OLD_PORT_DBDIR="/usr/local/etc/poudriere.d/myoldjail-options"
 PORT_DBDIR="/usr/local/etc/poudriere.d/myoldjail-MYPORTSNAPSHOT-options"
```
which means that even though I have old ports options in OLD_PORT_DBDIR, poudriere
wants to insist that I use PORT_DBDIR which has no options in it.

As an example of how this affects my use case, I have options trees in:

```
    /usr/local/etc/poudriere.d/<jailname>-options
    /usr/local/etc/poudriere.d/<jailname>-<setname>-options
```

This is because I typically have a few different package builds that I do
against this jail. I use setname to distinguish different builds. I don't use
a separate ports moniker in my options tree because there are critical options
I need to preserve for specific builds when I make packages from a new ports
tree.

**I mentioned (in IRC) creating a '-P' switch for the options command to tell the options command what
to use for PTNAME_TMP, with the default being no value. I hope you will consider this change or something with the same effect. Thank you for reading.**

**Comment by Nimloth** [comment]
The same seems to apply to sets:
Even when using the "default" ports tree, it seems the same problem occurs with sets.

```
poudriere options -j <jailname> -z <set> -f <port-list>
```

insists on creating a new folder

```
/usr/local/etc/poudriere.d/<jailname>-<set>-options
```

even if an options tree already exists in

```
/usr/local/etc/poudriere.d/<set>-options
```

**Comment by bdrewery** [comment]
#111 will fix this
