### ISSUE TITLE
Error: DISTFILES_CACHE directory does not exist.

### ISSUE THREAD

**Issue by interkosmos** [freebsd/poudriere#597]
When trying to run `poudriere-bulk` I get the error:
```
# poudriere bulk -j 11-amd64 -p local -C misc/abc123
[00:00:00] Error: DISTFILES_CACHE directory does not exist. (c.f.  poudriere.conf)
```
This leads to not beeing able to build any ports.

**Comment by bdrewery** [comment]
Define and create the directory.

Regards,
Bryan Drewery

**Comment by interkosmos** [comment]
The directory is defined and created. Actually, it is a ZFS mount point.

**Comment by bdrewery** [comment]
Then it must not be mounted, try `zfs mount <dataset>`.
This error only happens if `DISTFILES_CACHE` is set to a directory that does not exist.

**Comment by interkosmos** [comment]
Well, the strange this is that it is mounted:
```
# zfs list
zroot/usr/ports                    408K  54,6G   408K  /usr/ports
```

**Comment by bdrewery** [comment]
That's ports not distfiles.

**Comment by interkosmos** [comment]
Oh.
