### ISSUE TITLE
After Emacs ports are flavorized some of them can't be built with poudriere if 'DEFAULT_VERSIONS+=emacs=nox' is added to make.conf

### ISSUE THREAD

**Issue by yasuhirokimura** [freebsd/poudriere#600]
I preferred `editors/emacs-nox11` as emacs. So I added `EMACS_PORT_NAME=emacs-nox11` to `make.conf` and built and installed my favorite emacs ports. It worked fine both on real environment and with poudriere. 

But after r460621 of ports tree emacs ports are flavorized. So I replaced `EMACS_PORT_NAME=emacs-nox11` with `DEFAULT_VERSIONS+=emacs=nox` in `make.conf` and rebuilt and installed emacs ports. On real environment everything worked fine. But with poudriere some of them failed to be built because of dependency error. Examples of such ports are `devel/magit` and `www/emacs-w3m`. Attached files below are build log of them.

[magit-emacs25_nox-2.11.0_1.log](https://github.com/freebsd/poudriere/files/1778417/magit-emacs25_nox-2.11.0_1.log)
[emacs-w3m-emacs25_nox-1.4.598.b.20170903_3.log](https://github.com/freebsd/poudriere/files/1778418/emacs-w3m-emacs25_nox-1.4.598.b.20170903_3.log)

Host OS: 11.1-RELEASE amd64
Version of poudriere: 3.2.4_1
Jail OS: 11.1-RELEASE amd64
Ports tree revision: 463550

**Comment by bdrewery** [comment]
Thanks for your report. Something looks wrong here. I'll look into it in the next few days.

**Comment by yasuhirokimura** [comment]
I found another problem under same condition. Its about `options` command.

Let's assume there is no `${PREFIX}/etc/poudriere.d/options` directory and execute `poudriere options devel/magit`. At first options editor is invoked to edit options of `devel/magit`, and after it is finished it is invoked to edit that of `editors/emacs`. By the way there are following lines in `editors/emacs/Makefile`.

> .if ${FLAVOR:U} == nox
> (snip)
> OPTIONS_EXCLUDE=	ALSA CAIRO DBUS GCONF GIF GSETTINGS GTK2 GTK3 JPEG \
					M17N MAGICK MOTIF OSS OTF PNG SCROLLBARS SVG TIFF XAW \
					XAW3D XFT XIM XPM XWIDGETS
> .else
> (snip)
> .endif

So items edited by options editor are different between full and nox flavors. And in this case options editor should display options for nox flavor. But actually it displays that for full flavor.

I'm not sure if the source of this problem is same as that of original build error problem. But it happens under same condition. So I decided to report it as same issue. If I should report it as separated one, please let me know.

**Comment by bdrewery** [comment]
The emacs port is the problem not Poudriere. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225659
