### ISSUE TITLE
poudriere does not build TEST_DEPENDS

### ISSUE THREAD

**Issue by dag-erling** [freebsd/poudriere#609]
When working on upgrading a port I maintain, I like to do something like this:

    % cd cat/port
    % sudo pkg install -A $(make missing)

This often fails because I don't build the entire repo and even though `cat/port` is in my package list, Poudriere only builds its fetch / build / run dependencies, not its test dependencies.

I believe this could be solved by adding `${TEST_DEPENDS}` to `_PDEPS` around line 4439 of `common.sh` (in 3.2.6), or just by using `_UNIFIED_DEPENDS` instead of `_PDEPS`. For instance:

    des@desk ~/ports/databases/p5-DBIx-Class-Schema-Loader% make _PDEPS='${PKG_DEPENDS} ${EXTRACT_DEPENDS} ${PATCH_DEPENDS} ${FETCH_DEPENDS} ${BUILD_DEPENDS} ${LIB_DEPENDS} ${RUN_DEPENDS}' -V '${_PDEPS:C,([^:]*):([^:]*):?.*,\2,:C,^${PORTSDIR}/,,:O:u}'                                                            
    databases/mysql57-client databases/p5-DBIx-Class databases/postgresql96-client devel/p5-Carp-Clan devel/p5-Class-Accessor-Grouped devel/p5-Class-C3-Componentised devel/p5-Class-Inspector devel/p5-Class-Unload devel/p5-Data-Dump devel/p5-MRO-Compat devel/p5-Scope-Guard devel/p5-curry devel/p5-namespace-clean lang/p5-Try-Tiny lang/perl5.26 ports-mgmt/pkg textproc/p5-Hash-Merge textproc/p5-Lingua-EN-Inflect-Number textproc/p5-Lingua-EN-Inflect-Phrase textproc/p5-Lingua-EN-Tagger textproc/p5-String-ToIdentifier-EN
    des@desk ~/ports/databases/p5-DBIx-Class-Schema-Loader% make -V '${_UNIFIED_DEPENDS:C,([^:]*):([^:]*):?.*,\2,:C,^${PORTSDIR}/,,:O:u}'
    databases/mysql57-client databases/p5-DBD-SQLite databases/p5-DBIx-Class databases/postgresql96-client devel/p5-Carp-Clan devel/p5-Class-Accessor-Grouped devel/p5-Class-C3-Componentised devel/p5-Class-Inspector devel/p5-Class-Unload devel/p5-Data-Dump devel/p5-MRO-Compat devel/p5-Scope-Guard devel/p5-Test-Deep devel/p5-Test-Differences devel/p5-Test-Exception devel/p5-Test-Warn devel/p5-curry devel/p5-namespace-clean lang/p5-Try-Tiny lang/perl5.26 ports-mgmt/pkg textproc/p5-Hash-Merge textproc/p5-Lingua-EN-Inflect-Number textproc/p5-Lingua-EN-Inflect-Phrase textproc/p5-Lingua-EN-Tagger textproc/p5-String-ToIdentifier-EN

This would probably also require adding `TEST_DEPENDS` to `_changed_deps` on line 4419 of `common.sh`.

EDIT: that last part is a lot more complicated than I thought...

EDIT EDIT: also probably unnecessary.

**Comment by bdrewery** [comment]
Yes Poudriere does not support it yet. Tracking bug is #355
