### ISSUE TITLE
Port Sanity Check Failure

### ISSUE THREAD

**Issue by sylgeist** [freebsd/poudriere#611]
Poudriere 3.2.6
Port print/freetype2

Options for port:
```
# This file is auto-generated by 'make config'.
# Options for freetype2-2.9_1
_OPTIONS_READ=freetype2-2.9_1
_FILE_COMPLETE_OPTIONS_LIST=DEBUG DOCS LONG_PCF_NAMES PNG TABLE_VALIDATION LCD_FILTERING LCD_RENDERING FIX_SIZE_METRICS TT_SIZE_METRICS V38 V40
OPTIONS_FILE_UNSET+=DEBUG
OPTIONS_FILE_UNSET+=DOCS
OPTIONS_FILE_UNSET+=LONG_PCF_NAMES
OPTIONS_FILE_UNSET+=PNG
OPTIONS_FILE_UNSET+=TABLE_VALIDATION
OPTIONS_FILE_UNSET+=LCD_FILTERING
OPTIONS_FILE_SET+=LCD_RENDERING
OPTIONS_FILE_UNSET+=FIX_SIZE_METRICS
OPTIONS_FILE_UNSET+=TT_SIZE_METRICS
OPTIONS_FILE_UNSET+=V38
OPTIONS_FILE_SET+=V40
```

Error message during build:
```
=======================<phase: check-sanity   >============================
===>  License FTL GPLv2+ accepted by the user
====> You must select one and only one option from the RENDERING single
=====> Only one of these must be defined: LCD_FILTERING LCD_RENDERING
*** Error code 1
```

Make.conf
```
WITH_PKG=yes
MK_PROFILE=no
OPTIONS_UNSET+= DOCS NLS X11 EXAMPLES
DEFAULT_VERSIONS+=ssl=libressl
DEFAULT_VERSIONS+=pgsql=10
DEFAULT_VERSIONS+=python=3.6
```

It's not clear to me if this is a port issue or a Poudriere issue. I have tried 
- clearing the option for freetype2 (and dependencies)
- remove and recreating the jail
- trying various combinations of options for the port

**Comment by bdrewery** [comment]
When running `poudriere bulk` it will tell you exactly which options directory is being used. Verify that
the one it is using is the one that you found the options in. I'm guessing it's not the same due to
how `poudriere options -p` works.

I doubt this is a Poudriere bug though.

**Comment by sylgeist** [comment]
You are correct! Thank you!
Did something change with the precedence of options parsing in a recent version? Possibly just a leftover options dir that had an incompatible selection, but strange!
