### ISSUE TITLE
Issue with ports that install a python versioned binary and building multiple flavors

### ISSUE THREAD

**Issue by SBBH** [freebsd/poudriere#616]
I'm not sure if this is actually a poudriere issue or if this is something to do with the way python ports and flavors work so I'm not 100% sure where to post this but hopefully you don't mind or can give me some direction on where to ask.

Take security/ py-certbot for example. If python 2.7 is the default it will install the binary as "certbot-2.7" with a "certbot" symlink. Same idea if python 3.6 is the default, etc.

However, if building multiple flavors then it will only create the certbot symlink for the default version of python but no symlink for the non-default version. So, for example, on my poudriere setup I have a FreeBSD 11.1 jail that has python 3.6 set as the default version but I build all packages for both python 2.7 and 3.6. So, py36-certbot is fine, it installs both "certbot-3.6" and a symlink certbot -> certbot-3.6 but  py27-certbot only installs "certbot-2.7" with no symlink. I've noticed this with textproc/py-chardet and devel/py-setuptools and probably others but I haven't looked further.

**Comment by bdrewery** [comment]
What symlink are you expecting in the 3.6 default case, for 2.7? If `certbot` is already taken by 3.6 then what could 2.7 add? (It's not a Poudriere issue)

**Comment by SBBH** [comment]
I'm not installing both versions on the same system. We have some jails
that need Python 2.7 and some that need 3.6 so I build both flavors.

3.6 is the default so the 3.6 flavor creates a symlink however 2.7 does
not. If I make 2.7 the default then that is reversed.

I thought it might not be poudriere. Also, probably not something most
people ever have to deal with so don't run into often. Guess I'll just have
to work around it.

**Comment by mat813** [comment]
It has nothing to do with poudriere, and I would really say it is not a bug.
Only the default version gets a symlink, so that the packages do not conflict.

**Comment by bdrewery** [comment]
Ah I see now. It's the lack of an _alternatives system_. The default has to be known at build time currently. We have no runtime support for changing the default unfortunately. Either way it's an issue outside of Poudriere. Sorry about that.
