### ISSUE TITLE
Package getting hosed when running testport ports-mgmt/pkg

### ISSUE THREAD

**Issue by mat813** [freebsd/poudriere#617]
(using poudriere-devel-3.2.99.20180601)

So, you use poudriere, and all is well, and you have:

```
$ ls -lA /p/data/packages/11amd64-ports/Latest/
total 1
lrwxr-xr-x  1 mat   wheel  23  8 juin  16:50 pkg.tar@ -> ../All/pkg-1.10.5_1.tar
```

which is perfectly normal. 

Then, for some reason, you need to `testport ports-mgmt/pkg`, it all goes well, and now, you have:

```
$ ls -lA /p/data/packages/11amd64-ports/Latest/
total 1
lrwxr-xr-x  1 mat   wheel  31  8 juin  16:51 pkg.tar@ -> ../../tmp/pkgs/pkg-1.10.5_1.tar
```

which is fine while running `testport ports-mgmt/pkg` because it does point to an actually working package.

But it breaks poudriere in a few very subtle way, like, for example, it kinda silently disables incremental rebuild and repository sanity checks, so you can rapidly end up with a very, very broken repository.

The workaround I found to fix this without manually changing things is to run `bulk -C ports-mgmt/pkg`, which then goes back to:

```
$ ls -lA /p/data/packages/11amd64-ports/Latest/
total 1
lrwxr-xr-x  1 mat  wheel  23  8 juin  16:54 pkg.tar@ -> ../All/pkg-1.10.5_1.tar
```

But I am sure I am going to forget I have to do this when I testbuild pkg one day, and it is going to mess everything up again.

**Comment by bdrewery** [comment]
Hm this is probably a ports issue. I think it's the one creating the symlink. So it should be wiping the symlink too. Likely a missed piece when we stripped down the Latest links to only be for _pkg_.

**Comment by bdrewery** [comment]
bsd.port.mk:
```
3373 .  if ${PKGORIGIN} == "ports-mgmt/pkg" || ${PKGORIGIN} == "ports-mgmt/pkg-devel"
3374 _EXTRA_PACKAGE_TARGET_DEP+= ${PKGLATESTREPOSITORY}
3375 _PORTS_DIRECTORIES+=    ${PKGLATESTREPOSITORY}
3376 _EXTRA_PACKAGE_TARGET_DEP+= ${PKGLATESTFILE}
3377
3378 ${PKGLATESTFILE}: ${PKGFILE} ${PKGLATESTREPOSITORY}
3379     ${INSTALL} -l rs ${PKGFILE} ${PKGLATESTFILE}
3380 .  endif
3381
3382 .endif
```

Yeah the framework is creating it.

Though now that I think for more than a second I remember that Poudriere is the one deleting the package. I'll make it delete the link.

**Comment by bdrewery** [comment]
To be clear I'm going to fix the dangling symlink. I'm not fixing the #185 issue here despite it being annoying for the bootstrap.

**Comment by bdrewery** [comment]
Hrm I cannot find where `testport` deletes the package from the repository though. I'm stale on this.

**Comment by mat813** [comment]
When testport deletes which package? If it's the port you asked to build, I don't think it deletes it, I think it simply creates it some other place, and because it's pkg, it messes up the symlink.

**Comment by bdrewery** [comment]
Figured it out.

```
+ jexec -U root exp-11amd64-commit-test /usr/bin/limits -n 1024 /usr/bin/env 'PACKAGES=/tmp/pkgs' 'PKGREPOSITORY=/tmp/pkgs' 'DEVELOPER_MODE=yes' 'STRICT_DEPENDS=yes' /usr/bin/make -C /usr/ports/ports-mgmt/pkg package
make: "/usr/ports/Mk/bsd.port.mk" line 2593: PKGLATESTREPOSITORY=/.npkg/Latest -- PKGLATESTFILE=/.npkg/Latest/pkg.txz -- PKGREPOSITORY=/tmp/pkgs -- PACKAGES=/.npkg
make[1]: "/usr/ports/Mk/bsd.port.mk" line 2593: PKGLATESTREPOSITORY=/.npkg/Latest -- PKGLATESTFILE=/.npkg/Latest/pkg.txz -- PKGREPOSITORY=/tmp/pkgs -- PACKAGES=/.npkg
===>  Building package for pkg-1.10.5_5
```

The problem is that `testport` was setting `PKGENV="PACKAGES=/tmp/pkgs PKGREPOSITORY=/tmp/pkgs"` to write packages to _/tmp/pkgs_. However down in _build_port_ is:

```
if [ "${phase}" = "package" ]; then
        echo "PACKAGES=/.npkg" >> ${mnt}/etc/make.conf
        # Create sandboxed staging dir for new package for this build
        rm -rf "${PACKAGES}/.npkg/${PKGNAME}"
        mkdir -p "${PACKAGES}/.npkg/${PKGNAME}"
        ${NULLMOUNT} \
                "${PACKAGES}/.npkg/${PKGNAME}" \
                ${mnt}/.npkg
        chown -R ${JUSER} ${mnt}/.npkg
        :> "${mnt}/.npkg_mounted"
fi
```
This is making a tmpfs for the package drop even though the `pkg-1.x.txz` wasn't being written there. Only the symlink was being written there.

```
make[1]: "/usr/ports/Mk/bsd.port.mk" line 2593: PKGLATESTREPOSITORY=/.npkg/Latest -- PKGLATESTFILE=/.npkg/Latest/pkg.txz -- PKGREPOSITORY=/tmp/pkgs -- PACKAGES=/.npkg
```

In bsd.port.mk:
```
PKGREPOSITORY?=     ${PACKAGES}/${PKGREPOSITORYSUBDIR}
```
So because of the `PACKAGES=` set to _/.npkg_ via _make.conf_ there but the `PKGREPOSITORY` still set in the environment from `PKGENV` the latest link is all that was getting written to the tmpfs mount and it was later getting copied over:
(From using `mv -v` in the _/.npkg_ sync code)
```
/poudriere/data/packages/exp-11amd64-commit-test/.latest/.npkg/pkg-1.10.5_5/Latest/pkg.txz -> /poudriere/data/packages/exp-11amd64-commit-test/.latest//Latest/pkg.txz
```
So I need to avoid the _/.npkg_ override when `PKGENV` doesn't want it.
