### ISSUE TITLE
Upgrade from 3.2.8 to 3.3.1 causes now that gitlab-ce does not build anymore due to "Files or directories removed"

### ISSUE THREAD

**Issue by mfechner** [freebsd/poudriere#666]
It seems that the new version does not allow to touch `/usr/home` anymore:
```
===========================================================================
=>> Checking for extra files and directories
=>> Error: Files or directories removed:
/usr/home
build of www/gitlab-ce | gitlab-ce-11.8.0 ended at Sat Mar  2 13:29:51 CET 2019

```
If I remove the line from `pkg-plist` in `www/gitlab-ce` I get the error message:
```
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir /usr/home
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1
```

You can find both log files here:
https://pkg.fechner.net/data/120amd64-gitlab/2019-03-02_13h28m07s/logs/errors/gitlab-ce-11.8.0.log
https://pkg.fechner.net/data/120amd64-gitlab/2019-03-02_13h21m49s/logs/errors/gitlab-ce-11.8.0.log

How can I fix this?

**Comment by bdrewery** [comment]
It's related to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225309.
Though I only expected an issue if `MUTABLE_BASE=schg` was set. I'll take a look.

**Comment by bdrewery** [comment]
(This is all a *Ports* problem. The only reason it shows up now is because Poudriere creates _/usr/home_ in the jail before starting a package build.)
I think this ports commit exposed the existing problem. I had run into it before since I was using ccache.

```
Author: antoine
Date: Fri Mar  1 20:26:11 2019
New Revision: 494316
URL: https://svnweb.freebsd.org/changeset/ports/494316

Log:
  Fix leftover detection when ccache is not used
  
  With hat:	portmgr

Modified:
  head/Mk/Scripts/check_leftovers.sh

Modified: head/Mk/Scripts/check_leftovers.sh
==============================================================================
--- head/Mk/Scripts/check_leftovers.sh	Fri Mar  1 20:11:47 2019	(r494315)
+++ head/Mk/Scripts/check_leftovers.sh	Fri Mar  1 20:26:11 2019	(r494316)
@@ -54,7 +54,7 @@ tmpplist=$(make -C ${portdir} -VTMPPLIST)
 while read -r modtype path extra; do
 	# Ignore everything from these files/directories
 	case "${path}" in
-		${CCACHE_DIR}/*|\
+		${CCACHE_DIR:-/nonexistent}/*|\
 		/compat/linux/proc/*|\
 		/dev/*|\
 		/etc/make.conf.bak|\
```


The problem is that in 3.3 Poudriere is creating _/usr/home_ exactly because gitlab-ce (per PR 225309) is
trying to write to it. So it's now a pre-existing directory in the jail but the pkg-plist is trying to remove it.
This kind of thing is normally handled by directories existing in _/usr/ports/Templates/BSD.local.dist_ and
special case ignores in _/usr/ports/Mk/check_leftovers.sh_. Normally in _check_leftovers.sh_ the home directory for the port's `USERS` is used (from _/usr/ports/UIDs_) is ignored and no problem like this manifests. But because this port is creating its own directory somewhere on the system that is pre-existing but otherwise not ignored it hits this problem.

The list of places outside of _/usr/local_ that is port is "allowed" to write to is limited to this list from
_check_leftovers.sh_:
```
# Ignore everything from these files/directories
case "${path}" in
        ${CCACHE_DIR:-/nonexistent}/*|\
        /compat/linux/proc/*|\
        /dev/*|\
        /etc/make.conf.bak|\
        /proc/*|\
        /tmp/*|\
        /var/db/pkg/*|\
        /var/db/ports/*|\
        /var/log/*|\
        /var/mail/*|\
        /var/run/*|\
        /var/tmp/*) continue ;;
        # fc-cache - skip for now
        /var/db/fontconfig/*) continue ;;
esac
```
(There's a few exceptions later on but this is pretty much it.)

Adding _/usr/home_ to this list doesn't seem like a good idea to me. The gitlab port really should be
writing to a better place.

**Comment by bdrewery** [comment]
Note also that _sysutils/condor_ writes to _/usr/home_ so Poudriere needs to create this directory to allow writes to it. That port doesn't have this problem since its user in _/usr/ports/UIDs_ is properly set.
```
~/svn/ports # grep condor UIDs
condor:*:466:466::0:0:& user:/home/condor:/usr/sbin/nologin
```
(Poudriere symlinks _/home_ to _/usr/home_.)

**Comment by bdrewery** [comment]
Oddly with `MUTABLE_BASE=schg` I don't get the leftover. I'm missing something. Looking into it more.

**Comment by mfechner** [comment]
> It's related to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225309.
> Though I only expected an issue if `MUTABLE_BASE=schg` or `MUTABLE_BASE=no` was set. Do you have either of those?

no, I define the following options in my poudriere make.conf:
```
DEFAULT_VERSIONS=php=7.2 mysql=10.3m bdb=6 ssl=openssl111 pgsql=9.6 samba=4.8
WITH_BDB6_PERMITTED=1
WANT_OPENLDAP_SASL=yes

WITH_MPM=event
OPTIONS_UNSET=DEBUG DOCBOOK EXAMPLES
OPTIONS_SET=proxy dav ssl ldap

#DISABLE_LICENSES=yes
NO_LICENSES_INSTALL=           yes
NO_LICENSES_DIALOGS=           yes
LICENSES_ACCEPTED+=NONE
```

**Comment by bdrewery** [comment]
> > It's related to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225309.
> > Though I only expected an issue if `MUTABLE_BASE=schg` or `MUTABLE_BASE=no` was set. Do you have either of those?
> 
> no, I define the following options in my poudriere make.conf:
> 
> ```
> DEFAULT_VERSIONS=php=7.2 mysql=10.3m bdb=6 ssl=openssl111 pgsql=9.6 samba=4.8
> WITH_BDB6_PERMITTED=1
> WANT_OPENLDAP_SASL=yes
> 
> WITH_MPM=event
> OPTIONS_UNSET=DEBUG DOCBOOK EXAMPLES
> OPTIONS_SET=proxy dav ssl ldap
> 
> #DISABLE_LICENSES=yes
> NO_LICENSES_INSTALL=           yes
> NO_LICENSES_DIALOGS=           yes
> LICENSES_ACCEPTED+=NONE
> ```

Yup see the rest please. I've edited out some distractions just now.

**Comment by mfechner** [comment]
The new gitlab version uses now the standard path for the git user (/usr/local/git), but I see a left-over error message:
https://pkg.fechner.net/data/120amd64-default/2019-04-24_22h34m36s/logs/errors/gitlab-ce-11.10.0.log

Do you have an idea what this error means.
The error message:
```
==> You should manually remove the "git" user. 
==> You should manually remove the "git" group 
===========================================================================
=>> Checking for extra files and directories
=>> Error: Files or directories removed:
git
=>> Cleaning up wrkdir
```
is not clear for me.

**Comment by mfechner** [comment]
Everything works now, thanks!
