### ISSUE TITLE
EVIRONMENT section of manpage incomplete

### ISSUE THREAD

**Issue by michael-o** [freebsd/poudriere#668]
The entire section does not reflect that `FETCH_BIND_ADDRESS`, `HTTP_PROXY`, `FTP_PROXY`, `NO_PROXY` and `MAKEOBJDIRPREFIX` apply to both `ports` and `jail` subcommands.

Willing to provide a PR for that.

**Comment by bdrewery** [comment]
Thanks fixed.

**Comment by michael-o** [comment]
Looks good to me. Looking forward for the next release.
