### ISSUE TITLE
Mysterious failure with -m null jail (missing version)

### ISSUE THREAD

**Issue by trombonehero** [freebsd/poudriere#675]
When creating a jail with `-m null -M /path/to/installation`, no `version` file seems to be created in the `/usr/local/etc/poudriere.d/jails/JAILNAME` directory. This is, apparently, a fatal problem, as `poudriere bulk` stops executing with no error message — at least with v3.3.1, it exists with an exit status of 1, with the final line of output being `Balancing pool`.

After adding some tracing to `common.sh` I can see that the problem comes from attempting to read `/usr/local/etc/poudriere.d/jails/JAILNAME/version`, but you have to modify Poudriere to learn that. Could one (or both?) of the following be done to provide a bit more feedback?

 - [ ] make `poudriere jail -c` emit an error when `-m null` is attempted without `-v`
 - [ ] make `jget` (or `get_attr`? or `read_file`?) emit an error message when it fails

Or am I, perhaps, misunderstanding the purpose of the `version` file?

Thanks.

**Comment by bdrewery** [comment]
I haven't looked the details yet and I don't recall the details with the version file. However, there's probably at least 2 bugs here. You shouldn't be able to create a jail that is lacking required metadata, and bulk shouldn't silently crash if that metadata is missing.

**Comment by trombonehero** [comment]
It looks like this file is maybe expected to contain the output of `uname -r`? It also looks like `poudriere jail -c` may be removing the `login.conf` changes I made manually to add `UNAME_r`... is that field meant to be filled using Poudriere's `-v` option?

**Comment by bdrewery** [comment]
If the jail has a /usr/src then it determines the version automatically. Otherwise `-v` is expected.
/etc/login.conf in the jail path is auto updated to set `UNAME_r` based on that and is reverted later with `jail -d`. I had wanted to fix `-m null` to not modify the jail path at all eventually. I think I'll do that for this bug too.

**Comment by bdrewery** [comment]
The regression came from commit 7d91ef45105d531d36236f2d1cdaa3a6a8ef9d6b

**Comment by bdrewery** [comment]
Thanks fixed.

**Comment by bdrewery** [comment]
FYI in commit bcda4cf990d0f4061e017e1f267491d97fafe6d9 (only scheduled for poudriere-devel for now) I fixed 'jail -c -m null' to not modify /etc/login.conf. Though it does still force the same change during bulk startup in the cloned jail. At least now it won't modify something it doesn't own.

**Comment by trombonehero** [comment]
Fantastic. Thanks!
