### ISSUE TITLE
Rebuild packages on vulnerability

### ISSUE THREAD

**Issue by marceloneil** [freebsd/poudriere#680]
It would be useful to rebuild packages or a specific package when a vulnerability is discovered in VuXML (https://www.vuxml.org/freebsd/)

**Comment by dlangille** [comment]
After the vuln is patched, PORTVERSION will be bumped.

This will automatically trigger a build the next time a bulk is run.

If you run bulk every day, what you are asking for will happen.

Do I misunderstand the request?

**Comment by marceloneil** [comment]
It was more to have a vuln trigger a build, in the case where you run bulk builds less often (like FreeBSD does).

**Comment by dlangille** [comment]
It's not the vuln which should trigger a build, it's the fix to the vuln.

**Comment by marceloneil** [comment]
Sorry that's what I meant! Maybe this would be better solved with some sort of periodic script that checks for vulnerabilities and if there is an updated PORTVERSION it can trigger a rebuild.

**Comment by dlangille** [comment]
I would just run bulk every night.

Only the ports with updates will be rebuilt.

If you want something sooner, run every N hours.  No work is done if there is nothing new to build.
