### ISSUE TITLE
bulk builds: add option to prevent network access during fetch stage

### ISSUE THREAD

**Issue by mulander** [freebsd/poudriere#689]
Is there a way to prevent the builders from fetching any distfiles?

Currently two jails are created for building packages. One with networking access (for the fetch stage and for packages listed in ALLOW_NETWORKING_PACKAGES) and another one with no network access for regular builds.

Currently when running bulk builds, any missing distfiles are automatically fetched over the network. Instead I would like the build to fail if a distfile is not present.

I plan to implement this feature and submit it as a pull request.

**Comment by bdrewery** [comment]
👍 
In `injail` and `injail_tty` you would just put something like:
```
if [ "${DISALLOW_NETWORKING}" ]; then
    local JNETNAME=
fi
```
```

**Comment by mulander** [comment]
Thanks! I tested, documented and submitted this suggestion in #689.
