### ISSUE TITLE
mounting nullfs file systems in read-only mode conflicts with MUTABLE_BASE="yes".

### ISSUE THREAD

**Issue by bu7cher** [freebsd/poudriere#695]
https://github.com/freebsd/poudriere/blob/75dc18ca6ac915f4689e227f867cda129ce1db36/src/share/poudriere/common.sh#L1590

**Comment by bdrewery** [comment]
Yes by default `nullpaths="/rescue /usr/share /usr/tests /usr/lib32"` is used no matter what as read-only.

This hit me at work as well since we were trying to write to _/usr/lib32_. We had to patch it out there.
