### ISSUE TITLE
openjdk8-8.212.4.1 fails to build, configure error

### ISSUE THREAD

**Issue by Hagabard** [freebsd/poudriere#696]
openjdk8 won't build in poudriere, failes to pass configure for Java.  It does seem to build the bootstrap and it exists but I suspect it cannot run.  It may be related to bootstrap-openjdk8:
======================================================================

WARNING: This port only exists for bootstrapping java/openjdk8.
You are advised to remove this port as soon as a stable JDK is built.

This OpenJDK implementation requires fdescfs(5) mounted on /dev/fd and
procfs(5) mounted on /proc.

If you have not done it yet, please do the following:

        mount -t fdescfs fdesc /dev/fd
        mount -t procfs proc /proc

To make it permanent, you need the following lines in /etc/fstab:

        fdesc   /dev/fd         fdescfs         rw      0       0
        proc    /proc           procfs          rw      0       0

======================================================================

`=======================<phase: configure      >============================
===>  Configuring for openjdk8-8.212.4.1
Warning: You are using legacy autoconf cross-compilation flags.
It is recommended that you use --openjdk-target instead.

Running generated-configure.sh
configure: loading site script /usr/ports/Templates/config.site
configure: Configuration created at Fri May 31 19:09:54 UTC 2019.
configure: configure script generated at timestamp 1553405262.
checking for basename... /usr/bin/basename
checking for bash... /usr/local/bin/bash
checking for cat... /bin/cat
checking for chmod... /bin/chmod
checking for cmp... /usr/bin/cmp
checking for comm... /usr/bin/comm
checking for cp... /bin/cp
checking for cut... /usr/bin/cut
checking for date... /bin/date
checking for gdiff... no
checking for diff... /usr/bin/diff
checking for dirname... /usr/bin/dirname
checking for echo... /bin/echo
checking for expr... /bin/expr
checking for file... /usr/bin/file
checking for find... /usr/bin/find
checking for head... /usr/bin/head
checking for ln... /bin/ln
checking for ls... /bin/ls
checking for mkdir... /bin/mkdir
checking for mktemp... /usr/bin/mktemp
checking for mv... /bin/mv
checking for nawk... /usr/bin/nawk
checking for printf... /usr/bin/printf
checking for rm... /bin/rm
checking for sh... /bin/sh
checking for sort... /usr/bin/sort
checking for tail... /usr/bin/tail
checking for tar... /usr/bin/tar
checking for tee... /usr/bin/tee
checking for touch... /usr/bin/touch
checking for tr... /usr/bin/tr
checking for uname... /usr/bin/uname
checking for uniq... /usr/bin/uniq
checking for wc... /usr/bin/wc
checking for which... /usr/bin/which
checking for xargs... /usr/bin/xargs
checking for gawk... (cached) /usr/bin/awk
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for egrep... (cached) /usr/bin/egrep
checking for fgrep... (cached) /usr/bin/fgrep
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for cygpath... no
checking for greadlink... no
checking for readlink... /usr/bin/readlink
checking for df... /bin/df
checking for SetFile... no
checking for cpio... /usr/bin/cpio
checking build system type... amd64-portbld-freebsd11.2
checking host system type... amd64-portbld-freebsd11.2
checking target system type... amd64-portbld-freebsd11.2
checking openjdk-build os-cpu... bsd-x86_64
checking openjdk-target os-cpu... bsd-x86_64
checking compilation type... native
checking for top-level directory... /wrkdirs/usr/ports/java/openjdk8/work/openjdk-jdk8u-jdk8u212-b04.1
checking for presence of closed sources... no
checking if closed source is suppressed (openjdk-only)... no
checking which variant of the JDK to build... normal
checking which interpreter of the JVM to build... template
checking which variants of the JVM to build... server
checking which debug level to use... release
checking for sysroot... 
checking for toolchain path... 
checking for extra path... 
checking where to store configuration... in default location
checking what configuration name to use... bsd-x86_64-normal-server-release
checking for apt-get... no
checking for yum... no
checking for port... no
checking for pkgutil... no
checking for pkgadd... no
configure: Testing potential make at /usr/local/bin/gmake, found using user supplied MAKE=/usr/local/bin/gmake
configure: Using GNU make 3.81 (or later) at /usr/local/bin/gmake (version: GNU Make 4.2.1)
checking if find supports -delete... yes
checking for unzip... /usr/bin/unzip
checking for zip... /usr/local/bin/zip
checking for ldd... /usr/bin/ldd
checking for readelf... /usr/bin/readelf
checking for hg... no
checking for stat... /usr/bin/stat
checking for time... /usr/bin/time
checking pkg-config is at least version 0.9.0... yes
checking for 7z... no
checking for unzip... unzip
checking for wget... no
checking for lftp... no
checking for ftp... ftp
checking headful support... headless only
configure: Found potential Boot JDK using configure arguments
configure: Potential Boot JDK found at /usr/local/bootstrap-openjdk8 is incorrect JDK version (Error occurred during initialization of VM); ignoring
configure: (Your Boot JDK must be version 7 or 8)
configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
configure exiting with result code 1
===>  Script "../../configure" failed unexpectedly.
Please report the problem to java@FreeBSD.org [maintainer] and attach the
"/wrkdirs/usr/ports/java/openjdk8/work/openjdk-jdk8u-jdk8u212-b04.1/common/autoconf/config.log"
including the output of the failure of your make command. Also, it might be
a good idea to provide an overview of all packages installed on your system
(e.g. a /usr/local/sbin/pkg-static info -g -Ea).
*** Error code 1

Stop.
make: stopped in /usr/ports/java/openjdk8
=>> Cleaning up wrkdir
===>  Cleaning for openjdk8-8.212.4.1
build of java/openjdk8 | openjdk8-8.212.4.1 ended at Fri May 31 12:09:57 PDT 2019
build time: 00:00:53
!!! build failure encountered !!!

At this point I restarted building my set with -i interactive, was able to cd to /usr/ports/java/openjdk8 and it passes configure and compiles no problem  For a work around to ublock the things requiring java, I did a make package.  It failed to copy.
===>  Building package for openjdk8-8.212.4.1
cp: /packages/All/openjdk8-8.212.4.1.txz: Read-only file system
So I just copied it from outside to the packages/All directory and was able to move on with my builds.

Initial guesses as to why it may not be able to run the bootstrap jdk for me were maybe the procfs and fdescfs mounts weren't set until it failed and dropped to interactive shell, but the fact that I can build in interactive but not in bulk seems like it is some kind of bug.

Also included is ports list I am building.

[11-2x64.ports.txt](https://github.com/freebsd/poudriere/files/3243189/11-2x64.ports.txt)

**Comment by Hagabard** [comment]
Full build log

[build.log.txt](https://github.com/freebsd/poudriere/files/3243199/build.log.txt)

**Comment by Hagabard** [comment]
Yes, I still have the same issue, I have to run the batch in manual mode
whenever a java update comes up. I go to openjdk8 and make pkg (which does
not have a configure error) and manually copy out of jail. Then batch works
with everything else.

**Comment by skitchin** [comment]
I'm having the same issue.  Was there any update on poudriere's fix on this problem?

**Comment by Hagabard** [comment]
Still happening. For now the interactive workaround is working, I don't
know if there is a true fix yet.

**Comment by skitchin** [comment]
Did you read my edited post in the thread about customized GENERIC?

**Comment by Hagabard** [comment]
I replied to email that (oddly) did not include that, sorry. I don't think
I am running a modified GENERIC file, but I could be on a custom kernel
still. Most of my FreeBSD installs have been stock kernels for some time
now, but this server may still be an exception to that. I will investigate
the kernel further and get back to you.

**Comment by Hagabard** [comment]
We were running a GENERIC kernel so I don't know what was up but after we upgraded to FreeBSD 11.3 it builds without intervention now.
