### ISSUE TITLE
is poudriere image (poudriere-devel) meant to work?

### ISSUE THREAD

**Issue by ivr588** [freebsd/poudriere#704]
Hii,

I have a 12.0-release mips.mips64 poudriere jail. I want to make a bootable image and have been failing with -t usb so I tried -t rawdisk like this:

poudriere image -h router -j 120R-mips64 -n erl3 -o /root/img -t rawdisk -s 4g

it fails like this:

>>> Old libraries removed
mv: /usr/local/poudriere/data/images/erl3-9ken/world/etc/login.conf.orig: No such file or directory
[01:02:20] Error while create image. cleaning up.
mdconfig: ioctl(/dev/mdctl): Device busy

A similar error happens with -t usb

As the man page says poudriere image is ALPHA, is it expected right now to work at all? The version is poudriere-devel-3.3.99.20190803 and it's running on 12-stable r350629

**Comment by bdrewery** [comment]
#685 will fix this.
