### ISSUE TITLE
incorrect error message when BASEFS does not exist

### ISSUE THREAD

**Issue by emaste** [freebsd/poudriere#714]
I ran `poudriere jail -c` and got the following error:
`[00:00:00] Error: Please provide a BASEFS variable in your poudriere.conf`
however I did have a BASEFS variable in poudriere.conf (the default /usr/local/poudriere), but the directory didn't exist

**Comment by bdrewery** [comment]
This error is only shown (in 2 places) if BASEFS is empty.
`[ -z ${BASEFS} ] && err 1 "Please provide a BASEFS variable in your poudriere.conf"`
I don't see how it could fire if not empty.

**Comment by emaste** [comment]
From common.sh `BASEFS=$(realpath "${BASEFS}")

**Comment by bdrewery** [comment]
Your second comment about `realpath` is something I hit at work this week as well. There's a regression here because an earlier version apparently did `mkdir -p $BASEFS` but now assumes it exists, doesn't hide the error, and doesn't give a clear error about it.
At work we had this that caused some very obscure failures with `jail -c`:
poudriere.conf:
```
BASEFS=/p
```
```
% poudriere jail -c ...
realpath: /p: No such file or directory
```

**Comment by emaste** [comment]
Sorry I wasn't trying to be cryptic, I just found the way BASEFS was being sent after your comment and should have provided additional information.

realpath gives a warning on stderr if the path does not exist:
```
% realpath /does/not/exist
realpath: /does/not/exist: No such file or directory
```

but I guess stderr is redirected here along the lines of
```
% cat foo.sh
#!/bin/sh
exec 2>/dev/null
P=$(realpath /does/not/exist)
echo $P
% sh foo.sh

%
```

**Comment by bdrewery** [comment]
Related issue https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240118

**Comment by woodsb02** [comment]
I find this is fixed if I revert these 2 changes (so I assume they caused this regression):
https://github.com/freebsd/poudriere/commit/681c63f075ab411018a19f3139b25f155f46eeaf
https://github.com/freebsd/poudriere/commit/f065e9450add8bf33e8c792c52429bb789423c96

**Comment by woodsb02** [comment]
My experience with this issue is that it blocks first time setup of a new poudriere machine. My "poudriere  jail -c" command was failing entirely due to this issue.

Reverting the above 2 changes does not entirely fix the issue - the jail creation will proceed, but 2 of the zfs datasets get mounted in the wrong location under /zroot/poudriere/ whilst the rest all get correctly mounted under /usr/local/poudriere/:
- zroot/poudriere
- zroot/poudriere/jails

/usr/local/etc/poudriere.conf (relevant settings):
```
ZPOOL=zroot
ZROOTFS=/poudriere
BASEFS=/usr/local/poudriere
```

The command output:
```
# poudriere  jail -c -j 12amd64 -v 12.1-RELEASE
realpath: /usr/local/poudriere: No such file or directory
[00:00:00] Error: Please provide a BASEFS variable in your poudriere.conf

# zfs list
NAME                            USED  AVAIL  REFER  MOUNTPOINT
zroot                          2.02G   150G    88K  /zroot
zroot/ROOT                      721M   150G    88K  none
zroot/ROOT/default              720M   150G   720M  /
zroot/poudriere                 712K   150G    88K  /zroot/poudriere
zroot/poudriere/data            624K   150G    96K  /data
zroot/poudriere/data/.m          88K   150G    88K  /data/.m
zroot/poudriere/data/cache       88K   150G    88K  /data/cache
zroot/poudriere/data/images      88K   150G    88K  /data/images
zroot/poudriere/data/logs        88K   150G    88K  /data/logs
zroot/poudriere/data/packages    88K   150G    88K  /data/packages
zroot/poudriere/data/wrkdirs     88K   150G    88K  /data/wrkdirs
```

**Comment by woodsb02** [comment]
I can manually work around this issue if I run these commands before the first time I try to setup poudriere:

```
# zfs create -o compression=lz4 -o atime=off -o mountpoint=/usr/local/poudriere zroot/poudriere
# zfs create zroot/poudriere/jails
# zfs create zroot/poudriere/ports
```

**Comment by emaste** [comment]
> My experience with this issue is that it blocks first time setup of a new poudriere machine.

Yes, this is how I encountered it.

**Comment by bdrewery** [comment]
> I find this is fixed if I revert these 2 changes (so I assume they caused this regression):
> [681c63f](https://github.com/freebsd/poudriere/commit/681c63f075ab411018a19f3139b25f155f46eeaf)
> [f065e94](https://github.com/freebsd/poudriere/commit/f065e9450add8bf33e8c792c52429bb789423c96)

That helped, thank you.
