### ISSUE TITLE
Options depending of flavor

### ISSUE THREAD

**Issue by kuPyxa** [freebsd/poudriere#734]
Hi.

I cannot build devel/py-virtualenv of 16.7.5 version with python 2.7. My make.conf:

`DEFAULT_VERSIONS+= python=2.7 python2=2.7 python3=3.7`

Logs:

`
===>   py27-virtualenv-16.7.5 depends on package: py27-towncrier>0 - found`                                                                                                              
`===>   Returning to build of py27-virtualenv-16.7.5       `                                                                                                                              
`===>   py27-virtualenv-16.7.5 depends on package: py27-pathlib2>0 - not found `                                                                                                          
`===>   py27-virtualenv-16.7.5 depends on package: /packages/All/py27-pathlib2-2.3.5.txz - not found       `                                                                              
`===>   USE_PACKAGE_DEPENDS_ONLY set - not building missing dependency from source                                                                                                       
*** Error code 1                                                                                                                                                                        
`

Could you explain what I do wrong? Except using python 2.7 )

**Comment by kuPyxa** [comment]
Maybe problem in this section of port:

`.if ${FLAVOR:U:Mpy27}        `                                                                                                                                                       
`DOCS_BUILD_DEPENDS+=<-->${PYTHON_PKGNAMEPREFIX}pathlib2>0:devel/py-pathlib2@${PY_FLAVOR}     `                                                                                           
`.endif                                                                                                                                                                                  
`

**Comment by kuPyxa** [comment]
You need adding this string before:

`.include <bsd.port.pre.mk>`

**Comment by bdrewery** [comment]
Yes it is wrong for a port to use `FLAVOR:U` anywhere. I keep trying to convince other porters of this.
