### ISSUE TITLE
"Cannot rollback ....: there is a snapshot ... more recent than...

### ISSUE THREAD

**Issue by hartzell** [freebsd/poudriere#743]
I'm using poudriere to build the set of I use.  It's been working since early summer, 2018.  The system is running 12.1-RELEASE-p2.

I recently (Feb 4) started getting an error about not being able to rollback a particular builder's storage.  I asked freebsd-questions about (https://lists.freebsd.org/pipermail/freebsd-questions/2020-February/287685.html), didn't hear anything.

The only potentially related thing I can think of to mention is that, as part of that build I managed to fill up the pool.  I've cleaned it up.

As part of my up{date,grades} on Feb 4, I updated to poudriere-3.3.3 and/but am still seeing the problem:

```
[00:02:53] [02] [00:00:00] Building security/pinentry | pinentry-1.1.0_6
cannot rollback 'zroot/poudriere/jails/12_1-ports_and_hartzell-ref/02': there is a snapshot or bookmark more recent than 'zroot/poudriere/jails/12_1-po
rts_and_hartzell-ref/02@prepkg'
[00:02:54] [02] [00:00:01] Error: Unable to rollback zroot/poudriere/jails/12_1-ports_and_hartzell-ref/02 to prepkg
=>> Error: Unable to rollback zroot/poudriere/jails/12_1-ports_and_hartzell-ref/02 to prepkg
[00:02:59] [01] [00:00:15] Finished security/libksba | libksba-1.3.5_1: Success
```

The same port builds successfully on the next run.

**Comment by bdrewery** [comment]
Does this still happen for you or was it just the one time?

**Comment by hartzell** [comment]
I'm sorry I didn't follow up here.  Miroslav Lachman, on the [freebsd-ports-mailing-list], suggested that it might be related to periodic snapshots that I was making (via sanoid, in my case).

While I haven't proven it, I'm comfortable with the hypothesis.  I only do rebuilds when there's a security report that touches the things that I use, it'll be easy enough to just pause my snapshots during the build.

I should close this, unless you want to hold it open for some reason.  Thanks!



[freebsd-ports-mailing-list]: https://lists.freebsd.org/pipermail/freebsd-ports/2020-March/117986.html

**Comment by bdrewery** [comment]
Well we do already use `zfs destroy -r` so I'm surprised by this. `-R` is stronger but destroys clones which shouldn't be an issue here.

Perhaps it is a race in the ZFS code for handling snapshots with both of these happening at the same time:
1. Snapshot created
2. @prepkg destroyed

If you can try to exclude the /usr/local/poudriere/data/.m directory from snapshots. The sysutils/zfstools package (which I wrote) can do that at least.
```
NAME                     PROPERTY               VALUE                  SOURCE
zroot/poudriere/data/.m  com.sun:auto-snapshot  false                  received
```
