### ISSUE TITLE
poudriere no longer deletes forbidden or removed packages during bulk -a

### ISSUE THREAD

**Issue by ant1** [freebsd/poudriere#747]
This is a security issue.

**Comment by bdrewery** [comment]
But it shouldn't. That's the end phase with `make clean-restricted`. `bulk -R` does this. If something is broken there it's the ports framework.

The only potential issue here is building something that gets deleted at the end.

**Comment by ant1** [comment]
Restricted is different from forbidden.
And what about ports that no longer exist but the package is still kept

**Comment by bdrewery** [comment]
> Restricted is different from forbidden.

Which `make <target>` should I call instead?

Are FLAVORS handled in these calls?

As for deleted ports `poudriere pkgclean` should be used. You could do this before calling the repo publish command.

**Comment by bdrewery** [comment]
FORBIDDEN only sets an IGNORE. Running the old code it never tried anything with a port unless there was a new version or changed dep, etc. The addition of an IGNORE or FORBIDDEN did not cause a package to be deleted by default. It would however be deleted if there was also a PORTREVISION bump or other reason to rebuild it. I think this is a gap from day 1 with Poudriere.

With the new IGNORE handling it is much simpler to always delete a newly FORBIDDEN package.

**Comment by bdrewery** [comment]
```
r527808 | antoine | 2020-03-04 22:43:52 -0800 (Wed, 04 Mar 2020) | 2 lines

Bump after FORBIDDEN
```

I see you have been dealing with that bug by bumping the version. I will fix this to not require the version bump.

**Comment by bdrewery** [comment]
I've fixed *master* to delete FORBIDDEN always now regardless of version bumps.
```
[00:00:25] [Dry Run] Deleting smartmontools-7.0_2.txz: is forbidden: foo
```

**Comment by bdrewery** [comment]
This is now all addressed in master.
