### ISSUE TITLE
Repository metadata can't be read by jail pkg

### ISSUE THREAD

**Issue by rbgarga** [freebsd/poudriere#748]
Builder has pkg 1.13.2 and ports tree used by poudriere has 1.12.x.  Repository created by `poudriere bulk` has meta version 2 and can't be read by pkg 1.12.x.

After look into `ensure_pkg_installed()` I noted the following code, which would explain the problem for crossbuild.

```shell
	if [ ${QEMU_EMULATING} -eq 1 ] && \
	    [ -f /usr/local/sbin/pkg-static ]; then
		cp -f /usr/local/sbin/pkg-static "${mnt}/.p/pkg-static"
		return 0
	fi
```

Unfortunately it's not my case, it happened to me with amd64.  I'm using poudriere 3.3.3.

**Comment by bdrewery** [comment]
@bapt any comment?

**Comment by rbgarga** [comment]
Oh! I forgot to mention the problem is specific with crossbuild for arm, I was unable to reproduce it on amd64 again.  I understand the host pkg-static help to speed up the build process but it would be nice to have an option to don't  use it or an option to make a modern pkg binary to create a repository with meta version 1
