### ISSUE TITLE
Duplicated -[ilnskr] commands in poudriere-jail(8)

### ISSUE THREAD

**Issue by pauamma** [freebsd/poudriere#762]
-i           Show information about a jail.  See also
                  poudriere-status(8).

     -l           List all poudriere jails.

     -n           When combined with -l, only display jail name.

     -s           Starts a jail.

     -k           Kills a jail (stops it).

     -r name      Rename a jail to name.

     -i           Show information about a jail.  See also
                  poudriere-status(8).

     -l           List all poudriere jails.

     -n           When combined with -l, only display jail name.

     -s           Starts a jail.

     -k           Kills a jail (stops it).

     -r name      Rename a jail to name.

     -u           Update a jail.

**Comment by bdrewery** [comment]
I'm not seeing this. Which release/package is your Poudriere?

**Comment by pauamma** [comment]
> % pkg info poudriere
> poudriere-3.3.4
> Name           : poudriere
> Version        : 3.3.4
> Installed on   : Tue Jun 16 21:35:35 2020 UTC
> [...]

I just checked and I no longer see it. 4 months later, I'm unable to say whether it was my imagination or an artifact of some component of the software chain I was using to talk to that VM.  Either way, sorry for the noise and thanks for checking.
