### ISSUE TITLE
Metadata gathering is slow

### ISSUE THREAD

**Issue by myfreeweb** [freebsd/poudriere#763]
```
[00:01:48] Gathering ports metadata
[00:06:20] Calculating ports order and dependencies
```

Admittedly the above is over NFSv4 (SSD mirror, 10GbE) but it wasn't that much faster when I had the ports on the local NVMe drive.

- maybe this shouldn't be done in a single threaded shell script..
- would it be possible to cache the gathered metadata between runs?

**Comment by bdrewery** [comment]
> maybe this shouldn't be done in a single threaded shell script..

It's not single threaded. How many CPU do you have?

```
[00:00:03] [Dry Run] Gathering ports metadata
[00:01:39] [Dry Run] Calculating ports order and dependencies
```
It's quite fast for me. It's been where most of my attention wrongly ends up.

> would it be possible to cache the gathered metadata between runs?

Potentially yes.

**Comment by myfreeweb** [comment]
I was referring to this comment:

https://github.com/freebsd/poudriere/blob/c177f2333dbfdfc5f40a81c308418f723e23cfee/test/common.bulk.sh#L22

Though looking more carefully (not while being too tired :D) this is in some `test` code, not relevant. \*facepalm\* sorry.

I have 16 (half of which are SMT threads). This seems I/O bound though, especially with NFS.

**Comment by bdrewery** [comment]
Yes it is definitely IO bound as it is traversing the entire ports tree. 30 whatever thousand ports each loading dozens of other files. Warming up the cache of these files can help. NFS caching never works right for me.

Sorry I don't think this is an issue that can be fixed in Poudriere.
