### ISSUE TITLE
Off-by-one error of color change in output of `bulk` and `testport` command

### ISSUE THREAD

**Issue by yasuhirokimura** [freebsd/poudriere#767]
OS: FreeBSD 12.1-RELEASE amd64
Poudriere: 3.2.4

There is off-by-one error of color change in output of `bulk` and `testport` command. It happens in line that reports build of one package is completed. Attached file is screenshot of poudriere output
on system cosole.

![poudriere off-by-one-error](https://user-images.githubusercontent.com/5249848/89742868-a4bf1a00-dad8-11ea-9e28-fd17a40e38b2.png)

Let's look at the line that reports build of `ports-mgmt/pkg` has completed.  The color of this line changes as following.

```
123456789012345678901234567890123456789012345678901234567890123456789012
[00:01:05] [01] [00:00:50] Finished ports-mgmt/pkg | pkg-1.14.6: Success
GGGGGGGGGGKGRRWKWWWWWWWWWWKGGGGGGGGKBBBBBBBBBBBBBBKBKBBBBBBBBBBBKGGGGGGG
```

Where,

W: white
R: red
G: green
B: blue
K: black

The error happens at 12th character from left ('['). Its color is green but probably should be white. Same error happens on every line that ports build of one package is completed.

**Comment by yasuhirokimura** [comment]
I investigated the code and found there is bug in line 121 of `src/share/poudriere/common.sh`. That is,

```shell
                printf "${COLOR_ARROW}${elapsed}${DRY_MODE-}${arrow:+${COLOR_ARROW}${arrow}${COLOR_RESET} }${*}${COLOR_RESET}${NL}"
```

But how it should be fixed depends on what color is used to write the value of `${elapsed}`. If default color should be used, then this line should be changed as following.

```shell
                printf "${elapsed}${DRY_MODE-}${arrow:+${COLOR_ARROW}${arrow}${COLOR_RESET} }${*}${COLOR_RESET}${NL}"
```

And if `${COLOR_ARROW}` should be used. then it should be changed as following.

```shell
                printf "${COLOR_ARROW}${elapsed}${COLOR_RESET}${DRY_MODE-}${arrow:+${COLOR_ARROW}${arrow}${COLOR_RESET} }${*}${COLOR_RESET}${NL}"
```

**Comment by yasuhirokimura** [comment]
Considering the result of comparing lines 121 and 123, it is inferred that the value of the variable `elapsed` should be displayed in the default color. So line 123 should be fixed as the former of previous comment.

**Comment by bdrewery** [comment]
> Considering the result of comparing lines 121 and 123, it is inferred that the value of the variable `elapsed` should be displayed in the default color. So line 123 should be fixed as the former of previous comment.

The elapsed is intended to be the COLOR_ARROW value. Your title was accurate: it's off by **1** not all of elapsed. It's a problem specific to being called from `job_msg` I think.

The COLOR_ARROW value is misnamed, should be like COLOR_STATUS, and is only used for result lines. It is inconsistent that it doesn't highlight the 2nd job elapsed value too but I don't think it's worth fixing that.

I think this is what we want:
```
diff --git src/share/poudriere/common.sh src/share/poudriere/common.sh
index 66cc298c3..5ea1eea66 100644
--- src/share/poudriere/common.sh
+++ src/share/poudriere/common.sh
@@ -125,7 +125,7 @@ _msg_n() {
                arrow="=>>"
        fi
        if [ -n "${COLOR_ARROW}" ] || [ -z "${1##*\033[*}" ]; then
-               printf "${COLOR_ARROW}${elapsed}${DRY_MODE-}${arrow:+${COLOR_ARROW}${arrow}${COLOR_RESET} }%b${COLOR_RESET}${NL}" "$*"
+               printf "${COLOR_ARROW}${elapsed}${DRY_MODE-}${arrow:+${COLOR_ARROW}${arrow} }${COLOR_RESET}%b${COLOR_RESET}${NL}" "$*"
        else
                printf "${elapsed}${DRY_MODE-}${arrow:+${arrow} }%b${NL}" "$*"
        fi
```

Which is moving the COLOR_RESET out of the arrow expansion.
```
${arrow:+${COLOR_ARROW}${arrow}${COLOR_RESET} }
```
->
```
${arrow:+${COLOR_ARROW}${arrow} }${COLOR_RESET}
```

**Comment by yasuhirokimura** [comment]
I understand. I'll update #768
