### ISSUE TITLE
test/locked_mkdir.sh fails

### ISSUE THREAD

**Issue by backerman** [freebsd/poudriere#789]
Observed on FreeBSD 12.1-RELEASE-p10 and 11.3-RELEASE-p14 (both amd64) with current poudriere master.

```
FAIL: locked_mkdir.sh
=====================

Using SH=/home/bsa3/src/poudriere/sh
[00:00:00] getpid: 94880
[00:00:07] /usr/home/bsa3/src/poudriere/test/locked_mkdir.sh:104: Lock should not succeed: expected: '75$', actual: '0$'
FAIL locked_mkdir.sh (exit status: 45)
```

**Comment by bdrewery** [comment]
Thanks. The test is racy.

Regards,
Bryan Drewery

**Comment by bdrewery** [comment]
I have a lot of pending work to improve this to be less racy. I'm going to forget this issue exists here but am fully aware of the problem so going to close this.
