### ISSUE TITLE
Request: option to automatically retry crashed builds

### ISSUE THREAD

**Issue by dag-erling** [freebsd/poudriere#791]
Background: I use zfSnap to take automatic snapshots of my entire pool every hour on the hour. The same job also scans and deletes old snapshots. In FreeBSD 11, this worked perfectly, but in FreeBSD 12, there appears to be some sort of race condition which can result in poudriere failing to roll back the jail if it tries to start a build while the zfSnap delete job is running.

Could you add an option to automatically retry crashed builds (any build listed as `crashed` or `???` in the web UI) up to N times, for a configurable value of N which defaults to 0?

EDIT: [here's an example](https://pkg.des.no/logs/build.html?mastername=121amd64-default&build=2020-10-21_05h56m03s).

**Comment by swills** [comment]
I use sysutils/zfstools for a similar thing but don't see issues. Maybe that would work for you? Just a suggestion.

**Comment by dag-erling** [comment]
Presumably, zfstools works better because it only snapshots datasets with a specific property set, and that property isn't set on poudriere jails. The bug is still there, you just don't notice it. But even then, this is still a valuable addition, as there might be other issues that could cause a job to fail temporarily

**Comment by brd** [comment]
The zfSnap wiki recommends running with `-d` on a once a day or less.  See this page [zfs wiki](https://github.com/zfsnap/zfsnap/wiki/zfSnap), under 'Delete old snapshots'.

I wonder if this is more of a ZFS problem? i.e. should it try again or wait for a lock to be released?

**Comment by dag-erling** [comment]
Poudriere already retries the zfs operation, I think. It's been a while, but when I first looked into the issue (including diving into the kernel) the only conclusion I was able to reach was “it _should_ work, but it doesn't...”

As for running “once a day or less”, that doesn't really help when a poudriere run takes 25 hours to complete.

**Comment by bdrewery** [comment]
I've been seeing this on my head system lately. Failure to rollback snapshots in Poudriere. I believe it's a ZFS regression. But I do think it makes sense to at least try rolling back a few times rather than immediately give up. That's simpler for now than making the entire package rebuild as that gets into a lot of metadata weeds for the web ui and poudriere-status.

**Comment by bdrewery** [comment]
Also the linked build reminds me that we really need bulk operations logged. That link shows a bunch of crashed builds with no explanation as to why.

**Comment by dag-erling** [comment]
The crashed builds are almost all due to zfs, but there are also two `mkdir: /.npkg/All: No such file or directory`, one reported as “makefile” and one reported as “???”. I don't know what that means.

**Comment by bdrewery** [comment]
The main issue here with zfs rollbacks should be fixed by commit 97924e46c69c33314446b0b3b79789a1f532ebff
