### ISSUE TITLE
how to use poudriere to (only??) build pkgbase

### ISSUE THREAD

**Issue by igalic** [freebsd/poudriere#809]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version? (I'm running git HEAD) 
- [ ] Is your ports tree recent? (irrelevant to my question) 
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)? (yes, 
12.2)

## Describe the bug

i'm aware that this is a new and unreleased feature, 
as such it may be forgiven that it's undocumented, but i'd like to

use poudriere to (only??) build pkgbase

that doesn't seem to work.

## How to reproduce

read the Man pages, check help, search this repo, give up and try things out

i arrived at

```sh
$ poudriere jail -j base13 -B -K GENERIC -b -m src=/usr/src 
(prints usage)
```

frustratingly, this only prints the usage, but doesn't say why it's wrong. the reason is that I'm missing a "command", such as, 

```sh
$ poudriere jail -j base13 -s -B -K GENERIC -b -m src=/usr/src
[00:00:00] Error: No such ports tree default
```

so this now makes me believe that i can only achieve my goal of building pkgbase if i also build a port 

or??

## Expected behavior

- a clear indication when a "command" is missing
- documentation on how to build pkgbase
- the ability to build pkgbase without any ports

ideally, pkgbase(s?) should be a sub-command, like ports, where we can define pkgbase sets

## Environment
 - Host OS: 12.2 amd64
 - Jail OS 13.0 amd64
 - Poudriere Version: 2cb8ac847dd8cbce555f3d2a32c1e78f5d249ec4
 - Ports branch and revision: git HEAD

**Comment by evadot** [comment]
You need to create the jail saying that you want pkgbase : 
poudriere jail -c -j myjail -B -K GENERIC -b -m src=/usr/src should work but I've only tested with -m git
This will record in the jail settings that pkgbase is enabled (you can confirm with poudriere jail -i -j myjail)
pkgbase packages are available in the images subdirectory in /usr/local/poudriere/data/
If the jail have pkgbase enabled, packages will be recreated at each poudriere jail -u -j myjail
There shouldn't be a pkgbase subcommand, it's part of the jail build system in poudriere and should stay that way.
pkgbase "sets" are choosen via src.conf (WITH/WITHOUT).
Hope it answers you question.

**Comment by igalic** [comment]
as preparations are underway for my builds to [go public](https://codeberg.org/pkgbase/website/src/branch/main/index.md) i think we can close this issue now.
Thank you very much.
