### ISSUE TITLE
multiple kernels in jail's kernel file are not handled properly

### ISSUE THREAD

**Issue by igalic** [freebsd/poudriere#818]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [ ] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug

adding more than one kernel in the jail's kernel file (i pressume this also works by creating the jail -K "GENERIC GENERIC-NODEBUG" this isn't handled as a list, if it's handled at all: 
```
--- svnliterdump.debug ---
objcopy --only-keep-debug svnliterdump.full svnliterdump.debug
--- svnliterdump ---
objcopy --strip-debug --add-gnu-debuglink=svnliterdump.debug  svnliterdump.full svnliterdump
--- buildworld_epilogue ---
--------------------------------------------------------------
>>> World build completed on Wed Jan  6 03:58:42 UTC 2021
>>> World built in 24346 seconds, ncpu: 2, make -j2
--------------------------------------------------------------
[06:45:49] Starting make buildkernel with 2 jobs
--- buildkernel ---
make: make: don't know how to make GENERIC-NODEBUG. Stop

make: stopped in /poudriere/jails/pkgbase130-current-amd64/usr/src
```

## Expected behavior

I'd expect poudriere to either loop over the list, or call `KERNCONF="THE LIST"`

## Environment
 - Host OS: 13.0-CURRENT amd64
 - Jail OS: 13.0-CURRENT amd64 
 - Poudriere Version: 2cb8ac847

**Comment by igalic** [comment]
while i was distracted with chasing another issue, i didn't create a pull request for this in poudriere, but @kevans91 created one in base, which might be a better fix: https://reviews.freebsd.org/D28190

this ⬆️ ensures the packaging process will see the full set of kernels built with KERNCONF

**Comment by bdrewery** [comment]
For backwards compatibility, before that linked fix gets to everyone, we should probably set `NO_INSTALLEXTRAKERNELS=no`  when calling the make packages command. Like with `env` how I was talking about elsewhere.
```
env \
FOO=1 \
BAR=2 \
make ...
```

**Comment by igalic** [comment]
this is now fixed in master and can be closed now
