### ISSUE TITLE
Ability to build (not testport) a port with all cores

### ISSUE THREAD

**Issue by neelchauhan** [freebsd/poudriere#828]
## Prerequisites
- [X] Have you checked for an existing issue describing your idea?

## What is your proposal?

I want the ability to `build` (as opposed to `testport` a port with all cores dedicated to one port as an option. This could be the port specified by the `-o` option, or build ports sequentially like we do without Poudriere.

## What is the existing behavior, if any?

Even for large ports, we only give one core per package.

## What is the motivation / use case for the change?

This will make it quicker to build large dependencies (e.g. LLVM, GCC) on regular PCs like my AMD 3700X HP Omen, as opposed to needing 32/64/128-core package building machines.

## Did you consider any alternatives?

No. I'm not spending $5000 on an AMD Threadripper machine.

## Is this really a ports feature request?
<Poudriere is just a driver.  Most logic outside of _coordinating resource usage for building packages_ should be in Ports.>

No.

## Example
<If applicable add screenshots or mockups to demonstrate the feature.>

It could be an option like `-s` to `poudriere bulk` or `poudriere testport` that could build the final port, or all ports sequentially with all cores, instead of package/core.

## Additional context
<Add any other context about the feature request here.>

N/A (for now).

**Comment by brd** [comment]
Hi Neel!

Look for `ALLOW_MAKE_JOBS_PACKAGES` in poudriere.conf:

I use:
```
ALLOW_MAKE_JOBS_PACKAGES="pkg ccache py* llvm* openjdk* gcc*"
```

**Comment by devosalain** [comment]
It should spawn number of cores make processes or number of jobs make processes.
But it does not.
I think it does not work..

**Comment by bdrewery** [comment]
@devosalain which port? MAKE_JOBS is only significant during *build* phases, not extract, fetch, package, etc.
