### ISSUE TITLE
testport -c broken due to read-only mount

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#83]
I think I'm seeing a similar issue: a ports tree
is nullfs mounted read-only, hence:

=> SHA256 Checksum OK for pkg-1.1.4.tar.xz.
mkdir: /usr/ports/ports-mgmt/pkg/work: Read-only file system
*** Error code 1

More details:

# poudriere jail -l
JAILNAME             VERSION              ARCH    METHOD  PATH
ia64                 11.0-CURRENT         ia64    svn+https /pdr/jails/ia64
# poudriere ports -l
PORTSTREE            METHOD     PATH
default              svn+https  /pdr/ports/default

# poudriere testport -i -c -j ia64 -o ports-mgmt/pkg
====>> Creating the reference jail... done
*skip*
=> SHA256 Checksum OK for pkg-1.1.4.tar.xz.
mkdir: /usr/ports/ports-mgmt/pkg/work: Read-only file system
*** Error code 1

While the jail is still mounted:

# df -T
Filesystem                             Type    1K-blocks     Used     Avail Capacity  Mounted on
/dev/da0p2                             ufs      60931274 17261470  38795304    31%    /
devfs                                  devfs           1        1         0   100%    /dev
/dev/da0p1                             msdosfs    409504     1184    408320     0%    /efi
tank/poudriere/data                    zfs     137186297     3521 137182776     0%    /pdr/data
tank/poudriere/jails/ia64              zfs     139463583  2280807 137182776     2%    /pdr/jails/ia64
tank/poudriere/ports/default           zfs     138073349   890573 137182776     1%    /pdr/ports/default
tank                                   zfs     137182808       32 137182776     0%    /tank
tank/poudriere                         zfs     137182809       33 137182776     0%    /tank/poudriere
tank/poudriere/jails                   zfs     137182807       31 137182776     0%    /tank/poudriere/jails
tank/poudriere/ports                   zfs     137182807       31 137182776     0%    /tank/poudriere/ports
tank/poudriere/jails/ia64-default-ref  zfs     139465147  2282371 137182776     2%    /pdr/data/build/ia64-default/ref
devfs                                  devfs           1        1         0   100%    /pdr/data/build/ia64-default/ref/dev
tmpfs                                  tmpfs     9540384        8   9540376     0%    /pdr/data/build/ia64-default/ref/wrkdirs
/pdr/ports/default                     nullfs  138073349   890573 137182776     1%    /pdr/data/build/ia64-default/ref/usr/ports
/pdr/data/packages/ia64-default        nullfs  137186297     3521 137182776     0%    /pdr/data/build/ia64-default/ref/packages
/usr/ports/distfiles                   nullfs   60931274 17261470  38795304    31%    /pdr/data/build/ia64-default/ref/distfiles
tmpfs                                  tmpfs     9541160      784   9540376     0%    /pdr/data/build/ia64-default/ref/poudriere
# 

Note that /pdr/ports/default is mounted read-only:

# mkdir /pdr/data/build/ia64-default/ref/usr/ports/zzz
mkdir: /pdr/data/build/ia64-default/ref/usr/ports/zzz: Read-only file system
# 

And so is /pdr/data/packages/ia64-default:

# mkdir /pdr/data/build/ia64-default/ref/packages/zzz 
mkdir: /pdr/data/build/ia64-default/ref/packages/zzz: Read-only file system
# 

More details:

# zfs list
NAME                                    USED  AVAIL  REFER  MOUNTPOINT
tank                                   3.05G   131G    32K  /tank
tank/poudriere                         3.04G   131G    33K  /tank/poudriere
tank/poudriere/data                    3.44M   131G  3.44M  /pdr/data
tank/poudriere/jails                   2.19G   131G    31K  /tank/poudriere/jails
tank/poudriere/jails/ia64              2.19G   131G  2.18G  /pdr/jails/ia64
tank/poudriere/jails/ia64-default-ref  1.73M   131G  2.18G  /pdr/data/build/ia64-default/ref
tank/poudriere/ports                    870M   131G    31K  /tank/poudriere/ports
tank/poudriere/ports/default            870M   131G   870M  /pdr/ports/default
# 

# pkg info -xo poudr
poudriere-devel-3.0.99.20131019 ports-mgmt/poudriere-devel
#

**Comment by koobs** [comment]
I'm not sure yet to what extent this is related to this issue, but I've been recently experiencing lots of testport build dependency failures, which all seemed to be failing in the same way:

```
===>  Building package for indexinfo-0.2.2
env: /usr/local/sbin/pkg-static: No such file or directory
*** [do-package] Error code 1

and others:

===>  Building package for pkgconf-0.9.7
env: /usr/local/sbin/pkg-static: No such file or directory
*** [do-package] Error code 1
```
So I recreated my poudriere (poudriere-devel-3.1.1) and jail environments from scratch

```
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] sudo poudriere jail -l
    Password:
    JAILNAME VERSION        ARCH  METHOD TIMESTAMP           PATH
    93amd64  9.3-RELEASE-p9 amd64 ftp    2015-01-28 15:36:30 /usr/local/poudriere/jails/93amd64
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] sudo poudriere jail -d -j 93amd64
    [00:00:00] ====>> Removing 93amd64 jail... done
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] sudo poudriere jail -l
    JAILNAME VERSION ARCH METHOD TIMESTAMP PATH
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] df -h
    Filesystem                 Size    Used   Avail Capacity  Mounted on
    /dev/ada0p3                 14G     10G      3G    78%    /
    devfs                      1.0k    1.0k      0B   100%    /dev
    storage/home                26G     10G     15G    39%    /mnt/home
    storage                     15G     33k     15G     0%    /storage
    storage/poudriere           15G     33k     15G     0%    /storage/poudriere
    storage/poudriere/jails     15G     31k     15G     0%    /storage/poudriere/jails
    storage/poudriere/ports     15G     31k     15G     0%    /storage/poudriere/ports
    storage/usr                 15G     31k     15G     0%    /storage/usr
    storage/poudriere/data      15G     19M     15G     0%    /usr/local/poudriere/data
    storage/usr/ports           16G    590M     15G     4%    /usr/ports
    storage/usr/src             16G    852M     15G     5%    /usr/src
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] ls -la /usr/local/poudriere/data
    total 13
    drwxr-xr-x  7 root  wheel    7 Jan 28 15:38 ./
    drwxr-xr-x  5 root  wheel  512 Nov 16  2012 ../
    drwxr-xr-x  4 root  wheel    4 Jan 28 15:44 .m/
    drwxr-xr-x  2 root  wheel    2 Jan 28 22:37 cache/
    drwxr-xr-x  3 root  wheel    3 Jan 28 15:38 logs/
    drwxr-xr-x  4 root  wheel    4 Jan 28 15:44 packages/
    drwxr-xr-x  2 root  wheel    2 Jan 28 15:26 queue/
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] sudo rm -rf /usr/local/poudriere/data/*
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] ls -la /usr/local/poudriere/data
    total 7
    drwxr-xr-x  3 root  wheel    3 Jan 28 22:37 ./
    drwxr-xr-x  5 root  wheel  512 Nov 16  2012 ../
    drwxr-xr-x  4 root  wheel    4 Jan 28 15:44 .m/
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] sudo rm -rf /usr/local/poudriere/data/.m
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports] ls -la /usr/local/poudriere/data
    total 6
    drwxr-xr-x  2 root  wheel    2 Jan 28 22:37 ./
    drwxr-xr-x  5 root  wheel  512 Nov 16  2012 ../
    [user@9-STABLE-amd64:/usr/home/user/repos/freebsd/ports]
```
I am seeing issues with testport builds failing very early on dependent packages:

```
[user@9-STABLE-amd64:~] sudo poudriere testport -j 93amd64 -p user -o dns/ldns -c
Password:
[00:00:00] ====>> Creating the reference jail... done
[00:00:00] ====>> Mounting system devices for 93amd64-user
[00:00:00] ====>> Mounting ports/packages/distfiles
[00:00:00] ====>> Converting package repository to new format
[00:00:00] ====>> Stashing existing package repository
[00:00:00] ====>> Mounting packages from: /usr/local/poudriere/data/packages/93amd64-user
[00:00:00] ====>> Appending to make.conf: /usr/local/etc/poudriere.d/make.conf
/etc/resolv.conf -> /usr/local/poudriere/data/.m/93amd64-user/ref/etc/resolv.conf
[00:00:00] ====>> Starting jail 93amd64-user
===> Building/installing dialog4ports as it is required for the config dialog
===>  Cleaning for dialog4ports-0.1.5_2
===>  License BSD2CLAUSE accepted by the user
===>   dialog4ports-0.1.5_2 depends on file: /usr/local/sbin/pkg - not found
===>    Verifying install for /usr/local/sbin/pkg in /usr/ports/ports-mgmt/pkg
===>  License BSD2CLAUSE accepted by the user
===> Fetching all distfiles required by pkg-1.4.7 for building
===>  Extracting for pkg-1.4.7
===>  License BSD2CLAUSE accepted by the user
===> Fetching all distfiles required by pkg-1.4.7 for building
=> SHA256 Checksum OK for pkg-1.4.7.tar.xz.
===>  Patching for pkg-1.4.7
===>  Configuring for pkg-1.4.7

......<snip>.......

====> Compressing man pages (compress-man)
===>  Installing for pkg-1.4.7
===>  Checking if pkg already installed
===>   Registering installation for pkg-1.4.7
[93amd64-user] Installing pkg-1.4.7...
If you are upgrading from the old package format, first run:

  # pkg2ng

===>   Returning to build of dialog4ports-0.1.5_2
===> Fetching all distfiles required by dialog4ports-0.1.5_2 for building
===>  Extracting for dialog4ports-0.1.5_2
=> SHA256 Checksum OK for dialog4ports-0.1.5.tar.gz.
===>  Patching for dialog4ports-0.1.5_2
===>  Configuring for dialog4ports-0.1.5_2
===>  Building for dialog4ports-0.1.5_2

.......<snip>.......

===>  Staging for dialog4ports-0.1.5_2
===>   Generating temporary packing list
install -s -o root -g wheel -m 555   dialog4ports /wrkdirs/usr/ports/ports-mgmt/dialog4ports/work/stage/usr/local/bin/dialog4ports
install -o root -g wheel -m 444 dialog4ports.1.gz  /wrkdirs/usr/ports/ports-mgmt/dialog4ports/work/stage/usr/local/man/man1
====> Compressing man pages (compress-man)
===>  Installing for dialog4ports-0.1.5_2
===>  Checking if dialog4ports already installed
===>   Registering installation for dialog4ports-0.1.5_2
[93amd64-user] Installing dialog4ports-0.1.5_2...
===>  Cleaning for pkg-1.4.7
===>  Cleaning for dialog4ports-0.1.5_2

[00:00:42] ====>> Logs: /usr/local/poudriere/data/logs/bulk/93amd64-user/2015-01-28_22h52m23s
[00:00:42] ====>> Loading MOVED
[00:00:42] ====>> Calculating ports order and dependencies
[00:00:43] ====>> pkg package missing, skipping sanity
[00:00:43] ====>> Skipping incremental rebuild and repository sanity checks
[00:00:43] ====>> Cleaning the build queue
[00:00:43] ====>> Recording filesystem state for prepkg... done
[00:00:43] ====>> Building 5 packages using 4 builders
[00:00:43] ====>> Starting/Cloning builders
[00:00:44] ====>> Hit CTRL+t at any time to see build progress and stats
[00:00:44] ====>> [01][00:00:00] Starting build of ports-mgmt/pkg
[00:01:32] ====>> [01][00:00:48] Finished build of ports-mgmt/pkg: Success
[00:01:33] ====>> [01][00:00:00] Starting build of print/indexinfo
[00:01:33] ====>> [02][00:00:00] Starting build of lang/perl5.18
[00:01:37] ====>> [01][00:00:04] Finished build of print/indexinfo: Failed: package
[00:01:37] ====>> [01][00:00:04] Skipping build of devel/gmake: Dependent port print/indexinfo failed
[00:06:07] ====>> [02][00:04:34] Finished build of lang/perl5.18: Failed: package
[00:06:07] ====>> [02][00:04:34] Skipping build of security/openssl: Dependent port lang/perl5.18 failed
[00:06:07] ====>> Stopping 4 builders
[00:06:08] ====>> Error: Depends failed to build
[00:06:08] ====>> Failed ports: print/indexinfo:package lang/perl5.18:package
[00:06:08] ====>> Skipped ports: devel/gmake security/openssl
[00:06:08] ====>> Cleaning up
[00:06:08] ====>> Umounting file systems
[user@9-STABLE-amd64:~]
```
Another couple of data points:

antoine mentioned that -c shouldn't be used because it had a bug (this one), so I tried without -c, which worked (built all dependents for dns/ldns), and then tried with -c again, which worked.

I haven't experienced the *mkdir: /usr/ports/ports-mgmt/pkg/work: Read-only file system* errors.

**Comment by mat813** [comment]
`testport -c` is broken, there's a pull request for it.
