### ISSUE TITLE
poudriere, ccache and freebsd 13

### ISSUE THREAD

**Issue by mat813** [freebsd/poudriere#832]
## Describe the bug
Today I updated our package builder to the latest beta for 13.0, added a 13.0 jail and started building.  Everything quickly failed because ccache was not able to access /root/.ccache because /root is now 750, so nobody cannot go there.

## How to reproduce
Create a 13.0 jail, enable ccache, try to build something.

## Expected behavior
I don't know, maybe `chmod 755 /root` at one point.

**Comment by 0mp** [comment]
This is probably related to the src commit a35bc248fd6cfc2ebb0c6f836591637e58c2a860. Here's the Phabricator review: https://reviews.freebsd.org/D23392

**Comment by derekschrock** [comment]
Current short term hack?

https://gist.github.com/derekschrock/e05f0919b49528263633f8ba5b1af60b

**Comment by dsh2dsh** [comment]
Hi!

Looks like I've got the same issue. After upgrade to FreeBSD 13 I'm trying to rebuild all and it failed because ccache. I see message that ccache failed to create temp file in /root/.ccache.

**Comment by chrcoluk** [comment]
guys its easy to use a custom ccache location using CCACHE_DIR variable.

e.g. CCACHE_DIR=/var/tmp/ccache

**Comment by bdrewery** [comment]
> guys its easy to use a custom ccache location using CCACHE_DIR variable.
> 
> e.g. CCACHE_DIR=/var/tmp/ccache

`CCACHE_DIR` is just a host-source directory. It does not impact the destination directory.

```
${NULLMOUNT} ${CCACHE_DIR} ${mnt}${HOME}/.ccache
```
