### ISSUE TITLE
consider depending on cpdup

### ISSUE THREAD

**Issue by igalic** [freebsd/poudriere#837]
There exists a `cpdup(1)` port: https://www.freshports.org/sysutils/cpdup/

Would it make sense to just depend on that port?

poudriere does not install the cpdup man page, so reading `poudriere image --help`'s:

```
    -X excludefile  -- File containing the list in cpdup format
```

Is really confusing, when there's no man page to refer to.

-----

note that there's a newer version of cpdup that's moved over under the DragonFlyBSD umbrella, and there's a patch for it but the maintainer seems to have timed out: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252854

**Comment by bdrewery** [comment]
I hear you but at the moment Poudriere is self-contained, except for some certs that should be in base anyway.
