### ISSUE TITLE
poudriere-devel: Jail creation fails on older installs

### ISSUE THREAD

**Issue by brd** [freebsd/poudriere#844]
After 1b3cf3a  There are problems with this for older installs.. I have:

```
ZPOOL=scratch
```

In poudriere.conf and my jails dataset has the following mountpoint:

```
NAME                     PROPERTY    VALUE                     SOURCE
scratch/poudriere/jails  mountpoint  /scratch/poudriere/jails  default
```

So it creates a dataset without a mount point and then cannot find it:

```
# poudriere -vv jail -c -j 122 -v 12.2-RELEASE
[00:00:00] Creating 122 fs at /usr/local/poudriere/jails/122... done
mkdir: /usr/local/poudriere/jails/122: No such file or directory
```

If I update the mountpoint property for `scratch/poudriere/jails` it works fine, but there needs to be an upgrade path.

@driesmp Do you have any thoughts on how this should be handled?

**Comment by driesmp** [comment]
I'll investigate, just for my information, did you change the mountpoint of scratch/poudriere/jails to /usr/local/poudriere/jails?

**Comment by driesmp** [comment]
Ok, learnings so far, when poudriere has never been installed it works fine.
When poudriere has been used and is upgraded to the new ZFS way of working we need to execute the following commands once for the conversion.

```
zfs inherit -r mountpoint ${ZPOOL}${ZROOTFS}
zfs set mountpoint=$BASEFS ${ZPOOL}${ZROOTFS}

**Comment by brd** [comment]
> I'll investigate, just for my information, did you change the mountpoint of scratch/poudriere/jails to /usr/local/poudriere/jails?

I did to get past this problem for now..

> Ok, learnings so far, when poudriere has never been installed it works fine.
> When poudriere has been used and is upgraded to the new ZFS way of working we need to execute the following commands once for the conversion.
> 
> ```
> zfs inherit -r mountpoint ${ZPOOL}${ZROOTFS}
> zfs set mountpoint=$BASEFS ${ZPOOL}${ZROOTFS}
> ```

Yes, I agree, and we want to check this probably every time we create a ports tree or jail.

**Comment by bdrewery** [comment]
I am going to revert #814 for now. It needs to handle migration for mountpoint, but also compression and atime on /jails and /ports.

**Comment by bdrewery** [comment]
I will only revert the `createfs` part.
