### ISSUE TITLE
question about FLAVOR handling

### ISSUE THREAD

**Issue by ohauer** [freebsd/poudriere#846]
## Prerequisites
- [x ] Have you checked for an existing issue describing the issue?
### Question, what is the best way to specify FLAVORS in the build list?
E.g. emulators/open-vm-tools-nox11 was removed and added as FLAVOR to emulators/open-vm-tools

Specifying emulators/open-vm-tools@nox11 builds what I want but has a bad behavior so the port is build every time even no dependency or the port itself has changed.

### build log with emulators/open-vm-tools@nox11 in the package list:
```
Deleting open-vm-tools-nox11-11.xxx.txz: stale package: **unwanted origin** emulators/open-vm-tools@**nox11**
```

new try with:
```
### make.conf
.if ${.CURDIR:M*/emulators/open-vm-tools}
FLAVOR?=nox11
.endif
```
### build log with emulators/open-vm-tools in the package list :
```
 Deleting open-vm-tools-nox11-11.xxx.txz: stale package: unwanted origin emulators/open-vm-tools@nox11
```

**Comment by bdrewery** [comment]
Which version of poudriere? `poudriere version`

I'm confused, how are you specifying the port origin in your `bulk -f` list?

Do you have open-vm-tools listed more in your port list?

If `emulators/open-vm-tools@nox11` then why add the make.conf change?

Does the problem happen without the make.conf change?

**Comment by ohauer** [comment]
Sorry for the delay.
Your hint was 100% successfull

**Comment by Helmut1972** [comment]
I'm having the same issue, could you please describe the solution?

Thank you!

**Comment by ohauer** [comment]
Hi Helmut,

solution was to specify the Flavor only in the package list wit the "@" sign and not additional in the make.conf that I have for PD.

Since I'm running no desktops and console only systems I want to avoid everyting that is not required in this case X11 stuff and blindly copied the content from /etc/make.conf to /usr/local/etc/pd/make.conf which not work with PD
