### ISSUE TITLE
Can't create a ports-tree with git

### ISSUE THREAD

**Issue by rduffner** [freebsd/poudriere#850]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
Cannot create ports-tree after ports switched to git
```
root@bsd1-build-prod:/usr/local/poudriere/ports # poudriere ports -cvvv -B 2021Q2 -m git -p 2021Q2
=>> Debug: Reading /usr/local/etc/poudriere.conf
[00:00:01] Creating 2021Q2 fs at /usr/local/poudriere/ports/2021Q2... done
[00:00:01] Dev: cache_invalidate: Invalidating _zfs_getfs(/usr/local/poudriere/ports/2021Q2)
[00:00:01] Cloning the ports tree...Cloning into '/usr/local/poudriere/ports/2021Q2'...
warning: Could not find remote branch 2021Q2 to clone.
fatal: Remote branch 2021Q2 not found in upstream origin
[00:00:01] Error:  fail
[00:00:01] Error while creating ports tree, cleaning up.
[00:00:01] Dev: cache_call: Fetching _zfs_getfs(/usr/local/poudriere/ports/2021Q2)
[00:00:01] Dev: cache_invalidate: Invalidating _zfs_getfs(/usr/local/poudriere/ports/2021Q2)
root@bsd1-build-prod:/usr/local/poudriere/ports # 
```

But maybe, it's just documentation missing?

## How to reproduce
poudriere ports -cvvv -B 2021Q2 -m git -p 2021Q2

## Expected behavior
Should be able to create a ports-tree.

## Screenshots
none

## Environment
 - Host OS: 12.2-RELEASE-p6

 - Poudriere Version: 3.3.6 
 - Ports branch and revision: 2021Q2

**Comment by silenius** [comment]
as a workaround you can try with: `-U "https://git.freebsd.org/ports.git"`

**Comment by rduffner** [comment]
Yes, this works! At least, it created a ports-tree.

**Comment by bdrewery** [comment]
This is improved in upcoming 3.3.7 but I don't expect this exact format of `-m git` to work as that implies `git://` which FreeBSD's repo doesn't support. Not specifying `-m` at all will do the right thing in 3.3.7.
