### ISSUE TITLE
poudriere testport -c does not use the correct ports tree.

### ISSUE THREAD

**Issue by mat813** [freebsd/poudriere#854]
## Prerequisites
- [X] Have you checked for an existing issue describing your problem?
- [X] Are you running the latest version?
- [X] Is your ports tree recent?
- [X] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
I always use `poudriere testport -c` to be able to review options, and today, I removed an option, and it was still showing up.

## How to reproduce
Run `poudriere testport -j 13amd64 -c sysutils/tmux`
It ends up running

```
PORTSDIR=/home/mat/work/freebsd/ports __MAKE_CONF=/p/data/.m/13amd64-ports/ref/.p/tmp/poudriere-make.conf.ZWMGmFVT PORT_DBDIR=/p/data/.m/13amd64-ports/ref/var/db/ports TERM=screen-256color make -C /usr/ports/sysutils/tmux
```

Where `/usr/ports` is very wrong.

## Expected behavior
It should either run inside the jail, or it should not use `/usr/ports` but the ports tree I am using.

## Environment
 - Host OS 13.0 amd64
 - Jail OS 13.0 amd64
 - Poudriere Version poudriere-devel-3.3.99.20210303_1
 - Ports branch and revision: main 195f2e27fd72d

**Comment by bdrewery** [comment]
https://gist.github.com/bdrewery/6618d33d392b5f9ec1cd0bf10b81ae0c has a patch if you want to try it out.

It avoids running in the jail because of dialog4ports being ran from the host. Separate issue to deal with.

**Comment by mat813** [comment]
This gives me:

```
PORTSDIR=/p/data/.m/13amd64-ports/ref/home/mat/work/freebsd/ports __MAKE_CONF=/p/data/.m/13amd64-ports/ref/.p/tmp/poudriere-make.conf.boJt4qze PORT_DBDIR=/p/data/.m/13amd64-ports/ref/var/db/ports TERM=screen-256
color make -C /p/data/.m/13amd64-ports/ref/usr/ports/sysutils/tmux config                                                                                                                                            
make: "/p/data/.m/13amd64-ports/ref/usr/share/mk/bsd.port.mk" line 32: Cannot open /p/data/.m/13amd64-ports/ref/home/mat/work/freebsd/ports/Mk/bsd.port.mk
make: Fatal errors encountered -- cannot continue
make: stopped in /p/data/.m/13amd64-ports/ref/usr/ports/sysutils/tmux
```

PORTSDIR was correct before, though. so, with only:

```

 	    TERM=${SAVED_TERM} \
-	    make -C ${portdir} \
+	    make -C "${MASTERMNT}${portdir}" \
 	    ${FLAVOR:+FLAVOR=${FLAVOR}} \
```

It works, thanks.

**Comment by bdrewery** [comment]
Oh there is `$portdir` and `$portsdir`. Fun.

**Comment by mat813** [comment]
Though, it could just be `${MASTERMNT}/usr/ports`.

**Comment by brd** [comment]
@brooksdavis Can you test with this patch that your use case still works?

**Comment by brd** [comment]
Looks like it was broken by: d8c832bb921274efa1a6be229feeca5036a48088

**Comment by rbgarga** [comment]
> This gives me:
> 
> ```
> PORTSDIR=/p/data/.m/13amd64-ports/ref/home/mat/work/freebsd/ports __MAKE_CONF=/p/data/.m/13amd64-ports/ref/.p/tmp/poudriere-make.conf.boJt4qze PORT_DBDIR=/p/data/.m/13amd64-ports/ref/var/db/ports TERM=screen-256
> color make -C /p/data/.m/13amd64-ports/ref/usr/ports/sysutils/tmux config                                                                                                                                            
> make: "/p/data/.m/13amd64-ports/ref/usr/share/mk/bsd.port.mk" line 32: Cannot open /p/data/.m/13amd64-ports/ref/home/mat/work/freebsd/ports/Mk/bsd.port.mk
> make: Fatal errors encountered -- cannot continue
> make: stopped in /p/data/.m/13amd64-ports/ref/usr/ports/sysutils/tmux
> ```
> 
> PORTSDIR was correct before, though. so, with only:
> 
> ```
> 
>  	    TERM=${SAVED_TERM} \
> -	    make -C ${portdir} \
> +	    make -C "${MASTERMNT}${portdir}" \
>  	    ${FLAVOR:+FLAVOR=${FLAVOR}} \
> ```
> 
> It works, thanks.

I confirm this one line change fix the issue
