### ISSUE TITLE
Build Clusters - Distribute Tasks Across Multiple Compute Nodes

### ISSUE THREAD

**Issue by tuaris** [freebsd/poudriere#857]
## Prerequisites
- [X] Have you checked for an existing issue describing your idea?

## What is your proposal?
Start jails and execute build jobs on local and remote hosts using SSH + NFS protocols.  This would be a way of implementing clustering support.

## What is the existing behavior, if any?
Jails and build task are run on the local host.

## What is the motivation / use case for the change?
Build repositories faster by utilizing multiple worker nodes.

## Did you consider any alternatives?
You could simulate this behavior by listing all ports and flavors across a few sets and having each machine build one set.  Then manually merge the results into a single repository.  This is a lot of work and very complicated to do by hand.  I think extending Poudriere to support this feature (while not trivial) might be feasible?

## Is this really a ports feature request?
I believe this functionality is well within Poudriere's scope.

## Example
One of the nodes would be chosen as the "master" that will drive each of the worker nodes.  In poudriere.conf the IP/hostname of each of the worker nodes is listed.  Each worker node would need to have ZFS pools and datasets configured identically to the master node.   In the simplest case, root login via PKI would be used (I suppose it's possible to avoid direct root login by having doas/sudo installed).  The master node will also be an NFS server that shares out any common paths that the workers need to read/write (for example the ports trees, /usr/local/etc/poudriere.d/, distfiles, ccache, logs, pkgs, etc..).

The part that I am not sure of yet is if jails will need to be created on each worker node, or if they can be shared out over NFS.

The master node can be configured to only act as a driver or be a worker node itself.  When the process to start a build is started (using the master node), jails are launched in the same manner as is currently done.  On remote worker nodes the main difference is that the commands are sent over SSH and NFS shares will need to be mounted.  Poudriere then distributes the build tasks across all available workers.

When completed, the master node proceeds with any housekeeping and repository generation tasks.

## Additional context
I'm no expert on how Poudriere works, so if any of the above seems out of the ordinary... that's why :grin:

**Comment by bdrewery** [comment]
Thanks for the ideas. Will track from #473.
