### ISSUE TITLE
Use main as default branch for git

### ISSUE THREAD

**Issue by fliiiix** [freebsd/poudriere#859]
## Prerequisites
- [X] Have you checked for an existing issue describing the issue?

I guess the default should be `head/main` and not `head/master`

```
-B branch     -- Which branch to use for the svn or git methods.  Defaults
                     to 'head/master'.
```

**Comment by bdrewery** [comment]
Fixed for 3.3.7 in a3becdcd1ec9f5f53f3fa59ef9d0e41d931fabb4
