### ISSUE TITLE
ALLOW_MAKE_JOBS_PACKAGES &c don't actually accept globs (regression)

### ISSUE THREAD

**Issue by backerman** [freebsd/poudriere#860]
## Prerequisites
- [X] Have you checked for an existing issue describing your problem?
- [X] Are you running the latest version?
- [X] Is your ports tree recent?
- [X] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
Commit 7740fa2cf8faa310c0e0c357e0c35ef7c1b3668b appears to have introduced a regression that breaks parsing of the `ALLOW_*_PACKAGES` and similar variables. The `*` is only special if it's outside quotation marks (ref [SUS Shell & Utilities §2.13.1][citation]), so quoting the case pattern causes it to no longer be evaluated as a wildcard.

[citation]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_13
## How to reproduce
1. Attempt to build lang/gcc10 when `ALLOW_MAKE_JOBS_PACKAGES` contains `gcc*` but not `gcc10`.
2. Observe that `DISABLE_MAKE_JOBS` is still present in the build log.

## Expected behavior
`*` is treated as a wildcard in `ALLOW_MAKE_JOBS_PACKAGES`.

## Environment
 - Host OS [e.g. 12.2 amd64]: 13.0 amd64
 - Jail OS [e.g. 12.0 powerpc]:  13.0 amd64
 - Browser: [e.g. chrome, safari]: N/A
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: a8006e837b39f48df0f80afc562e2f8a6be6033d
 - Ports branch and revision [e.g. 2020Q3 r550754]: latest af49fbec4f0f6453b4b3dfe522107ed2918ae8f7

**Comment by bdrewery** [comment]
Broken by 7740fa2cf8faa310c0e0c357e0c35ef7c1b3668b
