### ISSUE TITLE
lang/perl5.xx fails with dtrace enabled

### ISSUE THREAD

**Issue by sambler** [freebsd/poudriere#866]
## Prerequisites
- [ y] Have you checked for an existing issue describing your problem?
- [ y] Are you running the latest version?
- [ y] Is your ports tree recent?
- [ y] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
lang/perl5.xx ports with dtrace enabled fail to build in poudriere
Tested with -
perl5.28.3_1
perl5.30.3_1
perl5.32.1_1
perl5.34.0.r1

perl5.32 builds on host - not in poudriere jail
disabling DTRACE option for perl5 ports in make.conf allows build to work
eg. lang_perl5.32_UNSET= DTRACE

build log shows -
```...
Support DTrace if available? [y]  
Where is the dtrace executable? (~name ok) [/usr/sbin/dtrace]  

*** Configure:  Fatal Error:  /usr/sbin/dtrace doesn't support -h flag
***
*** Your installed dtrace doesn't support the -h switch to compile a D
*** program into a C header. Can't continue.

===>  Script "Configure" failed unexpectedly.
```

## How to reproduce
Host and jail both built with stable/13 e284a6234ffb
Build perl5.xx ports in poudriere

## Expected behavior
perl ports to compile without error

## Environment
 - Host OS [e.g. 12.2 amd64]: amd64 stable/13 e284a6234ffb
 - Jail OS [e.g. 12.0 powerpc]: amd64 stable/13 e284a6234ffb
 - Host and jail have just been updated to stable/13 having both been compiled on stable/12 host
 - compat12, nvidia-driver, pkg, poudriere and perl5.32.1_1 - have been manually updated, other ports were built with stable/12
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: 3.3.6 and -devel-3.3.99.20210303_2
 - Ports branch and revision [e.g. 2020Q3 r550754]: main 4bbfa3821301

## Additional context
Appears related to older [bug 227312](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227312) - details added there also

**Comment by brd** [comment]
This is not a poudriere bug, see the last comment in the bug you linked.
