### ISSUE TITLE
test port options with testport

### ISSUE THREAD

**Issue by Zirias** [freebsd/poudriere#870]
I sometimes stumble over bugs in ports triggered by non-default options. As a maintainer, I try to avoid them by doing a `testport` with every valid combination of options. But with a port with many options, this is cumbersome and error-prone, it's easy to accidentally miss a combination.

I think `poudriere testport` could be helpful here by offering a flag to test all valid combinations in a single run, repeatedly building the same port:

* determine all valid combinations of options
* for each of them, generate the `make.conf` fragments to select them and run the test build

**Comment by bdrewery** [comment]
#303 covers this but it's not feasible to implement.

**Comment by mat813** [comment]
Another way to achieve this can be done by dropping a Makefile.local (that does not get added to the tree). For example, for `dns/bind916` I have this:

```make
# cat dns/bind916/Makefile.local 
.if !defined(BIND_TOOLS_SLAVE)
FLAVORS=        normal small huge ${OPTIONS_SINGLE_GSSAPI:NGSSAPI_NONE:tl}
.if empty(FLAVOR)
FLAVOR= normal
.endif

.if ${FLAVOR} != normal
PKGNAMESUFFIX:= ${PKGNAMESUFFIX}-${FLAVOR}
.endif

.if ${FLAVOR} == small
OPTIONS_UNSET_FORCE=    ${OPTIONS_DEFINE} ${OPTIONS_GROUP_DLZ}
.elif ${FLAVOR} == huge
OPTIONS_SET_FORCE=      ${OPTIONS_DEFINE} ${OPTIONS_GROUP_DLZ} ${OPTIONS_RADIO_CRYPTO}
.elif ${FLAVOR:Mgssapi*}
OPTIONS_UNSET_FORCE=    GSSAPI_NONE
OPTIONS_SET_FORCE=      ${FLAVOR:tu}
.endif

CONFIGURE_ARGS+=        --enable-full-report
```

It kinda abuses flavors to build different combinations of options.
