### ISSUE TITLE
"poudriere ports -uv" should exit with a non-zero status for a git+https tree when you have "unmerged files"

### ISSUE THREAD

**Issue by leres** [freebsd/poudriere#871]
## Prerequisites
- [X] Have you checked for an existing issue describing your problem?
- [X] Are you running the latest version?
- [X] Is your ports tree recent?
- [X] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
Updating a git+https ports tree that has unmerged files prints  errors but exits with status 0.

## How to reproduce
Run:
`poudriere ports -uv -p current`
which outputs:
```
[00:00:00] Updating portstree "current" with git+https...error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
 done
```
And the exit status is 0.

## Expected behavior
It's all good except it should exit 1 (or any other non-zero value)

## Screenshots
<If applicable add screenshots to help explain your problem.>

## Environment
 - Host OS [12.2 amd64]:
 - Jail OS [12.2 amd64]: 
 - Browser: [firefox]: 
 - Poudriere Version [3.3.6]: 
 - Ports branch and revision [main 975c4836a6e01d1e62e4f075d1d00c7c3c59f196]:

## Additional context
<Add any other context about the problem here.>

**Comment by bdrewery** [comment]
928ba1974dca3521508f9ae08200f00c25c2c6bf fixed this
