### ISSUE TITLE
Allow building from a temporary ports tree

### ISSUE THREAD

**Issue by yzgyyang** [freebsd/poudriere#873]
## Prerequisites
- [x] Have you checked for an existing issue describing your idea?

## What is your proposal?
<A clear and concise description of what your proposal is.>

In a CI environment, the ports tree that I would like to build could potentially live in `/path/to/build/12345/ports`. I would like to use this ports tree one-off for a specific build only, but don't save it (without `poudriere ports -c` first).

## What is the existing behavior, if any?
<A clear and concise description of what the current situation is.>

To my knowledge (I could be wrong), there is no easy way of just specifying a path to build from, something like

```
sudo poudriere bulk -t -j /path/to/build/12345/ports ports-mgmt/pkg net/nc
```

or quickly update the path to a tree to be pwd.

**Comment by bdrewery** [comment]
I don't see any reason to implement this. It's not trivial and would require modifying anything that uses a ports tree in the code. It's trivial for you to wrap your build with a `ports -c` and `ports -d` to import the system tree.

**Comment by bdrewery** [comment]
https://github.com/freebsd/poudriere/wiki/use_system_ports_tree
