### ISSUE TITLE
A command to run "exp-runs"

### ISSUE THREAD

**Issue by diizzyy** [freebsd/poudriere#884]
A nice feature would be to have poudriere test downstream users in tree using a command / switch
Example: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251512#c10

**Comment by bdrewery** [comment]
From what I can understand here this is just `poudriere bulk -cat`.

**Comment by bdrewery** [comment]
All that is special is comparing 2 builds which #396 is for.

**Comment by diizzyy** [comment]
I see, thanks! :-)
