### ISSUE TITLE
Reduce repetitive prefetches of binary packages

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#891]
## Prerequisites

☑ Checked for an existing issue.

## Proposal

If appropriate, allowed prefetched binaries to be cached. 

## Existing behaviour

`https://github.com/freebsd/poudriere/issues/890#issue-952215875`

– there, the recorded session was one of a number of sessions, each session used the same command: 

`poudriere bulk -b latest -j main -c graphics/okular`

– and each one involved a download of around 1 GiB.

```text
% pkg info -x poudriere
poudriere-devel-3.3.99.20210720
% uname -KUv
FreeBSD 14.0-CURRENT #102 main-n248139-3a57f08b504: Thu Jul 22 05:30:35 BST 2021     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG  1400026 1400026
% 
```

## What is the motivation / use case for the change?

_Unnecessarily_ repetitive prefetches: 

* consume time
* consume network bandwidth
* create unnecessary disk activity; #36

## Did you consider any alternatives?

From the manual page: 

```text
     -b name  Specify the name of the binary package branch to use to prefetch
              packages.  Should be "latest", "quarterly", "release_*", or url.
              With this option poudriere will first try to fetch from the
              binary package repository specified the binary package prior to
              do the sanity check if the package does not already exist.  When
              -t is used along with -C, or -c, then listed packages will not
              be fetched.

              See PACKAGE_FETCH_BRANCH, and PACKAGE_FETCH_URL, in
              poudriere.conf.sample.
```

I browsed the `.sample` file, can't see anything that might reduce repetition. 

## Is this really a ports feature request?

Yes. 

## Example

If the host `/var/cache/pkg` directory can not be made available to the jail then, I guess, poudriere might gain an in-jail equivalent. 

## Additional context

Side note, re: 
`https://github.com/freebsd/poudriere/issues/890#issue-952215875`
I recognise _Error: download_from_repo: failed to bootstrap pkg_ as a symptom of 
`https://github.com/freebsd/poudriere/issues/889`

**Comment by bdrewery** [comment]
Yeah I think this is needed too. In d3166243fabcf63c7a492fd7652344388cb5c93d I made it so `bulk -n -b` (dry-mode) still does the fetches as otherwise the predictions are wrong. It would be simpler if `pkg` used a caching pattern of `/var/cache/pkg/$ABI/$repo/` as currently just using host `/var/cache/pkg` (for all jals) causes conflicts on the filenames such that each jail would claim to have mismatches and do a refetch. A per-jail directory for caching makes sense but then it is this big growing directory that users are less aware of and would require new tooling to manage. I don't know. I might explore improving `pkg` and `pkg clean` here.

**Comment by grahamperrin** [comment]
Thanks, 

> … new tooling to manage. …

Management would be nice to have, but IMHO it'll be nicer to (first): 

* have the caching, enabled by default
* make the user aware of the cache

– and for awareness, you might simply add a line of output at or near the tail of the run. Use `du -hs` (or equivalent) behind the scenes to measure the size, on disk, of the cache.

**Comment by grahamperrin** [comment]
Example (mock up): 

```text
poudriere bulk -b latest -j main -c sysutils/htop
… 
The process will require 48 MiB more space.
48 MiB to be downloaded.
[main-default] Fetching automake-1.16.3.txz: 100%  549 KiB 561.8kB/s    00:01    
…
[main-default] Fetching libiconv-1.16.txz: 100%  607 KiB 621.2kB/s    00:01    
[main-default] Fetching pkg-1.16.3.txz: 100%    8 MiB   8.7MB/s    00:01    
[00:02:20] Error: download_from_repo: failed to bootstrap pkg
[00:02:20] Cleaning up
main-default: removed
main-default-n: removed
[00:02:20] 49 M (cumulative total for main-default) cached at /path/to/cache
[00:02:20] Unmounting file systems
```

**Comment by grahamperrin** [comment]
Oops, my bad, the lowercase `c`: 

> `poudriere bulk -b latest -j main -c graphics/okular`

**Comment by grahamperrin** [comment]
@bdrewery I think, this is not a bug; I was misusing lowercase `-c` (without realising the use case for uppsercase `-C`). Or, am I missing something?

**Comment by bdrewery** [comment]
@grahamperrin I'm not sure but I reworked this issue to be a feature of caching the packages. That's complete in my local repo, I just have not pushed it yet.
