### ISSUE TITLE
use jail make.conf during jail creation

### ISSUE THREAD

**Issue by swills** [freebsd/poudriere#895]
## Prerequisites
- [x] Have you checked for an existing issue describing the issue?

I'm not sure if this is a bug, a feature request or just something I don't understand, so filing as other....

I expected jail creation to use at least `/usr/local/etc/poudriere.d/<jailname>-make.conf`, but it does not:

https://github.com/freebsd/poudriere/blob/master/src/share/poudriere/jail.sh#L446

This seems to have always been this way and intentional, though I'm not sure why.

Are my expectations incorrect?

Is there another way to customize `CFLAGS`/`CXXFLAGS` used during jail build than via `make.conf`?

**Comment by bdrewery** [comment]
I think it could be an oversight from when building jails from source was added. At this point it might be surprising to fix it. More feedback from others would help.
It makes me want to add a ports.conf too that only ports uses.

**Comment by allanjude** [comment]
For jails from source, wouldn't we want more like <jailname>-src.conf rather than make.conf?

**Comment by bdrewery** [comment]
> For jails from source, wouldn't we want more like `<jailname>-src.conf` rather than make.conf?

We already have that.

**Comment by swills** [comment]
I think having a `ports.conf` does sound nice, but I'm not sure that using `/usr/local/etc/poudriere.d/<jailname>-make.conf` in jail creation affects that.

To me the real question seems to be, is there any down side at this point to using `/usr/local/etc/poudriere.d/<jailname>-make.conf` in jail creation going to cause issues not or in the future?

So far I can't seem to think of a way in which it would cause issues for anyone now, or if we add a `ports.conf` later.

**Comment by bdrewery** [comment]
The reason I bring up ports.conf is because make.conf isn't used for source now. People may require a simple way to avoid affecting the source build with ports flags they've had in make.conf if we fix the bug.
I'll get this in for the next release.

**Comment by swills** [comment]
any progress here?

**Comment by 5u623l20** [comment]
I was looking for this option and for now looks like I can add NO_MODULES= in <JAIL>-src-env.conf and it works. Need to test some more flags and how they add up without make.conf.

**Comment by swills** [comment]
> I was looking for this option and for now looks like I can add NO_MODULES= in -src-env.conf and it works. Need to test some more flags and how they add up without make.conf.

Yes, some options can be in -src-env.conf but not all. some options have to be in make.conf. anywho, i have a local hack for this but not sure it's right
