### ISSUE TITLE
poudriere naming conventions for jails and ports trees

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#897]
## Prerequisites
- ☑ Have you checked for an existing issue describing the issue?

From <https://forums.FreeBSD.org/threads/81582/post-525675>: 

> Don't use dashes (`-`) in the name of the jail … or the ports tree name. That causes a bunch of weird issues. …

From the manual page for poudriere-jail(8): 

```text
CAVEATS
   Jail Names
     The values set with the -j, -z, and -p flags are all used directly in the
     name of the jail created by poudriere.

     Be careful to respect the names supported by jail(8):

           This is an arbitrary string that identifies a jail (except it
           may not contain a '.').

FreeBSD 14.0-CURRENT              May 6, 2021             FreeBSD 14.0-CURRENT
```

```text
% pkg info -x poudriere
poudriere-devel-3.3.99.20210720
% 
```

**Comment by brd** [comment]
Eh? I use dashes in all my jail names and have not had any issues and I have been doing it for many years..

**Comment by grahamperrin** [comment]
(Maybe not a bug … I should have checked for myself before reporting …)

**Comment by grahamperrin** [comment]
Closing; can be reopened if there's a response to <https://forums.freebsd.org/threads/81582/#post-526102>. Apologies for the noise.

**Comment by bdrewery** [comment]
The issue is with ports trees with -. Jails with - should be fine (I use this). I'll add a check to prevent using new ports trees with -.
