### ISSUE TITLE
option change not recognized when new option is diabled

### ISSUE THREAD

**Issue by emtiu** [freebsd/poudriere#900]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
When a port gains a new option, which is disabled by default or by the user through `poudriere config`, the next run of `poudriere bulk` will not recognize a change in options.

## How to reproduce
This was observed when dealing with [this change to the ports tree](https://cgit.freebsd.org/ports/commit/?id=a3abb6ed787917d0b8ef9da6837c25e414763efa).
1. Before, the port had only one option: DOCS
2. The port was changed to have two options: DOCS BRACKETEDPASTE, with BRACKETEDPASTE on by default
3. I called `poudriere options -j myjail -c devel/readline` to disable the new option BRACKEDTEDPASTE
4. `poudriere bulk -j myjail -f myportlist` did not rebuild the devel/readline port.

## Expected behavior
I expected devel/readline to be rebuilt, because I had changed an option.

## Likely cause
My guess is that poudriere compared the enabled options before and after, and found just "DOCS" in both cases. poudriere wasn't aware that a new option BRACKEDTEDPASTE had been introduced, but disabled.

One might be tempted to think: When a new option appears, but is disabled, then the properties of the port have not changed. But this is not the case at least in this instance, because BRACKEDTEDPASTE made configurable a behavior that was always-on before the option existed. So by disabling the new option, I changed the behavior of the port.

## Environment
 - Host OS: 13.0 amd64
 - Jail OS: 13.0 amd64
 - Poudriere Version: poudriere-devel-3.3.99.20210720
 - Ports branch and revision: [main a3abb6ed787917d0b8ef9da6837c25e414763efa](https://cgit.freebsd.org/ports/commit/?id=a3abb6ed787917d0b8ef9da6837c25e414763efa)

**Comment by bdrewery** [comment]
Poudriere compares the options in the pkgfile from `pkg query -F readline-ver.txz '%Ok %Ov'` to `make -V SELECTED_OPTIONS` in the port directory.
I do expect it would detect this change fine.

```
~/git/ports/main/devel/readline # git checkout a3abb6ed787917d0b8ef9da6837c25e414763efa^
Previous HEAD position was a3abb6ed7879 devel/readline: Add BRACKETEDPASTE option
HEAD is now at 538ac402f424 devel/py-twisted: Add NO_ARCH
~/git/ports/main/devel/readline # make -V SELECTED_OPTIONS
DOCS
```
```
# ./poudriere bulk -j exp-12amd64 -p commit -z test devel/readline
...
[00:00:11] Mounting ports from: /root/git/ports/main
[00:00:11] Mounting packages from: /poudriere/data/packages/exp-12amd64-commit-test
...
[00:00:07] Ports supports: FLAVORS SELECTED_OPTIONS
[00:00:07] Ports top-level git hash: 538ac402f424
...
[00:00:48] Built ports: devel/readline
...
# pkg query -F /poudriere/data/packages/exp-12amd64-commit-test/All/readline-8.1.1.txz '%Ok %Ov'
DOCS on
```

```
~/git/ports/main/devel/readline # git checkout a3abb6ed787917d0b8ef9da6837c25e414763efa
Previous HEAD position was 538ac402f424 devel/py-twisted: Add NO_ARCH
HEAD is now at a3abb6ed7879 devel/readline: Add BRACKETEDPASTE option
~/git/ports/main/devel/readline # make -V SELECTED_OPTIONS
BRACKETEDPASTE DOCS
```

The `SELECTED_OPTIONS` behaves as I expect so far.

```
# ./poudriere bulk -j exp-12amd64 -p commit -z test -nv devel/readline
...
[00:00:05] [Dry Run] Mounting ports from: /root/git/ports/main
[00:00:05] [Dry Run] Mounting packages from: /poudriere/data/packages/exp-12amd64-commit-test
...
[00:00:07] [Dry Run] Ports supports: FLAVORS SELECTED_OPTIONS
[00:00:08] [Dry Run] Ports top-level git hash: a3abb6ed7879
...
[00:00:09] [Dry Run] Deleting readline-8.1.1.pkg: changed options
[00:00:09] [Dry Run] Pkg: DOCS
[00:00:09] [Dry Run] New: BRACKETEDPASTE DOCS
```

And it detected the option and will rebuild it.

Did you modify the `CHECK_CHANGED_OPTIONS` value? It defaults to yes.

**Comment by emtiu** [comment]
Note step 3. in my **How to reproduce** list, which comes _before_ running `poudriere bulk`. If I understand your testing output correctly, you did not reproduce that step. (Though it's possible I'm misunderstanding it.)

The problem appears when an option is _newly introduced and default-on_, but then _immediately disabled by `poudriere options`_ before running `poudriere bulk` the next time.

**Comment by bdrewery** [comment]
@emtiu Aha that makes sense now. Nice find!

**Comment by bdrewery** [comment]
I think I have it working locally now.
```
[00:00:12] [Dry Run] Deleting readline-8.1.1.pkg: changed options
[00:00:12] [Dry Run] Pkg: +DOCS
[00:00:12] [Dry Run] New: +DOCS -BRACKETEDPASTE
```

Doing more testing before pushing out to git.

**Comment by bdrewery** [comment]
This was also a problem for the new package fetching feature.
Before
```
[00:00:25] [Dry Run] Package fetch: Will fetch readline-8.1.1
```
After
```
[00:00:24] [Dry Run] Package fetch: Skipping readline-8.1.1: options wanted:   '-BRACKETEDPASTE +DOCS')
[00:00:24] [Dry Run] Package fetch: Skipping readline-8.1.1: options provided: '+DOCS')
```
