### ISSUE TITLE
Jail creation: -v head is not synonymous with -v 14.0-CURRENT (manifest not found)

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#901]
## Prerequisites

☑ Have you checked for an existing issue describing your problem?
☑ Are you running the latest version?
☑ Is your ports tree recent?
☐ Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)? **No**.

## Describe the bug

A documentation bug? 

`-v head` fails, `-v 14.0-CURRENT` succeeds. 

```text
root@mowa219-gjp4-zbook-freebsd:~ # poudriere jail -c -j example -v head
[00:00:00] Creating example fs at /usr/local/poudriere/jails/example... done
[00:00:01] Fetching MANIFEST for FreeBSD head amd64
fetch: https://download.FreeBSD.org/ftp/releases/amd64/amd64/head/MANIFEST: Not Found
fetch: https://download.FreeBSD.org/ftp/releases/amd64/amd64/head/MANIFEST: Not Found
[00:00:02] Error: Failed to fetch from https://download.FreeBSD.org/ftp/releases/amd64/amd64/head/MANIFEST
[00:00:02] Error while creating jail, cleaning up.
[00:00:02] Removing example jail... done
[00:00:03] Cleaning example data... done
root@mowa219-gjp4-zbook-freebsd:~ # 
```

## How to reproduce

`poudriere jail -c -j example -v head`

## Expected

From the relevant manual page, `man 8 poudriere-jail`: 

```text
     -v version       Specify the version of FreeBSD to use in the jail.  If
                      you are using -m ftp then the version should in the form
                      of “12.0-RELEASE”.  If you are using -m git, or -m svn,
                      then the version should be in the form of Git or SVN
                      branches, which is usually in the form of “stable/9” or
                      just “head” for CURRENT.  Other methods only use the
                      version value for display.
```

## Environment
 - Host OS: 14.0-CURRENT
 - Jail OS: not applicable
 - Browser: not applicable
 - Poudriere: poudriere-devel-3.3.99.20210720
 - Ports branch and revision:

**Comment by bdrewery** [comment]
The reported bug here is invalid; `-m ftp` does not support `head`. It needs `X-RELEASE`.
There is a bug here for `-m git` though in that suggesting `head` can be confusing.

**Comment by grahamperrin** [comment]
Thanks; I'm creating without specifying a method (allowing the default).

**Comment by bdrewery** [comment]
I don't see any bug remaining here. Am I wrong?

**Comment by grahamperrin** [comment]
Documentation could be better. 

I think, the paragraph should begin by stating the form that's required for the default method. 

Incidentally, "… Other methods only use the version value for display. …" – I don't understand (sorry).

**Comment by bdrewery** [comment]
Here is the new version:
```
     -v version       Specify the version of FreeBSD to use in the jail.  For most methods, and by default if no -m is specified, version should in the form of “12.0-RELEASE”.  If you are using -m git, or -m svn, then the version should be in the form of Git or SVN branches, which
                      is usually in the form of “stable/9” or “main” for CURRENT from git.  Other methods only use the version value for display.
```
