### ISSUE TITLE
ALLOW_MAKE_JOBS=no

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#903]
## Prerequisites

☑ Checked for an existing issue describing the idea

## Proposal

If `ALLOW_MAKE_JOBS` is `NO` or `no` then `MAKE_JOBS` should be disabled.

## Existing behavior

If I'm not mistaken, `NO` and `no` are equivalent to `yes`; see the second and third screenshots below. 

## Motivation

With this example in `/usr/local/etc/poudriere.conf.sample`:

`# ALLOW_MAKE_JOBS=yes`

– I made the reasonable assumption that the effect of `no` would be the opposite of the effect of `yes` (with the line not commented out). 

## Did you consider any alternatives?

I learnt (years ago) to comment out the `yes` line; to not attempt `NO`.

## Is this really a ports feature request?

Yes.

### `# ALLOW_MAKE_JOBS=NO` (commented out)

Result: `ninja -j1 -v all` whilst building llvm12-12.0.1_3

![2021-08-14 09:43:54 commented out, ninja -j1](https://user-images.githubusercontent.com/192271/129441264-99a5b272-0620-43bb-aee9-41f381589239.png)

Original command: 

* `poudriere bulk -b latest -j main -C emulators/virtualbox-ose emulators/virtualbox-ose-kmod`

### `ALLOW_MAKE_JOBS=NO`

Result: `ninja -j4 -v all` whilst building …

![2021-08-14 09:49:26 NO, ninja -j4](https://user-images.githubusercontent.com/192271/129441266-c198741c-0f15-43c6-9cef-567197091d90.png)

### `ALLOW_MAKE_JOBS=no`

Result: `ninja -j4 -v all` whilst building …

![2021-08-14 09:52:19 no, ninja-j4](https://user-images.githubusercontent.com/192271/129441272-4a114f94-3e6e-49da-8865-05a63234aea2.png)

## Additional context

```text
% uclcmd get --file /usr/local/etc/poudriere.conf PARALLEL_JOBS
1
% grep -B 3 ALLOW_MAKE_JOBS= /usr/local/etc/poudriere.conf.sample

# By default MAKE_JOBS is disabled to allow only one process per cpu
# Use the following to allow it anyway
# ALLOW_MAKE_JOBS=yes
% grep ALLOW_MAKE_JOBS= /usr/local/etc/poudriere.conf
# ALLOW_MAKE_JOBS=no
% pkg info -x poudriere
poudriere-devel-3.3.99.20210720
% uname -KrU
14.0-CURRENT 1400030 1400030
% 
```

**Comment by grahamperrin** [comment]
https://github.com/freebsd/poudriere/commit/e71a825fed37c5781ff0808f3920181ed1fec011

**Comment by brd** [comment]
In rc.subr we use: `[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)`..

@bdrewery thoughts?

**Comment by bdrewery** [comment]
> In rc.subr we use: `[Yy][Ee][Ss]|[Tt][Rr][Uu][Ee]|[Oo][Nn]|1)`..
> 
> @bdrewery thoughts?

It makes sense but it needs to be extended to every configuration var and would be quite intrusive. Hold off for now please, I have some large patches coming.

Closing this as it is fixed.
