### ISSUE TITLE
White spaces to surround the word 'from' whilst fetching whilst creating a jail

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#904]
## Prerequisites

☑ Have you checked for an existing issue describing your problem?
☑ Are you running the latest version?
☑ Is your ports tree recent?
☐ Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)? **No**.

## Describe the bug

Whilst creating a jail, it seems that there's no white space either side of the word 

_from_

## How to reproduce

`poudriere jail -c -j example -v 13.0-RELEASE`

## Expected behavior

White spaces between words/phrases. 

## Screenshots

![image](https://user-images.githubusercontent.com/192271/130005727-2c17dc0e-771d-4867-b91c-a407b21c95b5.png)

## Environment
 - Host OS: FreeBSD 14.0-CURRENT
 - Jail OS: FreeBSD 13.0-RELEASE in the example above
 - Browser: not applicable
 - Poudriere: poudriere-devel-3.3.99.20210720
 - Ports branch and revision: latest branch

## Additional context

```text
% uname -aKU
FreeBSD mowa219-gjp4-8570p-freebsd 14.0-CURRENT FreeBSD 14.0-CURRENT #105 main-n248685-c9f833abf1d: Fri Aug 13 20:24:43 BST 2021     root@mowa219-gjp4-zbook-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG  amd64 1400030 1400030
% 
```

**Comment by bdrewery** [comment]
Are you referring to the "/usr/local/poudriere/jails/example/fromftp/bas" part?

`fetch` has a builtin limit of 46 characters for that part. We could avoid the overflow by fetching relative to the destination directory.

```
# ./poudriere jail -c -j example -v 13.0-RELEASE
[00:00:00] Creating example fs at /poudriere/jails/example... done
[00:00:02] Fetching MANIFEST for FreeBSD 13.0-RELEASE amd64
MANIFEST                                              1046  B   12 MBps    00s
[00:00:02] Fetching base for FreeBSD 13.0-RELEASE amd64
base.txz                                               180 MB   73 MBps    03s
^C[00:00:06] Error: Signal SIGINT caught, cleaning up and exiting
[00:00:06] Error while creating jail, cleaning up.
[00:00:06] Removing example jail... done
[00:00:09] Cleaning example data... done
```

Assuming that is what you're referring to I've pushed a fix for it.
