### ISSUE TITLE
wiki/poudriere-bulk.8-devel seems to be outdated

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#909]
## Prerequisites

☑ Have you checked for an existing issue describing the issue?

https://github.com/freebsd/poudriere/wiki/poudriere-bulk.8-devel

> This page is auto-generated from src/bin/poudriere-bulk.8

Seeing the phrase _auto-generated_, I imagined that content would be equal to poudriere-devel `man 8 poudriere-bulk`, however there's no option `-b` …

**Comment by bdrewery** [comment]
Just regenerated it. Thanks,
