### ISSUE TITLE
jail.sh: consistently accept svn revision number

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#91]
Currently, certain branches allow specifying revision number for svn
checkout due to how sh(1) treats excluding glob patterns: ![0-9] vs. [^0-9].
The behavior is actually useful for debugging a port against a fixed bug
in userland to compare "before" and "after" or to check for a regression.
"allbsd" method is just not atomic enough and may be unavailable do to
broken build, hosting issues, etc.

For example, a user wants to confirm whether r244236 broke plist
WITH_DEBUG=1 for every bsd.{lib,prog}.mk port.

$ poudriere jails -cj 10x64_no_symbols_file -v head@244235 -a amd64 -m svn+file
$ poudriere jails -cj 10x64_with_symbols_file -v head@244408 -a amd64 -m svn+file

<pre>
--- src/poudriere.d/jail.sh~
+++ src/poudriere.d/jail.sh
@@ -359,25 +359,28 @@ create_jail() {
        ;;
    svn*)
        SVN=`which svn`
        test -z ${SVN} && err 1 "You need svn on your host to use svn method"
        case ${VERSION} in
            stable/*![0-9]*)
                err 1 "bad version number for stable version"
                ;;
+           head@*![0-9]*)
+               err 1 "bad revision number for head version"
+               ;;
            release/*![0-9]*.[0-9].[0-9])
                err 1 "bad version number for release version"
                ;;
            releng/*![0-9]*.[0-9])
                err 1 "bad version number for releng version"
                ;;
-           stable/*|head|release/*|releng/*.[0-9]) ;;
+           stable/*|head*|release/*|releng/*) ;;
            *)
-               err 1 "version with svn should be: head or stable/N or release/N or releng/N"
+               err 1 "version with svn should be: head[@rev] or stable/N or release/N or releng/N"
                ;;
        esac
        FCT=install_from_svn
        ;;
    csup)
        case ${VERSION} in
            .)
                ;;
</pre>

**Comment by bdrewery** [comment]
Doh, it only allows head@ not everything else!
