### ISSUE TITLE
'View latest only' seems to present something other than the latest build

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#916]
## Prerequisites

☑ checked for an existing issue describing the issue.

## Observations

1. <https://pkg-status.freebsd.org/builds?type=package&jailname=main-amd64&all=1>
2. click **View latest only**
3. <https://pkg-status.freebsd.org/builds?type=package&jailname=main-amd64> 

![image](https://user-images.githubusercontent.com/192271/132091657-8d61b553-ecb4-48c6-ba23-effb6997af3b.png)

<https://pkg-status.freebsd.org/builds/default:default:main-amd64:pff8f3a1b75aa_s1b602f641a:beefy18>

> stopped:done: 

– started _Tue, 08 Jun 2021_, which I doubted was the latest, so I browsed back to the address at step (1) then clicked the _stopped:done:_ listing below the one that's currently _parallel_build:_

![image](https://user-images.githubusercontent.com/192271/132091514-463f4ad3-30a5-488c-8a92-fb16b1fe3c36.png)

<https://pkg-status.freebsd.org/builds/default:default:main-amd64:p32835fdd312f_s7b529268a5:beefy18> (started _2021-09-02_) is much more recent than the one that's reportedly latest.

**Comment by bdrewery** [comment]
That's not Poudriere. https://github.com/bdrewery/pkg-status.freebsd.org is the proper place for this. Please file it there.
