### ISSUE TITLE
3.3.99.20210904 produces failed builds, downgrading to 3.3.99.20210828 fixes it

### ISSUE THREAD

**Issue by heliosyne** [freebsd/poudriere#917]
## Prerequisites
- Have you checked for an existing issue describing your problem?
Yes, and I don't see anything new enough that would cover it

- Are you running the latest version?
I'm using the latest version in HEAD

- Is your ports tree recent?
Yes, updated this morning, commit 4e429139a (Sep 5 20:29:35 2021 +0200)

- Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?
Yes, 12.2-RELEASE-p13

## Describe the bug
When I do a bulk run, I get some number of random build fails. It's different ones each time. This started happening after upgrading from 3.3.99.20210828 to 3.3.99.20210904. Downgrading back to 3.3.99.20210828 makes the problem cease entirely, even with full bulk -c runs.

I had enabled ccache and tmpfs, but I disabled those thinking maybe I was OOMing. Disabling them did not make the problem stop.

The builds that fail are seemingly random. This is a list of some of the ones I've seen:
```
database/postgresql12-contrib
devel/libevent
mail/dovecot-pigeonhole
security/gnutls
security/openssh-portable
shells/bash
sysutils/smartmontools
www/w3m
```
They don't all fail in the build phase. Some crashed during configure, one even crashed during package.
In all of them, looking at the poudriere log shows normal, error-free builder progress, then a single line:
```
Killed
```
There are some entires in /var/log/kernel.log like this:
```
kernel: pid 3148 (conftest), jid 218, uid 65534: exited on signal 11 (core dumped)
```
But I can only correlate those as far as them occuring only when poudriere was running and there are also fewer such kernel.log entries than failed builds. There aren't any other log entries that I can find. There's nothing in the BMC logs about ECC errors or overtemps.

I've done multiple bulk -c runs after downgrading to 3.3.99.20210828 and the error has not recurred, so it appears some change after 3.3.99.20210828 is killing builders.

## How to reproduce
Preface: I have production and preproduction trees and use overlays to provide a few local ports.

1. `poudriere ports -up preprod`
2. `poudriere bulk -j pas-releng-12 -p preprod -O localports -f /usr/local/etc/poudriere.d/build-list`
3. Check for updates, see the new poudriere-devel version 
4. Upgrade poudriere-devel: 3.3.99.20210828 -> 3.3.99.20210904
5. Do a full run with the new version: `poudriere bulk -c -j pas-releng-12 -p preprod -O localports -f /usr/local/etc/poudriere.d/build-list`
6. Go get a snack because it's 341 ports and takes a bit.
7. Come back to see the acursed red lines in your poudriere output.

## Expected behavior
poudriere bulk and bulk -c runs complete normally without error as have done hundreds of times

## Screenshots
The only error in the build log is a line that says "Killed", such as this excerpt from sysutils/smartmontools failing during the package phase:
```
=======================<phase: package        >============================
===== env: 'PKG_NOTES=build_timestamp ports_top_git_hash ports_top_checkout_unclean port_git_hash port_checkout_unclean built_by' 'PKG_NOTE_build_timestamp=2021-09-05T20:38:02+0000' 'PKG_NOTE_ports_top_git_hash=4e429139a' 'PKG_NOTE_ports_top_checkout_unclean=yes' 'PKG_NOTE_port_git_hash=b461751f0' 'PKG_NOTE_port_checkout_unclean=no' 'PKG_NOTE_built_by=poudriere-git-3.3.99.20210904' NO_DEPENDS=yes USER=nobody UID=65534 GID=65534
===>  Building package for smartmontools-7.2_1
Killed
ln: /poudriere/data/logs/bulk/pas-releng-12-preprod/2021-09-05_13h32m45s/logs/errors/smartmontools-7.2_1.log: File exists
build of sysutils/smartmontools | smartmontools-7.2_1 ended at Sun Sep  5 13:38:33 PDT 2021
build time: 00:00:31
!!! build failure encountered !!!
```

## Environment
 - Host OS [e.g. 12.2 amd64]: 12.2-RELEASE-p13 amd64
 - Jail OS [e.g. 12.0 powerpc]: 12.2-RELEASE-p9 amd64
 - Browser: [e.g. chrome, safari]: not applicable? I use the command-line
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: 3.3.99.20210904
 - Ports branch and revision [e.g. 2020Q3 r550754]: master 4e429139a 

## Additional context
none

**Comment by shiorid** [comment]
Same problem on 14.0-CURRENT.
Random ports are being killed each Bulk for no apparent reason.

**Comment by vishwin** [comment]
`conftest` crashing has always happened and is harmless.

In this poudriere-devel release, I've also seen port builds getting randomly killed in the starting phase. I and a couple others suspect the locking changes introduced for this release.

**Comment by heliosyne** [comment]
> `conftest` crashing has always happened and is harmless.

Thank you for clarifying this. I added it for completeness of reporting, but it's good to know it can be safely ignored.

**Comment by bdrewery** [comment]
Do any of you have `poudriere` commands crontabbed or trying to run while the bulk is active?

**Comment by bdrewery** [comment]
Seeing some poudriere.conf could help here.

**Comment by bdrewery** [comment]
https://gist.github.com/bdrewery/5e3f7468affdebab7de9409b32d24e1c fixes it when added to /usr/ports/ports-mgmt/poudriere-devel/files/. It's an old `sh` bug fix I forgot to commit last year but I cherry picked some dependent poudriere changes over to master which ran into it again.

**Comment by markmi** [comment]
My examples of the issue on multiple machines had no use of "poudriere commands crontabbed or trying to run while the bulk is active".

**Comment by markmi** [comment]
From a diff with the poudriere.conf.sample (ignoring comments/blank-lines):

ZPOOL=zopt0 # zoptb on amd64
USE_TMPFS="data" # yes on amd64
ALLOW_MAKE_JOBS=yes
ALLOW_MAKE_JOBS_PACKAGES="pkg ccache py* gcc* llvm* rust* ghc* *webkit* *office* chromium* iridium* mongodb*"
MAX_EXECUTION_TIME=172800
NOHANG_TIME=14400
MAX_EXECUTION_TIME_EXTRACT=14400
BUILD_AS_NON_ROOT=no

That is it for differences.

**Comment by shiorid** [comment]
> Seeing some poudriere.conf could help here.

Of course:
```
ZPOOL=rpool
ZROOTFS=/poudriere

BASEFS=/poudriere
POUDRIERE_DATA=${BASEFS}/data
DISTFILES_CACHE=${BASEFS}/distfiles
CCACHE_DIR=${BASEFS}/ccache

RESOLV_CONF=/etc/resolv.conf

USE_PORTLINT=no

CHECK_CHANGED_OPTIONS=verbose

ALLOW_MAKE_JOBS=yes

USE_TMPFS=yes

BUILDER_HOSTNAME=pkg.misaka.lan
PRESERVE_TIMESTAMP=yes
PKG_REPO_SIGNING_KEY=/usr/local/etc/ssl/keys/poudriere.key

BUILD_AS_NON_ROOT=yes
CCACHE_DIR_NON_ROOT_SAFE=yes

PORTBUILD_USER=nobody
PORTBUILD_GROUP=nobody
PORTBUILD_UID=65534
PORTBUILD_GID=65534

PRIORITY_BOOST="llvm* gcc* rust*"
```

**Comment by bdrewery** [comment]
Fixed in ports https://github.com/freebsd/freebsd-ports/commit/3dd6478b9231fc9bf79ea7c7689d9edd759f648a

**Comment by brd** [comment]
Thanks @bdrewery !
