### ISSUE TITLE
pkgclean deletes all of the .txz symlinks

### ISSUE THREAD

**Issue by heliosyne** [freebsd/poudriere#918]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
When I run poudriere pkgclean after a bulk run, it deletes all of the .txz symlinks created for backward compatibility. This isn't an operational issue for as me as I keep pkg on everything up to date, but it doesn't make sense for pkgclean to do this. If that version is making the backward-compatibility symlinks, why would pkgclean of the same version delete them?

It's also incredibly confusing because it looks like pkgclean is erroneously trying to delete the entire repo. It took me knowing we're currently in the transition phase from .txz to .pkg and repos temporarily contain compatibility symlinks .txz->.pkg.

Even worse, this then confuses poudriere-bulk into thinking none of the packages are built.

## How to reproduce
1. `poudriere bulk` you a nice fresh repo
2. Run `poudriere pkgclean`
3. Get spammed with a mass-delete prompt of .txz "files" that looks like pkgclean wants to empty the whole repo, say yes
4. Observe repo now only contains .pkg files and works fine because your pkg is new enough to use them
5. Run `poudriere bulk` again, see it want to build everything despite having a repo full of .pkg files

## Expected behavior
poudriere-pkgclean should be .txz->.pkg aware as well and not want to delete those symlinks
poudriere-bulk should recognize that missing symlinks are just missing symlinks instead of think it needs to bulk everything again

## Environment
 - Host OS [e.g. 12.2 amd64]: 12.2-RELEASE-p10 amd64
 - Jail OS [e.g. 12.0 powerpc]: 12.2-RELEASE-p10 amd64
 - Browser: [e.g. chrome, safari]: n/a
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: poudriere-devel-3.3.99.20210907_1
 - Ports branch and revision [e.g. 2020Q3 r550754]: HEAD 18c37b932

**Comment by bdrewery** [comment]
The links aren’t created by Poudriere and don’t seem to serve any purpose for anything but pkg itself, but everything gets a symlink. They are created by bsd.port.mk, I elieve erroneously. @bapt

In a newer git version I made the deleting of them less obvious during bulk, but not yet pkgclean.

Do you actually need the symlinks?

Regards,
Bryan Drewery

**Comment by bdrewery** [comment]
> poudriere-bulk should recognize that missing symlinks are just missing symlinks instead of think it needs to bulk everything again

Note that the symlinks have no bearing on build decisions because they are not expected outputs of `foo.pkg`. They are just distractions here.

**Comment by heliosyne** [comment]
> Do you actually need the symlinks?

I don't need them because I have control over all of the consumers of the repo, and everything runs the same version of pkg
