### ISSUE TITLE
RFC: Setting ZFS compress to gzip-9 during install

### ISSUE THREAD

**Issue by davidchisnall** [freebsd/poudriere#926]
## What is your proposal?

During image building for ZFS targets, set the compress for the pool to gzip-9 and then set it to lz4 before exporting the image.

## What is the existing behavior, if any?

Currently, lz4 compression is set on the pool

## What is the motivation / use case for the change?

An ZFS disk image for 13-STABLE currently consumes 547M with lz4, 377M with gzip-9.  Using gzip-9 is a significant space saving (31% smaller).  

It is not recommended to use gzip-9 during normal execution because it is much slower, especially on the compress path.  Most of the files in the base image are not modified in normal operation and so will be read once (with a performance hit on first use) and then typically sit in the ARC / buffer cache.  

Setting the default compression back to lz4 at the end means we get the performance benefits of LZ4 for any files that are created later.

There are two disadvantages to this approach:

 - Loading files with gzip-9 is slower (I have not measured what the overall performance hit is here, but I expect it to be small because most file I/O is not reading files that are part of the base image install).
 - Files stored later do not take advantage of deduplication with things in the base image (I don't consider this a significant drawback because we don't enable dedup on the root, but it might be a problem for images used to run many jails that want to use dedup with the base system)

## Did you consider any alternatives?

No.

## Is this really a ports feature request?

No, this relates only to ZFS VM image building.

## Additional context

I have a patch that does this locally.  If this is useful and there is consensus on how it should be exposed to the user, I can tidy it up and raise a PR.

**Comment by davidchisnall** [comment]
It looks as if [loader can't boot from gzip-compressed ZFS](https://bugs.freebsd.org/bugzilla//show_bug.cgi?id=153173), so for this to actually be useful that would need to be fixed first.

**Comment by davidchisnall** [comment]
@grahamperrin, as I understand it, #794 relates to the ZFS filesystems used by Poudriere during build.  This issue relates to ZFS filesystems created during image creation.  I'd like ZFS images to be as small as possible so that VM deployment is faster and we can use the smaller VM classes.

@clausecker, it looks like zstd was added to ZFS after 12 (where I'm currently running tests).  Is it supported for booting?

**Comment by clausecker** [comment]
@davidchisnall I do not know if it is supported for booting.
