### ISSUE TITLE
pkgclean.sh: POUDRIERE_BUILD_TYPE: parameter not set

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#930]
## Prerequisites

- ☑ Have you checked for an existing issue describing your problem?
- ☑ Are you running the latest version?
- ☑ Is your ports tree recent?
- ☑ Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug

`poudriere pkgclean` behaves somewhat strangely where, reportedly, no packages exist. 

```text
root@mowa219-gjp4-hello-060-vm:~ # poudriere pkgclean -A -n -j 12
[00:00:00] Cleaning in previously failed build directory
[00:00:00] No packages exist for 12-default
[: -gt: unexpected operator
[: -gt: unexpected operator
[: -gt: unexpected operator
/usr/local/share/poudriere/pkgclean.sh: POUDRIERE_BUILD_TYPE: parameter not set
root@mowa219-gjp4-hello-060-vm:~ # 
```

## How to reproduce

1. `poudriere pkgclean -A -n -j 12`

## Expected behavior

2. dry run removal of all packages (or, as observed above, a message that no packages exist) **without** messages about unexpected operators and non-set parameters

## Environment

 - Host OS: FreeBSD 12.2-RELEASE-p10
 - Jail OS: FreeBSD 12.2-RELEASE-p10
 - Browser: not applicable
 - Poudriere Version: poudriere-devel-3.3.99.20210907_1
 - Ports branch and revision: I can't remember how to get this information, but the tree is up-to-date.

## Additional context

I observed this behaviour with `pkgclean` whilst trying to troubleshoot `poudriere bulk` operations that neither build, nor fetch packages. Related typescript: 

[typescript, poudriere bulk.txt](https://github.com/freebsd/poudriere/files/7394642/typescript.poudriere.bulk.txt)

Re: [poudriere-bulk(8): pkg package missing | The FreeBSD Forums](https://forums.freebsd.org/threads/poudriere-bulk-8-pkg-package-missing.82516/) removal of `⋯/.building` seemed to work around the `poudriere bulk` issue with FreeBSD 14.0-CURRENT but not with FreeBSD 12.2-RELEASE-p10. (I'm somewhat confused, sorry.)

**Comment by bdrewery** [comment]
I forget which commit fixed this but a recent -devel update definitely does.
