### ISSUE TITLE
Man page out of sync

### ISSUE THREAD

**Issue by ari** [freebsd/poudriere#939]
Man page on FreeBSD site:

https://www.freebsd.org/cgi/man.cgi?query=poudriere-bulk&apropos=0&sektion=8&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html

includes reference to "overlays" feature. However current release poudriere-3.3.7_1 does not include such a feature.

Its a little hard to understand what version the poudriere-devel port refers to since it is some 3.3.0-xxx version which looks older than 3.3.7. But maybe that's mixed up.

**Comment by ari** [comment]
```
# poudriere version
3.3.7_1

# poudriere bulk -j 13 -p default -O custom -f /usr/local/etc/poudriere.d/ish_ports.list
Illegal option -O
poudriere bulk [options] [-a|-f file|cat/port ...]
```

**Comment by grahamperrin** [comment]
[256676 – manpage of poudriere-bulk(8) claims features which aren't available in 3.3.6](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256676) closed; [works as intended](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256676#c9).

**Comment by ari** [comment]
In which way does this work as intended?

**Comment by grahamperrin** [comment]
From linked comment 9: 

> … poudriere-devel wins because it is alphabetically last. …

Technically, I understand this. 

Emotionally, I empathise with <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256676#c5>

**Comment by grahamperrin** [comment]
If you have not already found the manual pages here in GitHub: 

* https://github.com/freebsd/poudriere/wiki/poudriere-bulk.8
* https://github.com/freebsd/poudriere/wiki/poudriere-bulk.8-devel

– and so on. 

----

Incidentally, 

https://github.com/freebsd/poudriere/issues/939#issue-1040683994

> … what version the poudriere-devel port refers to since it is some 3.3.0-xxx version …

More accurately, <https://www.freshports.org/ports-mgmt/poudriere-devel/#history> all recent versions are superior 3.3.99.2021⋯

**Comment by ari** [comment]
Thanks. I commented on the FreeBSD bug page.

**Comment by grahamperrin** [comment]
Thanks. 

I reckon, <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=256676#c10> should be a basis of a new bug (enhancement request) – at this stage, not too specific (in recent weeks a complementary idea has been at the back of my mind …). 

The most proper place to discuss might be the freebsd-doc list <https://lists.freebsd.org/archives/freebsd-doc/>, although plain text communication is a killer when I want to think visually. @ari please, are you a member of FreeBSD Forums?

**Comment by ari** [comment]
I dip into the forums every so often, but tend to interact more on the mailing lists. At any rate, not sure there is a point littering the bug tracker with feature requests unless someone with the skills is interested in taking up this work.
