### ISSUE TITLE
Automated Regression Test suite

### ISSUE THREAD

**Issue by bapt** [freebsd/poudriere#94]
We need automated tests. Poudriere has many features that are easily broken by refactoring. I expect the suite to take hours-days to run, but will give us some confidence before releasing.

The longest part will be the jail install/upgrade testing.

We should use our own custom ports tree as we are not so much interested in ports framework/features, but only that dependencies are looked up correctly, failures in each phase of a port build are handled properly, jail cleans up properly, etc. We may even need multiple trees depending on the test case.

Ideally this would automatically jail itself as well.

**Comment by bdrewery** [comment]
It's started in 3.2
