### ISSUE TITLE
Poudriere doesn't allow flavors to depend on each other

### ISSUE THREAD

**Issue by yurivict** [freebsd/poudriere#950]
This [line](https://github.com/freebsd/poudriere/blob/master/src/share/poudriere/common.sh#L6658) imposes the limitation that dependencies must have a different origin.

This is an unnecessary limitation that poudriere shouldn't impose.

Such situation is handled by the ports tree fine. Poudriere shouldn't have additional checks that aren't relevant to building packages.

**Comment by mat813** [comment]
A port cannot dépend on itself. If you are doing this, you are abusing flavors to make subpackages.

**Comment by yurivict** [comment]
Ok.
