### ISSUE TITLE
Packages fetching happens before the packages may be removed

### ISSUE THREAD

**Issue by AMDmi3** [freebsd/poudriere#954]
## Prerequisites
- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [x] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
I've enabled `PACKAGE_FETCH_BRANCH` feature found in poudriere-devel with `PACKAGE_FETCH_WHITELIST` set to gcc, llvm and some other ports. I've discovered that sometimes it rebuilds packages it was configured to fetch. Unfortunately, I've lost a full log, but the problem was that poudriere has removed gcc packages because some of their depends have changed, and that happened AFTER it tried to fetch them.

## How to reproduce
- Set up package fetching with `PACKAGE_FETCH_BRANCH` and `PACKAGE_FETCH_WHITELIST`
- Run a build, witness that packages specified in `PACKAGE_FETCH_WHITELIST` are fetched instead of being build
- Run a build again in some days, ensure that depends for the fetched packages have changed. Witness that packages are rebuilt instead of being fetched.

## Expected behavior
- Packages specified in `PACKAGE_FETCH_WHITELIST` are never built (unless maybe specified on the command line or in `bulk -f` file), e.g. are fetched and not removed afterwards/instead.

## Environment
 - Poudriere Version [e.g. 3.3.1 or git hash or port version]: poudriere-devel-3.3.99.20211017_2

**Comment by bdrewery** [comment]
This will be fixed by #822 which removes the excessive delete for incremental rebuilds. There is a new added assertion if a package that was fetched is subsequently deleted before the build starts.

**Comment by f451-fbsd** [comment]
+1 for this. I build on rpi4 and would really like to see this work. If you'd like, i'm happy to test any patches
