### ISSUE TITLE
pkgs contain non URL safe characters

### ISSUE THREAD

**Issue by ari** [freebsd/poudriere#976]
## Setup

1. Standard, simple poudriere installation.
2. build openjdk11
3. publish output to AWS S3 and cloudfront

I'm using a script like:

```
#!/bin/sh

event="$1"

if [ "$event" = "done" ] || [ "$event" = "" ] ; then

  export AWS_ACCESS_KEY_ID=**********
  export AWS_SECRET_ACCESS_KEY=********
  export AWS_DEFAULT_REGION=ap-southeast-2

  CMD="/usr/local/bin/aws"

  ${CMD} s3 sync --delete $(realpath /var/poudriere/data/packages/13-default/.latest) s3://ports/FreeBSD:13:amd64

fi

exit 0
```

In order to get https, I'm using cloudfront in front of S3. Cloudfront has built-in parsing for special URL characters like '+' which maps to a space in the file path. So...

```
# pkg upgrade -y openjdk11
Updating ish repository catalogue...
Fetching packagesite.txz: 100%  185 KiB 189.4kB/s    00:01
Processing entries: 100%
ish repository update completed. 676 packages processed.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	openjdk11: 11.0.13+8.1 -> 11.0.14+9.1

Number of packages to be upgraded: 1

159 MiB to be downloaded.
pkg: https://d1r5qhi42dpyw8.cloudfront.net/FreeBSD:13:amd64/All/openjdk11-11.0.14+9.1.pkg: Forbidden
```

Having a + in the URL like this isn't expected and should be escaped.

Not sure whether this is a pkg-fetch bug or something poudriere should do better when building index files.

**Comment by tomhukins** [comment]
Try URI encoding the `+` symbol to `%2B` and requesting https://d1r5qhi42dpyw8.cloudfront.net/FreeBSD:13:amd64/All/openjdk11-11.0.14%2B9.1.pkg instead.  See [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986/#section-2) for an explanation.

**Comment by tomhukins** [comment]
> how am I going to get "pkg fetch" to do that?

It already does.  If I run `pkg fetch openjdk11` using the default `pkg.FreeBSD.org` with its URL set to `pkg+http://pkg.FreeBSD.org/${ABI}/latest`, I see the command run successfully:
```
Updating FreeBSD repository catalogue...
Fetching packagesite.pkg: 100%    6 MiB   3.4MB/s    00:02    
Processing entries: 100%
FreeBSD repository update completed. 31440 packages processed.
All repositories are up to date.
The following packages will be fetched:

New packages to be FETCHED:
        openjdk11: 11.0.14+9.1 (159 MiB: 100.00% of the 159 MiB to download)

Number of packages to be fetched: 1

The process will require 159 MiB more space.
159 MiB to be downloaded.

Proceed with fetching packages? [y/N]: y
Fetching openjdk11-11.0.14+9.1.pkg: 100%  159 MiB  55.4MB/s    00:03
```

**Comment by ari** [comment]
Because the server is (incorrectly) handling "+" symbols? I just used tcmpdump to get data from a connection created by pkg-fetch...

```
    delish.ish.com.au.15580 > pkg0.twn.freebsd.org.http: Flags [P.], cksum 0x80e0 (incorrect -> 0xfc82), seq 1:184, ack 1, win 1027, options [nop,nop,TS val 975600196 ecr 3136747760], length 183: HTTP, length: 183
	GET /FreeBSD:13:amd64/quarterly/All/openjdk11-11.0.13+8.1.pkg HTTP/1.1
	Host: pkgmir.geo.freebsd.org
	Accept: */*
	User-Agent: pkg/1.17.5
	Range: bytes=6733824-
	Connection: close
```

You can clearly see the GET does not encode the +.

**Comment by tomhukins** [comment]
Yes, you're right.  I guess package servers generally run on nginx, which accomodates this problem.  I've been looking through the source for `pkg` and notice it calls `fetchXGet` from `libfetch`, passing it a URL processed with `fetchParseURL`.

The section of `fetchParseURL` marked _document_ escapes space characters, but nothing more.  Also it looks like it's based on RFC1738 rules, whereas the `+` escaping requirement doesn't appear until RFC3986.

So, I suspect the bug lies in libfetch, not poudriere or pkg, but I'm not certain about this.

**Comment by ari** [comment]
I got to roughly the same point in my debugging and got lost in the code. C is not really my thing since I read K&R in 1985. I've been posting to the freebsd-ports list, but there is no response there. I'm loathe to create a bug report which will sit there unseen for the next 5 years.

Is there someone who works on this code we can send this to?

Alternatively poudriere could rewrite these files with a space. Ugly but it works in my testing.

**Comment by ari** [comment]
There are two existing bugs which related to encoding in libfetch.

* https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=116005
* https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=127280

They date back to 2018 so I don't think anyone is looking at these. I wonder if the escaping bugs have security implications, passing passwords into logs when you don't expect them to or fetching resources you didn't mean to.

**Comment by ronaldklop** [comment]
I get 403 Forbidden with
https://d1r5qhi42dpyw8.cloudfront.net/FreeBSD:13:amd64/All/openjdk11-11.0.14+9.1.pkg
as well as with:
https://d1r5qhi42dpyw8.cloudfront.net/FreeBSD:13:amd64/All/openjdk11-11.0.14%2B9.1.pkg

And as 403 Forbidden is not 404 Not Found or Bad Request the server suggests the problem is in authentication and not in the wrong file name.

**Comment by ari** [comment]
Cloudfront throws 403 for not found when there are no permissions to list objects in the bucket. https://aws.amazon.com/premiumsupport/knowledge-center/s3-website-cloudfront-error-403/

Since this is our production repo, your URLs are now pointing to stale versions of openjdk so that version no longer exists. And I've written a script to replace + with space and workaround the bug.

**Comment by ari** [comment]
Thanks to @ronaldklop I see that in fact FreeBSD is correct and AWS is wrong according to [RFC 1866](https://datatracker.ietf.org/doc/html/rfc1866) Plus encoding should only happen in query params.

AWS S3 is wrong and I've found other threads complaining about this. Its unlikely to be fixed.

Here is my new hook to sync to S3 which works around this issue.

```
#!/usr/local/bin/bash

event="$1"
path="$(realpath /var/poudriere/data/packages/13-default/.latest)"

if [ "$event" = "done" ] || [ "$event" = "" ] ; then

  for file in $(find "${path}" -type f -name *[+]*)
    do
      mv "${file}" "${file//[+]/ }"
    done

  export AWS_ACCESS_KEY_ID=*******
  export AWS_SECRET_ACCESS_KEY=********
  export AWS_DEFAULT_REGION=ap-southeast-2

  CMD="/usr/local/bin/aws"

  ${CMD} s3 sync --exclude "*.txz" --delete "${path}" s3://ports/FreeBSD:13:amd64

fi

exit 0
```
