### ISSUE TITLE
cross-compiling poudriere jail for arm.armv6 on amd64 creates nxb-bin which doesn't make arm object files

### ISSUE THREAD

**Issue by midnightmagic** [freebsd/poudriere#991]
## Prerequisites
- [x ] Have you checked for an existing issue describing your problem?
- [x ] Are you running the latest version?
- [x ] Is your ports tree recent?
- [x ] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)?

## Describe the bug
On an amd64 host, creating a cross-compiling jail for -a arm.armv6 with stable/13 creates /nxb* tree inside the jail which doesn't actually cross-compile. When using main branch (14-current right now) 1400056, it works fine.

## How to reproduce
On a 13.1-STABLE x86_64, run:

poudriere jail -c -j 13arm6 -v stable/13 -a arm.armv6 -m git+https -x
poudriere jail -s -j 13arm6 -p yourPoudrierePortsTree
chroot (into the top-level of the jail)
(attempt to compile Hello World using /nxb-bin/usr/bin/cc)
(Observe it can't be linked against /usr/lib/crt1.o and is actually just a plain x86_64 object.)

Check that main works:
poudriere jail -c -j 14arm6 -v main -a arm.armv6 -m git+https -x
poudriere jail -s -j 14arm6
chroot (into the top-level of the jail)
(attempt to compile a Hello World using /nxb-bin/usr/bin/cc
(Observe it works fine.)

## Expected behavior
Functional cross-compiling jail /nxb* tree.

## Screenshots
n/a

## Environment
Host OS:
FreeBSD unit 13.1-STABLE FreeBSD 13.1-STABLE #0 stable/13-n250398-62c0ba91c78f: Mon Apr 11 21:13:07 UTC 2022
Jail OS:
13.1-RC2 commitid 0ae09fb966d534e526101be566c4ccc1b2815cb3 on stable/13 (i think?)
Poudriere Version:
poudriere-3.3.7_1
Ports branch and revision [e.g. 2020Q3 r550754]:
Not applicable, but this results in a failing armv6 cross-compiling jail which means even the first ports-mgmt/pkg will mysteriously fail—with no config.log or anything because autosetup/autosetup-find-tclsh will silently just complain that /nxb-bin/usr/bin/cc can't create executables without actually explaining why.

## Additional context
I'm not currently enough up on poudriere jail building to have already determined why /nxb-bin/* is populated with non-cross-compiling bins for 13.1-RC2, but it does work in 14-CURRENT. I'm open to extensive debugging requests. My machine requires a good 30 minutes unfortunately to recreate jails, so keep that in mind if you request some kind of bisection. :-)

**Comment by stewiem2000** [comment]
After a bit of digging, manually applying [this patch](https://github.com/freebsd/freebsd-src/commit/e2e2c622c35f3e54dbae88e3de3e48c51dbb4ebd) to a freshly-created 13.1-RELEASE arm64.aarch64 jail, and then update+cross-compiling (poudriere jail -u -x -j ...) solved the issue for me — let's hope it's MFC'd soon!

**Comment by kevans91** [comment]
@igalic pointed me this way -- sorry, I hadn't realized the commit that one was fixing was MFC'd. I've done so at:

stable/13 - 3afe1c2e1817
stable/12 - 702e1e5d1ef

**Comment by bdrewery** [comment]
Thanks @kevans91

**Comment by midnightmagic** [comment]
Thank you very much! Much love for the team. Please have a great weekend!
