### ISSUE TITLE
poudriere-options(8) -s advice to use 'make config'

### ISSUE THREAD

**Issue by grahamperrin** [freebsd/poudriere#992]
## Prerequisites

☑ Have you checked for an existing issue describing your idea?

## What is your proposal?

Please check the sanity of the advice to use `make config` in response to use of [poudriere-options(8)](https://github.com/freebsd/poudriere/wiki/poudriere-options.8). 

## What is the existing behavior, if any?

For example: 

```text
% poudriere options -ns editors/libreoffice
[00:00:00] Working on options directory /usr/local/etc/poudriere.d/options
===> The following configuration options are available for libreoffice-7.3.2.2_2:
     COINMP=off: Enable CoinMP (deprecated) math solver
     CUPS=on: CUPS printing system support
     DOCS=on: Build and/or install documentation
     GNOME=off: GNOME desktop environment support
     GTK3=on: GTK+ 3 GUI toolkit support
     GTK4=off: GTK+ 4 GUI toolkit support (broken)
     JAVA=on: Add Java support (XML filters, macros, DB connections)
     KF5=on: KF5/Qt5 GUI toolkit support (implies QT5)
     LTO=on: Use Link-Time Optimization
     MARIADB=off: Build with MariaDB/MySQL-SDBC driver
     MMEDIA=on: Enable multimedia backend for Impress
     PDFIUM=on: Enable PDFium secure engine
     PGSQL=off: Build with PostgreSQL-SDBC driver
     QT5=on: Qt5 GUI toolkit support (default visual style)
     SDK=off: Build with SDK
     TEST=off: Run all regression tests
     WEBDAV=on: Enable WebDAV protocol
===> Use 'make config' to modify these settings
% 
```

## What is the motivation / use case for the change?

Every time I see that last line: 

`===> Use 'make config' to modify these settings`

– in response to poudriere-options(8), the line confuses me. 

## Did you consider any alternatives?

Yes, however (unless I'm missing something) I can't imagine a use of `make config` that will properly modify a file such as this: 

`/usr/local/etc/poudriere.d/options/editors_libreoffice/options`

– for subsequent use with e.g. poudriere-bulk(8). 

## Is this really a ports feature request?

No.

## Example

Please see above. 

## Additional context

If I'm missing something: sorry.

**Comment by bdrewery** [comment]
Yeah confusing for sure. It's buried in `make showconfig`. This is what I did for now:
```
===> Use 'make config' to modify these settings
[00:00:01] Re-run poudriere options with the -c flag to modify the options.
```
