### ISSUE TITLE
pkgclean with -f option is deleting all packages

### ISSUE THREAD

**Issue by JohnSchneider** [freebsd/poudriere#997]
poudriere ~~3.3.7_1 (latest version in ports tree at the time of this bug submission)~~ 3.2.8 is deleting all packages with the pkgclean command, including those ports specified in file specified with -f option.  It complains about files with invalid file extension being in pkg repo, and then deletes both the package file and the symlink to it.

Example: <code>poudriere pkgclean -j 13-amd64 -f /usr/local/etc/poudriere-list -y -v</code>
Result: message about each package having an unknown file extension, deletion of the package file and deletion of the symlink to it.
Confirmation:
<code>root@pkg:/ # ls -l /usr/local/poudriere/data/packages/13-amd64-default/.latest/All/</code>
<code>total 0</code>

**Comment by bdrewery** [comment]
I just tested this and while it does complain about and delete older `.txz` symlinks, it did not delete the packages I expected to remain.

Please provide the ports checkout version you are using (as was requested by the template you deleted), and provide output of the command deleting everything, showing files before and after.

**Comment by bdrewery** [comment]
I suspect that https://cgit.freebsd.org/ports/commit/?id=dfae67d10c3f2b6dbde7d6e3280455cd87f9f15c is causing the issue here since there is no special handling for this new extension.

**Comment by JohnSchneider** [comment]
Here is the FreeBSD version I'm using, using a ports tree updated a few days ago:
<code>root@pkg:/ # uname -rU</code>
<code>13.1-STABLE 1301502</code>

This is the exact command used:
<code>poudriere pkgclean -j 13-amd64 -f /usr/local/etc/poudriere-list -y -v</code>

Attached my ports list file (added a .txt extension so ithub would allow me to attach):
[poudriere-list.txt](https://github.com/freebsd/poudriere/files/8639867/poudriere-list.txt)

**Comment by JohnSchneider** [comment]
Correction to original issue submission: my Poudriere version is actually 3.2.8.
<code>root@pkg:/ # poudriere version</code>
<code>3.2.8</code>

**Comment by JohnSchneider** [comment]
Upgraded to poudriere 3.3.7_1, and now pkgclean only deletes the .txz files. Updated original issue description to correct version stated.  Closing issue with this comment.

**Comment by bdrewery** [comment]
> Correction to original issue submission: my Poudriere version is actually 3.2.8. `root@pkg:/ # poudriere version` `3.2.8`

🤦 

Thanks for double checking that!
